-- GENERATED by packs/_lib/generate.py - DO NOT EDIT BY HAND.
-- pack=backload_matching mapping_source_id=synthetic
ALTER SESSION SET query_tag = '{"origin":"sf_sit-is-fleet","name":"oss-install-fleet-apps","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql","module":"pack-setup"}}';
CREATE DATABASE IF NOT EXISTS FLEET_APP COMMENT='{"origin":"sf_sit-is-fleet","name":"oss-install-fleet-apps","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';
ALTER DATABASE FLEET_APP SET DATA_RETENTION_TIME_IN_DAYS = 0;
CREATE SCHEMA IF NOT EXISTS FLEET_APP.BACKLOAD_MATCHING COMMENT='{"origin":"sf_sit-is-fleet","name":"oss-install-fleet-apps","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';

CREATE OR REPLACE VIEW FLEET_APP.BACKLOAD_MATCHING.VW_CONFIG
  COMMENT='{"origin":"sf_sit-is-fleet","name":"oss-install-fleet-apps","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}' AS
SELECT * FROM FLEET_INTELLIGENCE.BACKLOAD_MATCHING.CONFIG;

CREATE OR REPLACE VIEW FLEET_APP.BACKLOAD_MATCHING.VW_VEHICLE_CLASS
  COMMENT='{"origin":"sf_sit-is-fleet","name":"oss-install-fleet-apps","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}' AS
SELECT * FROM FLEET_INTELLIGENCE.BACKLOAD_MATCHING.VEHICLE_CLASS_PROFILE;

CREATE OR REPLACE VIEW FLEET_APP.BACKLOAD_MATCHING.VW_MATCH_PARAMS
  COMMENT='{"origin":"sf_sit-is-fleet","name":"oss-install-fleet-apps","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}' AS
SELECT * FROM FLEET_INTELLIGENCE.BACKLOAD_MATCHING.MATCH_PARAMS;

CREATE OR REPLACE VIEW FLEET_APP.BACKLOAD_MATCHING.VW_PROPOSAL_DECISIONS
  COMMENT='{"origin":"sf_sit-is-fleet","name":"oss-install-fleet-apps","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}' AS
SELECT * FROM FLEET_INTELLIGENCE.BACKLOAD_MATCHING.PROPOSAL_DECISIONS;

CREATE OR REPLACE VIEW FLEET_APP.BACKLOAD_MATCHING.VW_TRAILERS
  COMMENT='{"origin":"sf_sit-is-fleet","name":"oss-install-fleet-apps","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}' AS
-- MULTI-REGION. No CONFIG filter: REGION is carried as a dimension and the
-- per-region computations below are PARTITIONED rather than pre-filtered.
-- Three things had to become per-region for that to stay correct:
--   1. home_anchor averaged POI coordinates. Across two regions that
--      average lands in the ocean between them, so it is grouped BY REGION
--      and joined on the vehicle's own region.
--   2. `cls` resolved the vehicle class from the single CONFIG vehicle_type.
--      It now JOINs on each vehicle's own VEHICLE_TYPE, so a mixed fleet
--      gets the right payload band per vehicle. An unknown vehicle_type
--      still yields no row for that vehicle (the inner join replaces the
--      old `EXISTS (SELECT 1 FROM cls)` guard, per vehicle instead of
--      globally).
--   3. last_drop needs no filter at all - it groups by VEHICLE_ID, which is
--      globally unique (measured: 0 colliding ids across datasets).
WITH last_drop AS (
  SELECT VEHICLE_ID,
         MAX_BY(DESTINATION_LON, TRIP_END)    AS DROPOFF_LON,
         MAX_BY(DESTINATION_LAT, TRIP_END)    AS DROPOFF_LAT,
         MAX_BY(DESTINATION_POI_ID, TRIP_END) AS DROPOFF_POI_ID,
         MAX(TRIP_END)                        AS LAST_TRIP_END
  FROM SYNTHETIC_DATASETS.UNIFIED.V_FACT_TRIPS_CURRENT
  GROUP BY VEHICLE_ID
),
home_anchor AS (
  SELECT REGION, AVG(LAT) AS HOME_LAT, AVG(LNG) AS HOME_LON
  FROM SYNTHETIC_DATASETS.UNIFIED.V_DIM_POIS_CURRENT
  GROUP BY REGION
),
p AS (
  SELECT COALESCE(MAX(IFF(PARAM_KEY='PLANNING_LEAD_DAYS', TRY_TO_DOUBLE(PARAM_VALUE), NULL)), 4) AS LEAD_DAYS
  FROM FLEET_APP.BACKLOAD_MATCHING.VW_MATCH_PARAMS
)
SELECT
  f.VEHICLE_ID                                        AS TRAILER_ID,
  f.REGION                                            AS OPERATING_COUNTRY,
  f.REGION                                            AS REGION,
  FLEET_APP.CORE.REGION_LABEL(f.REGION)               AS REGION_LABEL,
  COALESCE(h.NAME, 'Home Depot')                      AS HOME_DEPOT,
  COALESCE(h.LNG, ha.HOME_LON)                        AS HOME_LON,
  COALESCE(h.LAT, ha.HOME_LAT)                        AS HOME_LAT,
  f.VEHICLE_TYPE                                      AS CURRENT_LOAD,
  COALESCE(d.NAME, 'Drop-off')                        AS DROPOFF_CITY,
  ld.DROPOFF_LON                                      AS DROPOFF_LON,
  ld.DROPOFF_LAT                                      AS DROPOFF_LAT,
  ld.LAST_TRIP_END                                    AS ETA_TS,
  DATEDIFF('minute', CURRENT_TIMESTAMP(), ld.LAST_TRIP_END) AS ETA_MIN,
  -- Dispatch-time availability: a vehicle still in transit is plannable
  -- NOW for the moment it frees up, so its free time is that future
  -- arrival. Where the synthetic drop-off is already past there is no
  -- future arrival to use, so the free time is spread deterministically
  -- across PLANNING_LEAD_DAYS. AVAILABILITY_BASIS reports which applied
  -- rather than hiding the synthesis.
  CASE
    WHEN ld.LAST_TRIP_END > CURRENT_TIMESTAMP() THEN ld.LAST_TRIP_END
    ELSE DATEADD('minute',
           MOD(ABS(HASH(f.VEHICLE_ID)), GREATEST(1, ((SELECT LEAD_DAYS FROM p) * 1440)::INT)),
           CURRENT_TIMESTAMP())
  END                                                 AS AVAILABLE_FROM_TS,
  IFF(ld.LAST_TRIP_END > CURRENT_TIMESTAMP(), 'eta', 'projected') AS AVAILABILITY_BASIS,
  -- Chain target under TARGET_MODE=home_depot. A per-request target
  -- (dispatcher_choice) is supplied at query time and falls back to this.
  COALESCE(h.LNG, ha.HOME_LON)                        AS TARGET_LON,
  COALESCE(h.LAT, ha.HOME_LAT)                        AS TARGET_LAT,
  COALESCE(h.NAME, 'Home Depot')                      AS TARGET_LABEL,
  ST_DISTANCE(
    ST_MAKEPOINT(ld.DROPOFF_LON, ld.DROPOFF_LAT),
    ST_MAKEPOINT(COALESCE(h.LNG, ha.HOME_LON),
                 COALESCE(h.LAT, ha.HOME_LAT))
  ) / 1000.0                                          AS TARGET_GAP_KM,
  'IN_TRANSIT'                                        AS STATUS,
  FALSE                                               AS HAZMAT_CERT,
  -- Synthetic equipment fit, assigned deterministically per vehicle from
  -- the same vocabulary the offer pool uses, so ENFORCE_EQUIPMENT_FIT is
  -- demonstrable end to end. Seeded OFF: a real fleet supplies this from
  -- its own asset master.
  ARRAY_CONSTRUCT('TAUTLINER','BOX','REEFER','MEGA','FLATBED')[
    MOD(ABS(HASH(f.VEHICLE_ID)), 5)]::VARCHAR         AS VEHICLE_EQUIPMENT,
  c.PAYLOAD_KG_TYP::NUMBER                            AS MAX_PAYLOAD_KG,
  NULLIF(f.BATTERY_RANGE_KM, 0)                       AS EV_RANGE_KM
FROM SYNTHETIC_DATASETS.UNIFIED.V_DIM_FLEET_CURRENT f
JOIN last_drop ld ON ld.VEHICLE_ID = f.VEHICLE_ID
JOIN FLEET_APP.BACKLOAD_MATCHING.VW_VEHICLE_CLASS c ON c.VEHICLE_TYPE = f.VEHICLE_TYPE
LEFT JOIN home_anchor ha ON ha.REGION = f.REGION
LEFT JOIN SYNTHETIC_DATASETS.UNIFIED.V_DIM_POIS_CURRENT h ON h.LOCATION_ID = f.HOME_LOCATION_ID
LEFT JOIN SYNTHETIC_DATASETS.UNIFIED.V_DIM_POIS_CURRENT d ON d.LOCATION_ID = ld.DROPOFF_POI_ID;

CREATE OR REPLACE VIEW FLEET_APP.BACKLOAD_MATCHING.VW_INTERNAL_VOLUMES
  COMMENT='{"origin":"sf_sit-is-fleet","name":"oss-install-fleet-apps","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}' AS
-- MULTI-REGION. `cls` now JOINs each trip's own VEHICLE_TYPE instead of
-- resolving one CONFIG value, and the pool bound is applied PER REGION -
-- a single global QUALIFY would let the region with the most recent trips
-- consume the whole pool and starve every other region of internal volumes.
--
-- POOL SIZE IS DERIVED FROM THE FLEET, NOT TRUNCATED TO A CONSTANT.
-- Every row here is a historical trip reinterpreted as an open order, so
-- the pool size is a modelling choice with no natural bound in the data.
-- It used to be `<= INTERNAL_POOL_CAP` (5000), which meant the number the
-- dispatcher reads was the CAP in a busy region and the TRUE trip count in
-- a quiet one: measured 16,535 SanFrancisco trips truncated to exactly
-- 5,000 next to 332 in Europe, i.e. one tile with two different meanings.
-- Sizing by INTERNAL_LOADS_PER_TRAILER makes it mean "loads waiting per
-- vehicle" everywhere and scales with any preset. INTERNAL_POOL_CAP is
-- retained as an absolute ceiling.
--
-- Do NOT filter this pool by PLANNING_LEAD_DAYS instead: MEASURED, that is
-- a no-op. PICKUP_FROM_TS below is GREATEST(TRIP_START, now + hash), and
-- TRIP_START is historical, so the synthetic future value always wins and
-- every row already lands inside the horizon (4,975 of 5,000 within 4
-- days, none in the past). Pickup feasibility is enforced downstream by
-- MAX_PICKUP_HORIZON_DAYS in VW_CANDIDATES.
WITH p AS (
  SELECT
    COALESCE(MAX(IFF(PARAM_KEY='PLANNING_LEAD_DAYS', TRY_TO_DOUBLE(PARAM_VALUE), NULL)), 4)    AS LEAD_DAYS,
    COALESCE(MAX(IFF(PARAM_KEY='INTERNAL_POOL_CAP',  TRY_TO_DOUBLE(PARAM_VALUE), NULL)), 5000) AS POOL_CAP,
    COALESCE(MAX(IFF(PARAM_KEY='INTERNAL_LOADS_PER_TRAILER', TRY_TO_DOUBLE(PARAM_VALUE), NULL)), 4) AS LOADS_PER_TRAILER
  FROM FLEET_APP.BACKLOAD_MATCHING.VW_MATCH_PARAMS
),
-- Fleet population per region. Counted from the shared fleet dimension
-- rather than VW_TRAILERS so both copies of this view (the FLEET_APP one
-- here and the FLEET_INTELLIGENCE one in the admin app's init.ts) can use
-- an identical basis, and so the ratio does not move when a vehicle
-- temporarily has no recorded drop-off.
fleet_size AS (
  SELECT REGION, COUNT(DISTINCT VEHICLE_ID) AS TRAILERS
  FROM SYNTHETIC_DATASETS.UNIFIED.V_DIM_FLEET_CURRENT
  GROUP BY REGION
)
SELECT
  'INT-' || LPAD(ROW_NUMBER() OVER (ORDER BY t.TRIP_START)::VARCHAR, 5, '0') AS ID,
  t.REGION                                                                    AS REGION,
  FLEET_APP.CORE.REGION_LABEL(t.REGION)                                       AS REGION_LABEL,
  COALESCE(o.NAME, 'Origin')                                                  AS PICKUP_CITY,
  t.ORIGIN_LON                                                                AS PICKUP_LON,
  t.ORIGIN_LAT                                                                AS PICKUP_LAT,
  COALESCE(d.NAME, 'Destination')                                             AS DROPOFF_CITY,
  t.DESTINATION_LON                                                           AS DROPOFF_LON,
  t.DESTINATION_LAT                                                           AS DROPOFF_LAT,
  GREATEST(
    t.TRIP_START,
    DATEADD('minute',
      MOD(ABS(HASH(t.TRIP_ID)), GREATEST(1, ((SELECT LEAD_DAYS FROM p) * 1440)::INT)) + 30,
      CURRENT_TIMESTAMP())
  )                                                                           AS PICKUP_FROM_TS,
  DATEADD(hour, 4,
    GREATEST(
      t.TRIP_START,
      DATEADD('minute',
        MOD(ABS(HASH(t.TRIP_ID)), GREATEST(1, ((SELECT LEAD_DAYS FROM p) * 1440)::INT)) + 30,
        CURRENT_TIMESTAMP())
    )
  )                                                                           AS PICKUP_TO_TS,
  (
    c.SHIPMENT_KG_MIN
    + ABS(HASH(t.TRIP_ID)) % NULLIF((c.SHIPMENT_KG_MAX - c.SHIPMENT_KG_MIN), 0)
  )::NUMBER                                                                   AS WEIGHT_KG,
  'B2B pallets'                                                               AS PRODUCT,
  FALSE                                                                       AS HAZMAT
FROM SYNTHETIC_DATASETS.UNIFIED.V_FACT_TRIPS_CURRENT t
JOIN FLEET_APP.BACKLOAD_MATCHING.VW_VEHICLE_CLASS c ON c.VEHICLE_TYPE = t.VEHICLE_TYPE
LEFT JOIN SYNTHETIC_DATASETS.UNIFIED.V_DIM_POIS_CURRENT o ON o.LOCATION_ID = t.ORIGIN_POI_ID
LEFT JOIN SYNTHETIC_DATASETS.UNIFIED.V_DIM_POIS_CURRENT d ON d.LOCATION_ID = t.DESTINATION_POI_ID
LEFT JOIN fleet_size fs ON fs.REGION = t.REGION
-- GREATEST(1, ...) so a region that has trips but no countable trailers
-- still yields a non-empty pool rather than silently emptying the page.
QUALIFY ROW_NUMBER() OVER (PARTITION BY t.REGION ORDER BY t.TRIP_START DESC)
        <= LEAST(
             (SELECT POOL_CAP FROM p),
             GREATEST(1, CEIL(COALESCE(fs.TRAILERS, 0) * (SELECT LOADS_PER_TRAILER FROM p)))
           );

CREATE OR REPLACE VIEW FLEET_APP.BACKLOAD_MATCHING.VW_EXTERNAL_OFFERS
  COMMENT='{"origin":"sf_sit-is-fleet","name":"oss-install-fleet-apps","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}' AS
-- MULTI-REGION. An offer row carries a REGION but no VEHICLE_TYPE, so the
-- class band is resolved through each region's OWN active dataset
-- (DIM_DATASETS) rather than the single CONFIG vehicle_type. That keeps the
-- weight rescaling correct when two regions run different asset modes.
WITH reg_vt AS (
  SELECT REGION, VEHICLE_TYPE
  FROM FLEET_INTELLIGENCE.CORE.DIM_DATASETS
  WHERE IS_ACTIVE
  QUALIFY ROW_NUMBER() OVER (PARTITION BY REGION ORDER BY CREATED_AT DESC) = 1
),
p AS (
  SELECT COALESCE(MAX(IFF(PARAM_KEY='PLANNING_LEAD_DAYS', TRY_TO_DOUBLE(PARAM_VALUE), NULL)), 4) AS LEAD_DAYS
  FROM FLEET_APP.BACKLOAD_MATCHING.VW_MATCH_PARAMS
),
-- Rebase each offer's pickup window onto the live planning horizon while
-- preserving its own window LENGTH. Generated timestamps are relative to
-- generation time, so on any dataset older than a day they already sit in
-- the past - and with forward-looking vehicle availability a past pickup
-- can never be served, which empties the external half of the demand pool
-- with no error anywhere.
shifted AS (
  SELECT
    f.*,
    GREATEST(
      f.PICKUP_FROM_TS,
      DATEADD('minute',
        MOD(ABS(HASH(f.OFFER_ID)), GREATEST(1, ((SELECT LEAD_DAYS FROM p) * 1440)::INT)) + 30,
        CURRENT_TIMESTAMP())
    ) AS PICKUP_FROM_TS_ADJ,
    GREATEST(60, COALESCE(DATEDIFF('minute', f.PICKUP_FROM_TS, f.PICKUP_TO_TS), 240)) AS WINDOW_MIN
  FROM SYNTHETIC_DATASETS.UNIFIED.V_FACT_OFFERS_CURRENT f
)
SELECT
  f.OFFER_ID,
  f.SOURCE,
  f.REGION                                 AS REGION,
  FLEET_APP.CORE.REGION_LABEL(f.REGION)    AS REGION_LABEL,
  -- SOURCE is a CHANNEL label whose values mix internal and external
  -- (INTERNAL / DISPATCH / MARKETPLACE / PARTNER_APP), so it cannot answer
  -- "did this come from outside". SOURCE_SYSTEM is the system identity: a
  -- real integration replaces the literal with its own system key, and no
  -- consumer changes. Deliberately vendor-free.
  'EXTERNAL_EXCHANGE'                      AS SOURCE_SYSTEM,
  COALESCE(f.VEHICLE_EQUIPMENT, 'ANY')     AS VEHICLE_EQUIPMENT,
  COALESCE(SUBSTR(f.REGION, 1, 2), 'US')   AS PICKUP_COUNTRY,
  COALESCE(SUBSTR(f.REGION, 1, 2), 'US')   AS DROPOFF_COUNTRY,
  COALESCE(p2.NAME, 'Pickup')              AS PICKUP_CITY,
  f.PICKUP_LON,
  f.PICKUP_LAT,
  COALESCE(d.NAME, 'Dropoff')              AS DROPOFF_CITY,
  f.DROPOFF_LON,
  f.DROPOFF_LAT,
  f.PICKUP_FROM_TS_ADJ                     AS PICKUP_FROM_TS,
  DATEADD('minute', f.WINDOW_MIN, f.PICKUP_FROM_TS_ADJ) AS PICKUP_TO_TS,
  LEAST(
    c.SHIPMENT_KG_MAX,
    GREATEST(
      c.SHIPMENT_KG_MIN,
      (c.SHIPMENT_KG_MIN + ABS(HASH(f.OFFER_ID)) % NULLIF((c.SHIPMENT_KG_MAX - c.SHIPMENT_KG_MIN), 0))::NUMBER
    )
  )                                        AS WEIGHT_KG,
  COALESCE(f.PRODUCT, 'General freight')   AS PRODUCT,
  f.PRICE_USD                              AS PRICE_USD,
  COALESCE(f.HAZMAT, FALSE)                AS HAZMAT,
  f.SOURCE || ' load: ' || COALESCE(p2.NAME, 'Pickup') || ' -> ' || COALESCE(d.NAME, 'Dropoff') AS LISTING_TEXT
FROM shifted f
JOIN reg_vt rv ON rv.REGION = f.REGION
JOIN FLEET_APP.BACKLOAD_MATCHING.VW_VEHICLE_CLASS c ON c.VEHICLE_TYPE = rv.VEHICLE_TYPE
LEFT JOIN SYNTHETIC_DATASETS.UNIFIED.V_DIM_POIS_CURRENT p2 ON p2.LOCATION_ID = f.PICKUP_POI_ID
LEFT JOIN SYNTHETIC_DATASETS.UNIFIED.V_DIM_POIS_CURRENT d  ON d.LOCATION_ID  = f.DROPOFF_POI_ID;

-- Grants (additive; roles from fleet_sa_app/app/role_binding.sql)
GRANT USAGE ON DATABASE FLEET_APP TO ROLE FLEET_APP_USER;
GRANT USAGE ON SCHEMA FLEET_APP.BACKLOAD_MATCHING TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL VIEWS IN SCHEMA FLEET_APP.BACKLOAD_MATCHING TO ROLE FLEET_APP_USER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FLEET_APP.BACKLOAD_MATCHING TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA FLEET_APP.BACKLOAD_MATCHING TO ROLE FLEET_APP_USER;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA FLEET_APP.BACKLOAD_MATCHING TO ROLE FLEET_APP_USER;
GRANT USAGE ON SCHEMA FLEET_APP.BACKLOAD_MATCHING TO ROLE FLEET_APP_OPS;
GRANT SELECT ON ALL VIEWS IN SCHEMA FLEET_APP.BACKLOAD_MATCHING TO ROLE FLEET_APP_OPS;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FLEET_APP.BACKLOAD_MATCHING TO ROLE FLEET_APP_OPS;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA FLEET_APP.BACKLOAD_MATCHING TO ROLE FLEET_APP_OPS;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA FLEET_APP.BACKLOAD_MATCHING TO ROLE FLEET_APP_OPS;
GRANT USAGE ON SCHEMA FLEET_APP.BACKLOAD_MATCHING TO ROLE FLEET_APP_ADMIN;
GRANT SELECT ON ALL VIEWS IN SCHEMA FLEET_APP.BACKLOAD_MATCHING TO ROLE FLEET_APP_ADMIN;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FLEET_APP.BACKLOAD_MATCHING TO ROLE FLEET_APP_ADMIN;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA FLEET_APP.BACKLOAD_MATCHING TO ROLE FLEET_APP_ADMIN;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA FLEET_APP.BACKLOAD_MATCHING TO ROLE FLEET_APP_ADMIN;
