/*
 * export-sf-baseline.sql
 * 
 * Exports all San Francisco region data from each skill schema to Parquet
 * in an internal stage, then downloads locally for upload to S3.
 *
 * Run AFTER all skill pipelines have been generated for San Francisco.
 *
 * Usage:
 *   1. Execute this script to export all tables to @EXPORT_STAGE
 *   2. Download from stage: snow stage copy @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/ ./sf-export/ --recursive
 *   3. Upload to S3: aws s3 sync ./sf-export/ s3://fleet-intelligence/SanFrancisco/ --delete
 */

--------------------------------------------------------------------
-- Setup
--------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS FLEET_INTELLIGENCE.CORE;

CREATE STAGE IF NOT EXISTS FLEET_INTELLIGENCE.CORE.EXPORT_STAGE
    DIRECTORY = (ENABLE = TRUE)
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

--------------------------------------------------------------------
-- fleet-intelligence-taxis
--------------------------------------------------------------------
COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/fleet-intelligence-taxis/TAXI_LOCATIONS/
FROM (SELECT * FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS.TAXI_LOCATIONS WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE MAX_FILE_SIZE = 268435456;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/fleet-intelligence-taxis/TAXI_DRIVERS/
FROM (SELECT * FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS.TAXI_DRIVERS WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/fleet-intelligence-taxis/TAXI_LOCATIONS_NUMBERED/
FROM (SELECT * FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS.TAXI_LOCATIONS_NUMBERED WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE MAX_FILE_SIZE = 268435456;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/fleet-intelligence-taxis/DRIVER_TRIPS/
FROM (SELECT * FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS.DRIVER_TRIPS WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/fleet-intelligence-taxis/DRIVER_TRIPS_WITH_COORDS/
FROM (SELECT * FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS.DRIVER_TRIPS_WITH_COORDS WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/fleet-intelligence-taxis/DRIVER_ROUTES/
FROM (SELECT * FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS.DRIVER_ROUTES WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/fleet-intelligence-taxis/DRIVER_ROUTES_PARSED/
FROM (SELECT * FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS.DRIVER_ROUTES_PARSED WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/fleet-intelligence-taxis/DRIVER_ROUTE_GEOMETRIES/
FROM (SELECT * FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS.DRIVER_ROUTE_GEOMETRIES WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/fleet-intelligence-taxis/DRIVER_LOCATIONS/
FROM (SELECT * FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS.DRIVER_LOCATIONS WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE MAX_FILE_SIZE = 268435456;

--------------------------------------------------------------------
-- fleet-intelligence-food-delivery
--------------------------------------------------------------------
COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/fleet-intelligence-food-delivery/RESTAURANTS/
FROM (SELECT * FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.RESTAURANTS WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/fleet-intelligence-food-delivery/CUSTOMER_ADDRESSES/
FROM (SELECT * FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.CUSTOMER_ADDRESSES WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE MAX_FILE_SIZE = 268435456;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/fleet-intelligence-food-delivery/COURIERS/
FROM (SELECT * FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.COURIERS WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/fleet-intelligence-food-delivery/RESTAURANTS_NUMBERED/
FROM (SELECT * FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.RESTAURANTS_NUMBERED WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/fleet-intelligence-food-delivery/ADDRESSES_NUMBERED/
FROM (SELECT * FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.ADDRESSES_NUMBERED WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/fleet-intelligence-food-delivery/DELIVERY_ORDERS/
FROM (SELECT * FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.DELIVERY_ORDERS WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/fleet-intelligence-food-delivery/ORDERS_WITH_LOCATIONS/
FROM (SELECT * FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.ORDERS_WITH_LOCATIONS WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/fleet-intelligence-food-delivery/DELIVERY_ROUTES/
FROM (SELECT * FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.DELIVERY_ROUTES WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/fleet-intelligence-food-delivery/DELIVERY_ROUTES_PARSED/
FROM (SELECT * FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.DELIVERY_ROUTES_PARSED WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/fleet-intelligence-food-delivery/DELIVERY_ROUTE_GEOMETRIES/
FROM (SELECT * FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.DELIVERY_ROUTE_GEOMETRIES WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/fleet-intelligence-food-delivery/COURIER_LOCATIONS/
FROM (SELECT * FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.COURIER_LOCATIONS WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE MAX_FILE_SIZE = 268435456;

--------------------------------------------------------------------
-- retail-catchment
--------------------------------------------------------------------
COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/retail-catchment/RETAIL_POIS/
FROM (SELECT * FROM FLEET_INTELLIGENCE.RETAIL_CATCHMENT.RETAIL_POIS WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE MAX_FILE_SIZE = 268435456;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/retail-catchment/CITIES_BY_STATE/
FROM (SELECT * FROM FLEET_INTELLIGENCE.RETAIL_CATCHMENT.CITIES_BY_STATE WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/retail-catchment/REGIONAL_ADDRESSES/
FROM (SELECT * FROM FLEET_INTELLIGENCE.RETAIL_CATCHMENT.REGIONAL_ADDRESSES WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE MAX_FILE_SIZE = 268435456;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/retail-catchment/REGION_CONFIG/
FROM (SELECT * FROM FLEET_INTELLIGENCE.RETAIL_CATCHMENT.REGION_CONFIG WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE;

--------------------------------------------------------------------
-- route-deviation
--------------------------------------------------------------------
COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/route-deviation/ROUTE_CACHE/
FROM (SELECT * FROM FLEET_INTELLIGENCE.ROUTE_CACHE.ROUTE_CACHE WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE MAX_FILE_SIZE = 268435456;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/route-deviation/TRIP_ACTUAL_METRICS/
FROM (SELECT * FROM FLEET_INTELLIGENCE.ROUTE_DEVIATION.TRIP_ACTUAL_METRICS WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/route-deviation/OD_EXPECTED_ROUTES/
FROM (SELECT * FROM FLEET_INTELLIGENCE.ROUTE_DEVIATION.OD_EXPECTED_ROUTES WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/route-deviation/TRIP_DEVIATION_ANALYSIS/
FROM (SELECT * FROM FLEET_INTELLIGENCE.ROUTE_DEVIATION.TRIP_DEVIATION_ANALYSIS WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/route-deviation/DRIVER_DEVIATION_SUMMARY/
FROM (SELECT * FROM FLEET_INTELLIGENCE.ROUTE_DEVIATION.DRIVER_DEVIATION_SUMMARY WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/route-deviation/DAILY_DEVIATION_TRENDS/
FROM (SELECT * FROM FLEET_INTELLIGENCE.ROUTE_DEVIATION.DAILY_DEVIATION_TRENDS WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE;

--------------------------------------------------------------------
-- route-optimization
--------------------------------------------------------------------
COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/route-optimization/PLACES/
FROM (SELECT * FROM FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.PLACES WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE MAX_FILE_SIZE = 268435456;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/route-optimization/LOOKUP/
FROM (SELECT * FROM FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.LOOKUP WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/route-optimization/JOB_TEMPLATE/
FROM (SELECT * FROM FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.JOB_TEMPLATE WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE;

--------------------------------------------------------------------
-- dwell-analysis (static tables only; DTs cannot be exported)
--------------------------------------------------------------------
COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/dwell-analysis/GEOFENCE_POLYGONS/
FROM (SELECT * FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.GEOFENCE_POLYGONS WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE;

--------------------------------------------------------------------
-- synthetic-datasets (source telemetry for dwell-analysis)
--------------------------------------------------------------------
COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/synthetic-datasets/FACT_TRUCK_TELEMETRY/
FROM (SELECT * FROM SYNTHETIC_DATASETS.FLEET_INTELLIGENCE.FACT_TRUCK_TELEMETRY WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE MAX_FILE_SIZE = 268435456;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/synthetic-datasets/TRUCK_FLEET/
FROM (SELECT * FROM SYNTHETIC_DATASETS.FLEET_INTELLIGENCE.TRUCK_FLEET WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/synthetic-datasets/GERMANY_DESTINATIONS/
FROM (SELECT * FROM SYNTHETIC_DATASETS.FLEET_INTELLIGENCE.GERMANY_DESTINATIONS WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/synthetic-datasets/GERMANY_REST_STOPS/
FROM (SELECT * FROM SYNTHETIC_DATASETS.FLEET_INTELLIGENCE.GERMANY_REST_STOPS WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE;

--------------------------------------------------------------------
-- travel-time-matrix
--------------------------------------------------------------------
COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/travel-time-matrix/SF_HEXAGONS/
FROM (SELECT * FROM FLEET_INTELLIGENCE.TRAVEL_TIME_MATRIX.SF_HEXAGONS WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE;

COPY INTO @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/travel-time-matrix/SF_TRAVEL_TIME_MATRIX/
FROM (SELECT * FROM FLEET_INTELLIGENCE.TRAVEL_TIME_MATRIX.SF_TRAVEL_TIME_MATRIX WHERE REGION = 'SanFrancisco')
FILE_FORMAT = (TYPE = PARQUET) HEADER = TRUE OVERWRITE = TRUE MAX_FILE_SIZE = 268435456;

--------------------------------------------------------------------
-- Verification
--------------------------------------------------------------------
LIST @FLEET_INTELLIGENCE.CORE.EXPORT_STAGE/SanFrancisco/;
