USE ROLE ACCOUNTADMIN;
USE WAREHOUSE ROUTING_ANALYTICS;

CREATE OR REPLACE PROCEDURE OPENROUTESERVICE_SETUP.ROUTING.BUILD_CITY_MATRIX(
    CITY_NAME VARCHAR,
    CENTER_LON FLOAT,
    CENTER_LAT FLOAT,
    RADIUS FLOAT DEFAULT 0.06
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    hex_count INTEGER;
    pair_count INTEGER;
    res RESULTSET;
    batch_size INTEGER DEFAULT 100;
BEGIN
    EXECUTE IMMEDIATE 'CREATE OR REPLACE TABLE OPENROUTESERVICE_SETUP.ROUTING.' || :CITY_NAME || '_HEXAGONS AS SELECT h3_index AS HEX_ID, lon AS LONGITUDE, lat AS LATITUDE, ROW_NUMBER() OVER (ORDER BY h3_index) AS ROW_NUM, ARRAY_CONSTRUCT(lon, lat) AS LOCATION_ARRAY FROM OPENROUTESERVICE_SETUP.PUBLIC.CA_H3_RES9 WHERE ABS(lon - (' || :CENTER_LON || ')) < ' || :RADIUS || ' AND ABS(lat - (' || :CENTER_LAT || ')) < ' || :RADIUS;

    res := (EXECUTE IMMEDIATE 'SELECT COUNT(*) AS cnt FROM OPENROUTESERVICE_SETUP.ROUTING.' || :CITY_NAME || '_HEXAGONS');
    LET c CURSOR FOR res;
    FOR row_var IN c DO
        hex_count := row_var.cnt;
    END FOR;

    EXECUTE IMMEDIATE 'CREATE OR REPLACE TABLE OPENROUTESERVICE_SETUP.ROUTING.' || :CITY_NAME || '_DEST_BATCHES AS WITH numbered AS (SELECT HEX_ID, LONGITUDE, LATITUDE, LOCATION_ARRAY, ROW_NUM, CEIL(ROW_NUM / ' || :batch_size || ') AS BATCH_NUM FROM OPENROUTESERVICE_SETUP.ROUTING.' || :CITY_NAME || '_HEXAGONS) SELECT BATCH_NUM, ARRAY_AGG(LOCATION_ARRAY) WITHIN GROUP (ORDER BY ROW_NUM) AS BATCH_LOCATIONS, ARRAY_AGG(HEX_ID) WITHIN GROUP (ORDER BY ROW_NUM) AS BATCH_HEX_IDS, COUNT(*) AS BATCH_SIZE FROM numbered GROUP BY BATCH_NUM';

    EXECUTE IMMEDIATE 'CREATE OR REPLACE TABLE OPENROUTESERVICE_SETUP.ROUTING.' || :CITY_NAME || '_MATRIX_RESULTS AS SELECT h.HEX_ID AS ORIGIN_HEX_ID, h.ROW_NUM, b.BATCH_NUM, b.BATCH_HEX_IDS, OPENROUTESERVICE_NATIVE_APP.CORE.MATRIX(''driving-car'', ARRAY_CAT(ARRAY_CONSTRUCT(h.LOCATION_ARRAY), b.BATCH_LOCATIONS), ARRAY_CONSTRUCT(''duration'', ''distance'')) AS MATRIX_RESULT FROM OPENROUTESERVICE_SETUP.ROUTING.' || :CITY_NAME || '_HEXAGONS h CROSS JOIN OPENROUTESERVICE_SETUP.ROUTING.' || :CITY_NAME || '_DEST_BATCHES b';

    EXECUTE IMMEDIATE 'CREATE OR REPLACE TABLE OPENROUTESERVICE_SETUP.ROUTING.' || :CITY_NAME || '_TRAVEL_TIME_MATRIX AS SELECT m.ORIGIN_HEX_ID, m.BATCH_HEX_IDS[f.INDEX]::VARCHAR AS DESTINATION_HEX_ID, m.MATRIX_RESULT:durations[0][f.INDEX + 1]::FLOAT AS TRAVEL_TIME_SECONDS, m.MATRIX_RESULT:distances[0][f.INDEX + 1]::FLOAT AS DISTANCE_METERS, CURRENT_TIMESTAMP() AS CREATED_AT FROM OPENROUTESERVICE_SETUP.ROUTING.' || :CITY_NAME || '_MATRIX_RESULTS m, LATERAL FLATTEN(input => m.BATCH_HEX_IDS) f WHERE m.MATRIX_RESULT:durations IS NOT NULL';

    res := (EXECUTE IMMEDIATE 'SELECT COUNT(*) AS cnt FROM OPENROUTESERVICE_SETUP.ROUTING.' || :CITY_NAME || '_TRAVEL_TIME_MATRIX');
    LET c2 CURSOR FOR res;
    FOR row_var IN c2 DO
        pair_count := row_var.cnt;
    END FOR;

    RETURN :CITY_NAME || ' matrix complete: ' || :hex_count || ' hexagons, ' || :pair_count || ' pairs';
END;
$$;
