USE ROLE ACCOUNTADMIN;
USE WAREHOUSE ROUTING_ANALYTICS;

-- ============================================================
-- TRAVEL TIME TABLES
-- ============================================================

CREATE TABLE IF NOT EXISTS OPENROUTESERVICE_SETUP.PUBLIC.CA_TRAVEL_TIME_RES7 (
    ORIGIN_H3 VARCHAR(20),
    DEST_H3 VARCHAR(20),
    TRAVEL_TIME_SECONDS FLOAT,
    TRAVEL_DISTANCE_METERS FLOAT
);

CREATE TABLE IF NOT EXISTS OPENROUTESERVICE_SETUP.PUBLIC.CA_TRAVEL_TIME_RES8 (
    ORIGIN_H3 VARCHAR(20),
    DEST_H3 VARCHAR(20),
    TRAVEL_TIME_SECONDS FLOAT,
    TRAVEL_DISTANCE_METERS FLOAT
);

CREATE TABLE IF NOT EXISTS OPENROUTESERVICE_SETUP.PUBLIC.CA_TRAVEL_TIME_RES9 (
    ORIGIN_H3 VARCHAR(20),
    DEST_H3 VARCHAR(20),
    TRAVEL_TIME_SECONDS FLOAT,
    TRAVEL_DISTANCE_METERS FLOAT
);

-- ============================================================
-- BATCHED PROCEDURES using MATRIX_TABULAR (1×N, sources:["0"])
-- Processes BATCH_SIZE origins per iteration, commits each batch.
-- Skips origins already in the travel time table (resume-safe).
-- ============================================================

CREATE OR REPLACE PROCEDURE OPENROUTESERVICE_SETUP.PUBLIC.BUILD_TRAVEL_TIME_MATRIX_RES7()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    batch_size INTEGER DEFAULT 1000;
    total_inserted INTEGER DEFAULT 0;
    batch_inserted INTEGER DEFAULT 0;
    remaining INTEGER DEFAULT 0;
    batch_num INTEGER DEFAULT 0;
BEGIN
    SELECT COUNT(DISTINCT ORIGIN_H3) INTO remaining
    FROM OPENROUTESERVICE_SETUP.PUBLIC.CA_H3_RES7_PAIRS p
    WHERE NOT EXISTS (
        SELECT 1 FROM OPENROUTESERVICE_SETUP.PUBLIC.CA_TRAVEL_TIME_RES7 t
        WHERE t.ORIGIN_H3 = p.ORIGIN_H3
    );

    WHILE (remaining > 0) DO
        batch_num := batch_num + 1;

        INSERT INTO OPENROUTESERVICE_SETUP.PUBLIC.CA_TRAVEL_TIME_RES7
        WITH pending_origins AS (
            SELECT DISTINCT p.ORIGIN_H3
            FROM OPENROUTESERVICE_SETUP.PUBLIC.CA_H3_RES7_PAIRS p
            WHERE NOT EXISTS (
                SELECT 1 FROM OPENROUTESERVICE_SETUP.PUBLIC.CA_TRAVEL_TIME_RES7 t
                WHERE t.ORIGIN_H3 = p.ORIGIN_H3
            )
            LIMIT :batch_size
        ),
        origin_groups AS (
            SELECT
                p.ORIGIN_H3,
                p.ORIGIN_LON,
                p.ORIGIN_LAT,
                ARRAY_AGG(ARRAY_CONSTRUCT(d.LON, d.LAT)) WITHIN GROUP (ORDER BY p.DEST_H3) AS DEST_COORDS,
                ARRAY_AGG(p.DEST_H3) WITHIN GROUP (ORDER BY p.DEST_H3) AS DEST_HEX_IDS
            FROM OPENROUTESERVICE_SETUP.PUBLIC.CA_H3_RES7_PAIRS p
            JOIN OPENROUTESERVICE_SETUP.PUBLIC.CA_H3_RES7 d
                ON p.DEST_H3 = d.H3_INDEX
            WHERE p.ORIGIN_H3 IN (SELECT ORIGIN_H3 FROM pending_origins)
            GROUP BY p.ORIGIN_H3, p.ORIGIN_LON, p.ORIGIN_LAT
        ),
        matrix_calls AS (
            SELECT
                ORIGIN_H3,
                DEST_HEX_IDS,
                OPENROUTESERVICE_NATIVE_APP.CORE.MATRIX_TABULAR(
                    'driving-car',
                    ARRAY_CONSTRUCT(ORIGIN_LON, ORIGIN_LAT),
                    DEST_COORDS
                ) AS MATRIX_RESULT
            FROM origin_groups
        )
        SELECT
            m.ORIGIN_H3,
            m.DEST_HEX_IDS[f.INDEX]::VARCHAR AS DEST_H3,
            m.MATRIX_RESULT:durations[0][f.INDEX]::FLOAT AS TRAVEL_TIME_SECONDS,
            m.MATRIX_RESULT:distances[0][f.INDEX]::FLOAT AS TRAVEL_DISTANCE_METERS
        FROM matrix_calls m,
        LATERAL FLATTEN(input => m.DEST_HEX_IDS) f
        WHERE m.MATRIX_RESULT:durations IS NOT NULL;

        SELECT COUNT(DISTINCT ORIGIN_H3) INTO remaining
        FROM OPENROUTESERVICE_SETUP.PUBLIC.CA_H3_RES7_PAIRS p
        WHERE NOT EXISTS (
            SELECT 1 FROM OPENROUTESERVICE_SETUP.PUBLIC.CA_TRAVEL_TIME_RES7 t
            WHERE t.ORIGIN_H3 = p.ORIGIN_H3
        );
    END WHILE;

    RETURN 'RES7 travel time matrix complete: ' || (SELECT COUNT(*) FROM OPENROUTESERVICE_SETUP.PUBLIC.CA_TRAVEL_TIME_RES7) || ' rows';
END;
$$;

CREATE OR REPLACE PROCEDURE OPENROUTESERVICE_SETUP.PUBLIC.BUILD_TRAVEL_TIME_MATRIX_RES8()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    batch_size INTEGER DEFAULT 1000;
    remaining INTEGER DEFAULT 0;
    batch_num INTEGER DEFAULT 0;
BEGIN
    SELECT COUNT(DISTINCT ORIGIN_H3) INTO remaining
    FROM OPENROUTESERVICE_SETUP.PUBLIC.CA_H3_RES8_PAIRS p
    WHERE NOT EXISTS (
        SELECT 1 FROM OPENROUTESERVICE_SETUP.PUBLIC.CA_TRAVEL_TIME_RES8 t
        WHERE t.ORIGIN_H3 = p.ORIGIN_H3
    );

    WHILE (remaining > 0) DO
        batch_num := batch_num + 1;

        INSERT INTO OPENROUTESERVICE_SETUP.PUBLIC.CA_TRAVEL_TIME_RES8
        WITH pending_origins AS (
            SELECT DISTINCT p.ORIGIN_H3
            FROM OPENROUTESERVICE_SETUP.PUBLIC.CA_H3_RES8_PAIRS p
            WHERE NOT EXISTS (
                SELECT 1 FROM OPENROUTESERVICE_SETUP.PUBLIC.CA_TRAVEL_TIME_RES8 t
                WHERE t.ORIGIN_H3 = p.ORIGIN_H3
            )
            LIMIT :batch_size
        ),
        origin_groups AS (
            SELECT
                p.ORIGIN_H3,
                p.ORIGIN_LON,
                p.ORIGIN_LAT,
                ARRAY_AGG(ARRAY_CONSTRUCT(d.LON, d.LAT)) WITHIN GROUP (ORDER BY p.DEST_H3) AS DEST_COORDS,
                ARRAY_AGG(p.DEST_H3) WITHIN GROUP (ORDER BY p.DEST_H3) AS DEST_HEX_IDS
            FROM OPENROUTESERVICE_SETUP.PUBLIC.CA_H3_RES8_PAIRS p
            JOIN OPENROUTESERVICE_SETUP.PUBLIC.CA_H3_RES8 d
                ON p.DEST_H3 = d.H3_INDEX
            WHERE p.ORIGIN_H3 IN (SELECT ORIGIN_H3 FROM pending_origins)
            GROUP BY p.ORIGIN_H3, p.ORIGIN_LON, p.ORIGIN_LAT
        ),
        matrix_calls AS (
            SELECT
                ORIGIN_H3,
                DEST_HEX_IDS,
                OPENROUTESERVICE_NATIVE_APP.CORE.MATRIX_TABULAR(
                    'driving-car',
                    ARRAY_CONSTRUCT(ORIGIN_LON, ORIGIN_LAT),
                    DEST_COORDS
                ) AS MATRIX_RESULT
            FROM origin_groups
        )
        SELECT
            m.ORIGIN_H3,
            m.DEST_HEX_IDS[f.INDEX]::VARCHAR AS DEST_H3,
            m.MATRIX_RESULT:durations[0][f.INDEX]::FLOAT AS TRAVEL_TIME_SECONDS,
            m.MATRIX_RESULT:distances[0][f.INDEX]::FLOAT AS TRAVEL_DISTANCE_METERS
        FROM matrix_calls m,
        LATERAL FLATTEN(input => m.DEST_HEX_IDS) f
        WHERE m.MATRIX_RESULT:durations IS NOT NULL;

        SELECT COUNT(DISTINCT ORIGIN_H3) INTO remaining
        FROM OPENROUTESERVICE_SETUP.PUBLIC.CA_H3_RES8_PAIRS p
        WHERE NOT EXISTS (
            SELECT 1 FROM OPENROUTESERVICE_SETUP.PUBLIC.CA_TRAVEL_TIME_RES8 t
            WHERE t.ORIGIN_H3 = p.ORIGIN_H3
        );
    END WHILE;

    RETURN 'RES8 travel time matrix complete: ' || (SELECT COUNT(*) FROM OPENROUTESERVICE_SETUP.PUBLIC.CA_TRAVEL_TIME_RES8) || ' rows';
END;
$$;

CREATE OR REPLACE PROCEDURE OPENROUTESERVICE_SETUP.PUBLIC.BUILD_TRAVEL_TIME_MATRIX_RES9()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    batch_size INTEGER DEFAULT 1000;
    remaining INTEGER DEFAULT 0;
    batch_num INTEGER DEFAULT 0;
BEGIN
    SELECT COUNT(DISTINCT ORIGIN_H3) INTO remaining
    FROM OPENROUTESERVICE_SETUP.PUBLIC.CA_H3_RES9_PAIRS p
    WHERE NOT EXISTS (
        SELECT 1 FROM OPENROUTESERVICE_SETUP.PUBLIC.CA_TRAVEL_TIME_RES9 t
        WHERE t.ORIGIN_H3 = p.ORIGIN_H3
    );

    WHILE (remaining > 0) DO
        batch_num := batch_num + 1;

        INSERT INTO OPENROUTESERVICE_SETUP.PUBLIC.CA_TRAVEL_TIME_RES9
        WITH pending_origins AS (
            SELECT DISTINCT p.ORIGIN_H3
            FROM OPENROUTESERVICE_SETUP.PUBLIC.CA_H3_RES9_PAIRS p
            WHERE NOT EXISTS (
                SELECT 1 FROM OPENROUTESERVICE_SETUP.PUBLIC.CA_TRAVEL_TIME_RES9 t
                WHERE t.ORIGIN_H3 = p.ORIGIN_H3
            )
            LIMIT :batch_size
        ),
        origin_groups AS (
            SELECT
                p.ORIGIN_H3,
                p.ORIGIN_LON,
                p.ORIGIN_LAT,
                ARRAY_AGG(ARRAY_CONSTRUCT(d.LON, d.LAT)) WITHIN GROUP (ORDER BY p.DEST_H3) AS DEST_COORDS,
                ARRAY_AGG(p.DEST_H3) WITHIN GROUP (ORDER BY p.DEST_H3) AS DEST_HEX_IDS
            FROM OPENROUTESERVICE_SETUP.PUBLIC.CA_H3_RES9_PAIRS p
            JOIN OPENROUTESERVICE_SETUP.PUBLIC.CA_H3_RES9 d
                ON p.DEST_H3 = d.H3_INDEX
            WHERE p.ORIGIN_H3 IN (SELECT ORIGIN_H3 FROM pending_origins)
            GROUP BY p.ORIGIN_H3, p.ORIGIN_LON, p.ORIGIN_LAT
        ),
        matrix_calls AS (
            SELECT
                ORIGIN_H3,
                DEST_HEX_IDS,
                OPENROUTESERVICE_NATIVE_APP.CORE.MATRIX_TABULAR(
                    'driving-car',
                    ARRAY_CONSTRUCT(ORIGIN_LON, ORIGIN_LAT),
                    DEST_COORDS
                ) AS MATRIX_RESULT
            FROM origin_groups
        )
        SELECT
            m.ORIGIN_H3,
            m.DEST_HEX_IDS[f.INDEX]::VARCHAR AS DEST_H3,
            m.MATRIX_RESULT:durations[0][f.INDEX]::FLOAT AS TRAVEL_TIME_SECONDS,
            m.MATRIX_RESULT:distances[0][f.INDEX]::FLOAT AS TRAVEL_DISTANCE_METERS
        FROM matrix_calls m,
        LATERAL FLATTEN(input => m.DEST_HEX_IDS) f
        WHERE m.MATRIX_RESULT:durations IS NOT NULL;

        SELECT COUNT(DISTINCT ORIGIN_H3) INTO remaining
        FROM OPENROUTESERVICE_SETUP.PUBLIC.CA_H3_RES9_PAIRS p
        WHERE NOT EXISTS (
            SELECT 1 FROM OPENROUTESERVICE_SETUP.PUBLIC.CA_TRAVEL_TIME_RES9 t
            WHERE t.ORIGIN_H3 = p.ORIGIN_H3
        );
    END WHILE;

    RETURN 'RES9 travel time matrix complete: ' || (SELECT COUNT(*) FROM OPENROUTESERVICE_SETUP.PUBLIC.CA_TRAVEL_TIME_RES9) || ' rows';
END;
$$;

-- ============================================================
-- SUSPEND the root task before modifying DAG
-- ============================================================

ALTER TASK OPENROUTESERVICE_SETUP.PUBLIC.TASK_01_BUILD_HEXAGONS_7_8 SUSPEND;

-- ============================================================
-- ADD travel time tasks to the DAG
-- ============================================================

CREATE OR REPLACE TASK OPENROUTESERVICE_SETUP.PUBLIC.TASK_08_BUILD_TRAVEL_TIME_RES7
    WAREHOUSE = ROUTING_ANALYTICS
    AFTER OPENROUTESERVICE_SETUP.PUBLIC.TASK_02_BUILD_PAIRS_RES7
AS
    CALL OPENROUTESERVICE_SETUP.PUBLIC.BUILD_TRAVEL_TIME_MATRIX_RES7();

CREATE OR REPLACE TASK OPENROUTESERVICE_SETUP.PUBLIC.TASK_09_BUILD_TRAVEL_TIME_RES8
    WAREHOUSE = ROUTING_ANALYTICS
    AFTER OPENROUTESERVICE_SETUP.PUBLIC.TASK_03_BUILD_PAIRS_RES8
AS
    CALL OPENROUTESERVICE_SETUP.PUBLIC.BUILD_TRAVEL_TIME_MATRIX_RES8();

CREATE OR REPLACE TASK OPENROUTESERVICE_SETUP.PUBLIC.TASK_10_BUILD_TRAVEL_TIME_RES9
    WAREHOUSE = ROUTING_ANALYTICS
    AFTER OPENROUTESERVICE_SETUP.PUBLIC.TASK_05_BUILD_PAIRS_RES9
AS
    CALL OPENROUTESERVICE_SETUP.PUBLIC.BUILD_TRAVEL_TIME_MATRIX_RES9();

-- ============================================================
-- RESUME all tasks (children first, root last)
-- ============================================================

ALTER TASK OPENROUTESERVICE_SETUP.PUBLIC.TASK_10_BUILD_TRAVEL_TIME_RES9 RESUME;
ALTER TASK OPENROUTESERVICE_SETUP.PUBLIC.TASK_09_BUILD_TRAVEL_TIME_RES8 RESUME;
ALTER TASK OPENROUTESERVICE_SETUP.PUBLIC.TASK_08_BUILD_TRAVEL_TIME_RES7 RESUME;
ALTER TASK OPENROUTESERVICE_SETUP.PUBLIC.TASK_07_BUILD_PAIRS_RES10 RESUME;
ALTER TASK OPENROUTESERVICE_SETUP.PUBLIC.TASK_06_BUILD_HEXAGONS_RES10 RESUME;
ALTER TASK OPENROUTESERVICE_SETUP.PUBLIC.TASK_05_BUILD_PAIRS_RES9 RESUME;
ALTER TASK OPENROUTESERVICE_SETUP.PUBLIC.TASK_04_BUILD_HEXAGONS_RES9 RESUME;
ALTER TASK OPENROUTESERVICE_SETUP.PUBLIC.TASK_03_BUILD_PAIRS_RES8 RESUME;
ALTER TASK OPENROUTESERVICE_SETUP.PUBLIC.TASK_02_BUILD_PAIRS_RES7 RESUME;
ALTER TASK OPENROUTESERVICE_SETUP.PUBLIC.TASK_01_BUILD_HEXAGONS_7_8 RESUME;
