################################################################################################
### Minimal configuration example file for openrouteservice. For a description please visit: ###
### https://giscience.github.io/openrouteservice/run-instance/configuration/                 ###
################################################################################################
ors:
  engine:
    profile_default:
      build:
        source_file: /home/ors/files/.cortex/skills/build-routing-solution/openrouteservice_app/staged_files/SanFrancisco.osm.pbf
        instructions: false
      service:
        maximum_distance: 1500000
        maximum_distance_dynamic_weights: 1500000
        maximum_distance_avoid_areas: 1500000
        maximum_distance_alternative_routes: 1500000
        maximum_distance_round_trip_routes: 1500000
        maximum_visited_nodes: 100000000
    profiles:   
## Driving profiles
      driving-car: 
        enabled: true
      driving-hgv: 
        enabled: true
## Cycling profiles
      cycling-regular:
        enabled: true
      cycling-road:
        enabled: false
      cycling-mountain:
        enabled: false
      cycling-electric:
        enabled: true
# Foot profiles
      foot-walking:
        enabled: true
      foot-hiking:
        enabled: false
# Wheelchair profiles
      wheelchair:
        enabled: false
  endpoints:
    matrix:
      maximum_visited_nodes: 100000000
      maximum_routes: 250000
    isochrones:
      maximum_locations: 2
      maximum_intervals: 10
      maximum_range_distance: 
        - profiles: driving-car, driving-hgv, cycling-regular, cycling-road, cycling-mountain, cycling-electric, foot-walking, foot-hiking, wheelchair
          value: 1500000
      maximum_range_time:
        - profiles: driving-car, driving-hgv, cycling-regular, cycling-road, cycling-mountain, cycling-electric, foot-walking, foot-hiking, wheelchair
          value: 18000
