#!/usr/bin/env python3
"""
gen_demo_data.py - Deterministic codegen for the Backload Matching demo seed.

Emits load-demo-data.sql containing only literal `INSERT INTO ... VALUES (...)` rows.
No CTEs, no QUALIFY, no correlated subqueries, no JOINs, no RANDOM/UNIFORM. The
SQL is a pure build artifact; if you need to change the data, edit THIS Python
file and re-run, then commit both files.

Run:
  python3 tools/gen_demo_data.py > references/load-demo-data.sql
"""
import random
import sys

random.seed(42)

# Cities inside the Germany ORS bbox (5.86E..15.05E, 47.27N..55.15N)
CITIES = [
    ('Hamburg',    9.9937,  53.5511),
    ('Bremen',     8.8017,  53.0793),
    ('Berlin',    13.4050,  52.5200),
    ('Hannover',   9.7320,  52.3759),
    ('Dortmund',   7.4653,  51.5136),
    ('Cologne',    6.9603,  50.9375),
    ('Frankfurt',  8.6821,  50.1109),
    ('Leipzig',   12.3731,  51.3397),
    ('Dresden',   13.7373,  51.0504),
    ('Stuttgart',  9.1829,  48.7758),
    ('Nuremberg', 11.0767,  49.4521),
    ('Munich',    11.5820,  48.1351),
]

# Nordic home depots
HOMES = [
    ('Copenhagen', 12.5655, 55.6759),
    ('Stockholm',  18.0686, 59.3293),
    ('Oslo',       10.7522, 59.9139),
    ('Helsinki',   24.9384, 60.1699),
]

LOADS = ['Furniture parts', 'Auto components', 'Pharma pallets', 'Frozen food', 'Industrial machinery']
PRODUCTS_INTERNAL = ['DHL Express parcels', 'B2B pallets', 'Automotive parts', 'Pharma cold-chain', 'Retail e-commerce']
PRODUCTS_EXTERNAL = ['Pallets (general)', 'Steel coils', 'Plastic granulate', 'Beverages', 'Furniture', 'Bulk paper']
SOURCES = ['TIMOCOM', 'WTRANSNET', 'TELEROUTE', 'B2P']


def jitter(v, scale=0.04):
    return v + random.uniform(-scale, scale)


def sql_str(s):
    return "'" + s.replace("'", "''") + "'"


def sql_bool(b):
    return 'TRUE' if b else 'FALSE'


HEADER = """-- ============================================================================
-- Backload Matching Engine - Demo Data Loader
-- AUTOGENERATED by tools/gen_demo_data.py - DO NOT EDIT THIS FILE BY HAND.
-- To change the data, edit gen_demo_data.py and re-run it.
-- ============================================================================

ALTER SESSION SET query_tag = '{"origin":"sf_sit-is-fleet","name":"oss-backload-matching","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';

USE WAREHOUSE ROUTING_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS FLEET_INTELLIGENCE.BACKLOAD_MATCHING
  COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-backload-matching","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';

USE SCHEMA FLEET_INTELLIGENCE.BACKLOAD_MATCHING;
"""


# -----------------------------------------------------------------------------
# TRAILERS
# -----------------------------------------------------------------------------
def emit_trailers():
    out = ["""
CREATE OR REPLACE TABLE TRAILERS (
    TRAILER_ID        VARCHAR PRIMARY KEY,
    OPERATING_COUNTRY VARCHAR,
    HOME_DEPOT        VARCHAR,
    HOME_LON          FLOAT,
    HOME_LAT          FLOAT,
    CURRENT_LOAD      VARCHAR,
    DROPOFF_CITY      VARCHAR,
    DROPOFF_LON       FLOAT,
    DROPOFF_LAT       FLOAT,
    ETA_OFFSET_MIN    NUMBER,
    STATUS            VARCHAR,
    HAZMAT_CERT       BOOLEAN,
    MAX_PAYLOAD_KG    NUMBER
)
COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-backload-matching","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';

INSERT INTO TRAILERS VALUES"""]
    rows = []
    for i in range(80):
        c = random.choice(CITIES)
        h = random.choice(HOMES)
        eta_min = random.randint(0, 360)
        load = random.choice(LOADS)
        haz = random.random() < 0.4
        cap = random.choice([18000, 20000, 22000, 24000, 26000])
        status = 'IN_TRANSIT' if eta_min < 240 else 'STAGED'
        row = "  ({tid}, 'DE', {h0}, {h1:.4f}, {h2:.4f}, {l}, {c0}, {c1:.4f}, {c2:.4f}, {eta}, {st}, {hz}, {cap})".format(
            tid=sql_str(f'TR-{i+1:04d}'),
            h0=sql_str(h[0]), h1=h[1], h2=h[2],
            l=sql_str(load),
            c0=sql_str(c[0]), c1=jitter(c[1]), c2=jitter(c[2]),
            eta=eta_min, st=sql_str(status), hz=sql_bool(haz), cap=cap,
        )
        rows.append(row)
    out.append(",\n".join(rows) + ";")
    return "\n".join(out)


# -----------------------------------------------------------------------------
# INTERNAL_VOLUMES
# -----------------------------------------------------------------------------
def emit_internal_volumes():
    out = ["""

CREATE OR REPLACE TABLE INTERNAL_VOLUMES (
    ID                VARCHAR PRIMARY KEY,
    PICKUP_CITY       VARCHAR,
    PICKUP_LON        FLOAT,
    PICKUP_LAT        FLOAT,
    DROPOFF_CITY      VARCHAR,
    DROPOFF_LON       FLOAT,
    DROPOFF_LAT       FLOAT,
    PICKUP_FROM_OFFSET_MIN NUMBER,
    PICKUP_TO_OFFSET_MIN   NUMBER,
    WEIGHT_KG         NUMBER,
    PRODUCT           VARCHAR,
    HAZMAT            BOOLEAN
)
COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-backload-matching","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';

INSERT INTO INTERNAL_VOLUMES VALUES"""]
    rows = []
    n = 0
    while n < 120:
        p = random.choice(CITIES)
        d = random.choice(CITIES)
        if p[0] == d[0]:
            continue
        win_start = random.randint(60, 720)
        win_len = random.randint(60, 480)
        wt = random.randint(800, 25000)
        prod = random.choice(PRODUCTS_INTERNAL)
        n += 1
        row = "  ({i}, {p0}, {p1:.4f}, {p2:.4f}, {d0}, {d1:.4f}, {d2:.4f}, {ws}, {we}, {w}, {pr}, FALSE)".format(
            i=sql_str(f'INT-{n:05d}'),
            p0=sql_str(p[0]), p1=jitter(p[1], 0.03), p2=jitter(p[2], 0.03),
            d0=sql_str(d[0]), d1=jitter(d[1], 0.03), d2=jitter(d[2], 0.03),
            ws=win_start, we=win_start + win_len, w=wt, pr=sql_str(prod),
        )
        rows.append(row)
    out.append(",\n".join(rows) + ";")
    return "\n".join(out)


# -----------------------------------------------------------------------------
# EXTERNAL_OFFERS
# -----------------------------------------------------------------------------
def emit_external_offers():
    out = ["""

CREATE OR REPLACE TABLE EXTERNAL_OFFERS (
    OFFER_ID          VARCHAR PRIMARY KEY,
    SOURCE            VARCHAR,
    PICKUP_COUNTRY    VARCHAR,
    DROPOFF_COUNTRY   VARCHAR,
    PICKUP_CITY       VARCHAR,
    PICKUP_LON        FLOAT,
    PICKUP_LAT        FLOAT,
    DROPOFF_CITY      VARCHAR,
    DROPOFF_LON       FLOAT,
    DROPOFF_LAT       FLOAT,
    PICKUP_FROM_OFFSET_MIN NUMBER,
    PICKUP_TO_OFFSET_MIN   NUMBER,
    WEIGHT_KG         NUMBER,
    PRODUCT           VARCHAR,
    PRICE_EUR         NUMBER,
    HAZMAT            BOOLEAN,
    LISTING_TEXT      VARCHAR
)
COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-backload-matching","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';

INSERT INTO EXTERNAL_OFFERS VALUES"""]
    rows = []
    n = 0
    while n < 300:
        p = random.choice(CITIES)
        d = random.choice(CITIES)
        if p[0] == d[0]:
            continue
        n += 1
        src = SOURCES[(n - 1) % 4]
        prod = random.choice(PRODUCTS_EXTERNAL)
        wt = random.randint(800, 25000)
        price = random.randint(400, 4500)
        haz = random.random() < 0.08
        win_start = random.randint(60, 1200)
        win_len = random.randint(60, 480)
        listing = f"{src} {p[0]} -> {d[0]} {wt} kg {prod} EUR {price}{' ADR' if haz else ''}"
        row = "  ({oid}, {src}, 'DE', 'DE', {p0}, {p1:.4f}, {p2:.4f}, {d0}, {d1:.4f}, {d2:.4f}, {ws}, {we}, {w}, {pr}, {pc}, {hz}, {lt})".format(
            oid=sql_str(f'OFF-{n:06d}'), src=sql_str(src),
            p0=sql_str(p[0]), p1=jitter(p[1], 0.04), p2=jitter(p[2], 0.04),
            d0=sql_str(d[0]), d1=jitter(d[1], 0.04), d2=jitter(d[2], 0.04),
            ws=win_start, we=win_start + win_len, w=wt, pr=sql_str(prod),
            pc=price, hz=sql_bool(haz), lt=sql_str(listing),
        )
        rows.append(row)
    out.append(",\n".join(rows) + ";")
    return "\n".join(out)


VIEWS_AND_DECISIONS = """

CREATE OR REPLACE VIEW VW_TRAILERS AS
SELECT
    TRAILER_ID, OPERATING_COUNTRY, HOME_DEPOT,
    HOME_LON, HOME_LAT,
    CURRENT_LOAD, DROPOFF_CITY,
    DROPOFF_LON, DROPOFF_LAT,
    DATEADD(MINUTE, ETA_OFFSET_MIN, CURRENT_TIMESTAMP())  AS ETA_TS,
    ETA_OFFSET_MIN AS ETA_MIN,
    STATUS, HAZMAT_CERT, MAX_PAYLOAD_KG
FROM TRAILERS
WHERE STATUS IN ('IN_TRANSIT', 'STAGED');

CREATE OR REPLACE VIEW VW_INTERNAL_VOLUMES AS
SELECT
    ID, PICKUP_CITY, PICKUP_LON, PICKUP_LAT,
    DROPOFF_CITY, DROPOFF_LON, DROPOFF_LAT,
    DATEADD(MINUTE, PICKUP_FROM_OFFSET_MIN, CURRENT_TIMESTAMP()) AS PICKUP_FROM_TS,
    DATEADD(MINUTE, PICKUP_TO_OFFSET_MIN,   CURRENT_TIMESTAMP()) AS PICKUP_TO_TS,
    WEIGHT_KG, PRODUCT, HAZMAT
FROM INTERNAL_VOLUMES;

CREATE OR REPLACE VIEW VW_EXTERNAL_OFFERS AS
SELECT
    OFFER_ID, SOURCE, PICKUP_COUNTRY, DROPOFF_COUNTRY,
    PICKUP_CITY, PICKUP_LON, PICKUP_LAT,
    DROPOFF_CITY, DROPOFF_LON, DROPOFF_LAT,
    DATEADD(MINUTE, PICKUP_FROM_OFFSET_MIN, CURRENT_TIMESTAMP()) AS PICKUP_FROM_TS,
    DATEADD(MINUTE, PICKUP_TO_OFFSET_MIN,   CURRENT_TIMESTAMP()) AS PICKUP_TO_TS,
    WEIGHT_KG, PRODUCT, PRICE_EUR, HAZMAT, LISTING_TEXT
FROM EXTERNAL_OFFERS;

CREATE TABLE IF NOT EXISTS PROPOSAL_DECISIONS (
    DECISION_ID  VARCHAR DEFAULT UUID_STRING() PRIMARY KEY,
    TRAILER_ID   VARCHAR,
    OFFER_ID     VARCHAR,
    SOURCE       VARCHAR,
    SCORE        FLOAT,
    EMPTY_KM     FLOAT,
    DECIDED_BY   VARCHAR,
    DECIDED_AT   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RATIONALE    VARCHAR
)
COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-backload-matching","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';

SELECT 'TRAILERS' AS object, COUNT(*) AS n FROM TRAILERS
UNION ALL SELECT 'INTERNAL_VOLUMES', COUNT(*) FROM INTERNAL_VOLUMES
UNION ALL SELECT 'EXTERNAL_OFFERS',  COUNT(*) FROM EXTERNAL_OFFERS
ORDER BY 1;
"""


def main():
    sys.stdout.write(HEADER)
    sys.stdout.write(emit_trailers())
    sys.stdout.write(emit_internal_volumes())
    sys.stdout.write(emit_external_offers())
    sys.stdout.write(VIEWS_AND_DECISIONS)


if __name__ == '__main__':
    main()
