-- ============================================================================
-- FULL TEARDOWN SCRIPT — Drops all objects EXCEPT Docker images
-- ============================================================================
-- Usage: Execute via Cortex Code or snowflake_sql_execute (statement by statement)
--
-- WARNING: This script is DESTRUCTIVE. It drops ALL databases, schemas, tables,
-- warehouses, compute pools, integrations, and other objects created by this project.
--
-- PRESERVED: OPENROUTESERVICE_APP.CORE.IMAGE_REPOSITORY (Docker images intact)
--
-- The drop order follows reverse-dependency: most-dependent objects first.
-- ============================================================================

ALTER SESSION SET query_tag = '{"origin":"sf_sit-is-fleet","name":"oss-routing-solution-cleanup","version":{"major":2,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';

-- ============================================================================
-- PHASE 1: Suspend and drop all SPCS services
-- ============================================================================
ALTER SERVICE IF EXISTS OPENROUTESERVICE_APP.CORE.ORS_CONTROL_APP SUSPEND;
ALTER SERVICE IF EXISTS OPENROUTESERVICE_APP.CORE.ORS_SERVICE SUSPEND;
ALTER SERVICE IF EXISTS OPENROUTESERVICE_APP.CORE.ROUTING_GATEWAY_SERVICE SUSPEND;
ALTER SERVICE IF EXISTS OPENROUTESERVICE_APP.CORE.VROOM_SERVICE SUSPEND;
ALTER SERVICE IF EXISTS OPENROUTESERVICE_APP.CORE.DOWNLOADER SUSPEND;

DROP SERVICE IF EXISTS OPENROUTESERVICE_APP.CORE.ORS_CONTROL_APP;
DROP SERVICE IF EXISTS OPENROUTESERVICE_APP.CORE.ORS_SERVICE;
DROP SERVICE IF EXISTS OPENROUTESERVICE_APP.CORE.ROUTING_GATEWAY_SERVICE;
DROP SERVICE IF EXISTS OPENROUTESERVICE_APP.CORE.VROOM_SERVICE;
DROP SERVICE IF EXISTS OPENROUTESERVICE_APP.CORE.DOWNLOADER;

-- ============================================================================
-- PHASE 2: Stop and drop compute pools
-- ============================================================================
ALTER COMPUTE POOL IF EXISTS OPENROUTESERVICE_APP_COMPUTE_POOL STOP ALL;
ALTER COMPUTE POOL IF EXISTS ORS_CONTROL_APP_COMPUTE_POOL STOP ALL;
DROP COMPUTE POOL IF EXISTS OPENROUTESERVICE_APP_COMPUTE_POOL;
DROP COMPUTE POOL IF EXISTS ORS_CONTROL_APP_COMPUTE_POOL;

-- ============================================================================
-- PHASE 3: Drop external access integrations
-- ============================================================================
DROP INTEGRATION IF EXISTS ORS_OSM_EAI;
DROP INTEGRATION IF EXISTS ORS_CARTO_EAI;

-- ============================================================================
-- PHASE 4: Drop project databases (CASCADE handles all contained objects)
-- ============================================================================
DROP DATABASE IF EXISTS FLEET_INTELLIGENCE CASCADE;
DROP DATABASE IF EXISTS SYNTHETIC_DATASETS CASCADE;

-- ============================================================================
-- PHASE 5: Drop warehouse
-- ============================================================================
DROP WAREHOUSE IF EXISTS ROUTING_ANALYTICS;

-- ============================================================================
-- PHASE 6: Drop Marketplace databases
-- ============================================================================
DROP DATABASE IF EXISTS OVERTURE_MAPS__PLACES;
DROP DATABASE IF EXISTS OVERTURE_MAPS__ADDRESSES;
DROP DATABASE IF EXISTS OVERTURE_MAPS__BUILDINGS;

-- ============================================================================
-- PHASE 7: Clean OPENROUTESERVICE_APP database (preserve image repository)
-- ============================================================================
-- Drop all tables
DROP TABLE IF EXISTS OPENROUTESERVICE_APP.CORE.REGION_CATALOG;
DROP TABLE IF EXISTS OPENROUTESERVICE_APP.CORE.REGION_ORS_MAP;
DROP TABLE IF EXISTS OPENROUTESERVICE_APP.CORE.REGION_PROVISION_JOBS;
DROP TABLE IF EXISTS OPENROUTESERVICE_APP.CORE.MAP_CONFIG;
DROP TABLE IF EXISTS OPENROUTESERVICE_APP.CORE.INTRO_TRIPS;

-- Drop stages
DROP STAGE IF EXISTS OPENROUTESERVICE_APP.CORE.ORS_SPCS_STAGE;
DROP STAGE IF EXISTS OPENROUTESERVICE_APP.CORE.ORS_GRAPHS_SPCS_STAGE;
DROP STAGE IF EXISTS OPENROUTESERVICE_APP.CORE.ORS_ELEVATION_CACHE_SPCS_STAGE;
DROP STAGE IF EXISTS OPENROUTESERVICE_APP.CORE.SEED_DATA_STAGE;

-- Drop network rules
DROP NETWORK RULE IF EXISTS OPENROUTESERVICE_APP.CORE.ORS_OSM_NETWORK_RULE;
DROP NETWORK RULE IF EXISTS OPENROUTESERVICE_APP.CORE.ORS_CARTO_NETWORK_RULE;

-- Drop file formats
DROP FILE FORMAT IF EXISTS OPENROUTESERVICE_APP.CORE.JSON_FORMAT;
DROP FILE FORMAT IF EXISTS OPENROUTESERVICE_APP.CORE.PARQUET_FF;

-- Drop user-defined table functions (routing functions)
DROP FUNCTION IF EXISTS OPENROUTESERVICE_APP.CORE.CHECK_HEALTH();
DROP FUNCTION IF EXISTS OPENROUTESERVICE_APP.CORE.DIRECTIONS(VARCHAR, ARRAY, ARRAY, VARCHAR);
DROP FUNCTION IF EXISTS OPENROUTESERVICE_APP.CORE.DIRECTIONS(VARCHAR, VARIANT, VARCHAR);
DROP FUNCTION IF EXISTS OPENROUTESERVICE_APP.CORE.ISOCHRONES(VARCHAR, FLOAT, FLOAT, NUMBER, VARCHAR);
DROP FUNCTION IF EXISTS OPENROUTESERVICE_APP.CORE.MATRIX(VARCHAR, ARRAY, VARCHAR);
DROP FUNCTION IF EXISTS OPENROUTESERVICE_APP.CORE.MATRIX(VARCHAR, VARIANT, VARCHAR);
DROP FUNCTION IF EXISTS OPENROUTESERVICE_APP.CORE.MATRIX_TABULAR(VARCHAR, ARRAY, ARRAY, VARCHAR);
DROP FUNCTION IF EXISTS OPENROUTESERVICE_APP.CORE.MATRIX_TABULAR_W(VARCHAR, VARCHAR, ARRAY, ARRAY);
DROP FUNCTION IF EXISTS OPENROUTESERVICE_APP.CORE.OPTIMIZATION(VARIANT, VARCHAR);
DROP FUNCTION IF EXISTS OPENROUTESERVICE_APP.CORE.OPTIMIZATION(ARRAY, ARRAY, ARRAY, VARCHAR);
DROP FUNCTION IF EXISTS OPENROUTESERVICE_APP.CORE.BUILD_ORS_SERVICE_SPEC(VARCHAR, VARCHAR, VARCHAR);
DROP FUNCTION IF EXISTS OPENROUTESERVICE_APP.CORE.DOWNLOAD(VARCHAR, VARCHAR, VARCHAR);
DROP FUNCTION IF EXISTS OPENROUTESERVICE_APP.CORE.ORS_STATUS(VARCHAR);

-- Drop internal service functions (_RAW variants)
DROP FUNCTION IF EXISTS OPENROUTESERVICE_APP.CORE._DIRECTIONS_RAW(VARCHAR, VARIANT, VARCHAR);
DROP FUNCTION IF EXISTS OPENROUTESERVICE_APP.CORE._DIRECTIONS_TABULAR_RAW(VARCHAR, ARRAY, ARRAY, VARCHAR);
DROP FUNCTION IF EXISTS OPENROUTESERVICE_APP.CORE._ISOCHRONES_RAW(VARCHAR, ARRAY, ARRAY, VARCHAR);
DROP FUNCTION IF EXISTS OPENROUTESERVICE_APP.CORE._ISOCHRONES_RAW(VARCHAR, FLOAT, FLOAT, NUMBER, VARCHAR);
DROP FUNCTION IF EXISTS OPENROUTESERVICE_APP.CORE._MATRIX_RAW(VARCHAR, ARRAY, ARRAY, ARRAY, VARCHAR);
DROP FUNCTION IF EXISTS OPENROUTESERVICE_APP.CORE._MATRIX_RAW(VARCHAR, VARIANT, VARCHAR);
DROP FUNCTION IF EXISTS OPENROUTESERVICE_APP.CORE._MATRIX_TABULAR_RAW(VARCHAR, ARRAY, ARRAY, VARCHAR);
DROP FUNCTION IF EXISTS OPENROUTESERVICE_APP.CORE._OPTIMIZATION_RAW(VARIANT, VARCHAR);
DROP FUNCTION IF EXISTS OPENROUTESERVICE_APP.CORE._OPTIMIZATION_TABULAR_RAW(ARRAY, ARRAY, ARRAY, VARCHAR);
DROP FUNCTION IF EXISTS OPENROUTESERVICE_APP.CORE._OPTIMIZE_RAW(VARCHAR);
DROP FUNCTION IF EXISTS OPENROUTESERVICE_APP.CORE._ORS_STATUS_RAW(VARCHAR);

-- Drop all procedures
DROP PROCEDURE IF EXISTS OPENROUTESERVICE_APP.CORE.CREATE_REGION_ORS_SERVICE(VARCHAR, VARCHAR);
DROP PROCEDURE IF EXISTS OPENROUTESERVICE_APP.CORE.GET_PROVISION_STATUS();
DROP PROCEDURE IF EXISTS OPENROUTESERVICE_APP.CORE.GET_STATUS();
DROP PROCEDURE IF EXISTS OPENROUTESERVICE_APP.CORE.LIST_REGIONS();
DROP PROCEDURE IF EXISTS OPENROUTESERVICE_APP.CORE.LOAD_SEED_CATALOG(VARCHAR);
DROP PROCEDURE IF EXISTS OPENROUTESERVICE_APP.CORE.PROVISION_REGION_WRAPPER(VARCHAR, VARCHAR, VARCHAR, VARCHAR, FLOAT, FLOAT, FLOAT, FLOAT, VARCHAR, VARCHAR);
DROP PROCEDURE IF EXISTS OPENROUTESERVICE_APP.CORE.RECONCILE_AUTO_SUSPEND();
DROP PROCEDURE IF EXISTS OPENROUTESERVICE_APP.CORE.REFRESH_REGION_CATALOG();
DROP PROCEDURE IF EXISTS OPENROUTESERVICE_APP.CORE.RESUME_ALL_SERVICES();
DROP PROCEDURE IF EXISTS OPENROUTESERVICE_APP.CORE.RESUME_SERVICES();
DROP PROCEDURE IF EXISTS OPENROUTESERVICE_APP.CORE.SCALE_SERVICES(NUMBER, NUMBER);
DROP PROCEDURE IF EXISTS OPENROUTESERVICE_APP.CORE.SET_REBUILD_GRAPHS_FLAG(VARCHAR, VARCHAR);
DROP PROCEDURE IF EXISTS OPENROUTESERVICE_APP.CORE.SUSPEND_ALL_SERVICES();
DROP PROCEDURE IF EXISTS OPENROUTESERVICE_APP.CORE.WRITE_ORS_CONFIG(VARCHAR, VARCHAR, VARCHAR, VARCHAR);

-- Drop extra schemas (TRAVEL_MATRIX, etc.)
DROP SCHEMA IF EXISTS OPENROUTESERVICE_APP.TRAVEL_MATRIX CASCADE;

-- ============================================================================
-- VERIFICATION: After running, only these should remain:
--   OPENROUTESERVICE_APP.CORE.IMAGE_REPOSITORY (5 Docker images)
--   System databases (SNOWFLAKE, USER$*, CORTEX_CODE_IDE*, DEFAULT_DATABASE, POLICY_DB)
--   System compute pools (SYSTEM_COMPUTE_POOL_CPU, SYSTEM_COMPUTE_POOL_GPU)
--   System integrations (SNOWFLAKE$LOCAL_APPLICATION, CORTEX_CODE_IDE_EAI, GITHUB_GIT_INTEGRATION)
-- ============================================================================
