-- =============================================================================
-- CONFIGURE DEMO DEFAULTS
-- Sets all CONFIG tables to match the deployed data (ebike + SanFrancisco)
-- and creates the DELIVERIES view for Fleet Delivery dashboard
-- =============================================================================

USE WAREHOUSE ROUTING_ANALYTICS;
USE DATABASE FLEET_INTELLIGENCE;

-- Fix all CONFIG tables to point to the correct deployed data
UPDATE FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.CONFIG SET VEHICLE_TYPE = 'ebike', REGION = 'SanFrancisco';
UPDATE FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS.CONFIG SET VEHICLE_TYPE = 'ebike', REGION = 'SanFrancisco';
UPDATE FLEET_INTELLIGENCE.DWELL_ANALYSIS.CONFIG SET VEHICLE_TYPE = 'ebike', REGION = 'SanFrancisco';
UPDATE FLEET_INTELLIGENCE.ROUTE_DEVIATION.CONFIG SET VEHICLE_TYPE = 'ebike', REGION = 'SanFrancisco';
UPDATE FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.CONFIG SET VEHICLE_TYPE = 'ebike', REGION = 'SanFrancisco';
UPDATE FLEET_INTELLIGENCE.RETAIL_CATCHMENT.CONFIG SET VEHICLE_TYPE = 'ebike', REGION = 'SanFrancisco';

-- Create DELIVERIES view for Fleet Delivery dashboard
-- Maps FACT_TRIPS columns to the schema expected by the React components
CREATE OR REPLACE VIEW FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.DELIVERIES AS
SELECT
    t.TRIP_ID AS DELIVERY_ID,
    t.VEHICLE_ID AS COURIER_ID,
    p.NAME AS RESTAURANT_NAME,
    t.ORIGIN_POI_ID AS RESTAURANT_ID,
    t.TRIP_START AS ORDER_TIME,
    t.STATUS AS ORDER_STATUS,
    t.ORIGIN AS PICKUP_LOCATION,
    t.DESTINATION AS DROPOFF_LOCATION,
    t.DESTINATION AS CUSTOMER_LOCATION,
    t.ROUTE_GEOG AS GEOMETRY,
    t.DURATION_MINUTES AS DELIVERY_TIME_MIN,
    t.DISTANCE_KM AS DISTANCE_KM
FROM SYNTHETIC_DATASETS.UNIFIED.FACT_TRIPS t
LEFT JOIN SYNTHETIC_DATASETS.UNIFIED.DIM_POIS p ON t.ORIGIN_POI_ID = p.LOCATION_ID
WHERE t.VEHICLE_TYPE = (SELECT VEHICLE_TYPE FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.CONFIG LIMIT 1)
  AND t.REGION = (SELECT REGION FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.CONFIG LIMIT 1);

SELECT 'Demo defaults configured successfully' AS STATUS;
