-- =============================================================================
-- 07_deploy_demo_views.sql
-- Deploys ALL demo views, dynamic tables, and React-compatible projections.
--
-- EXECUTION ORDER (full deployment sequence):
--   modules/00_marketplace_datasets.sql  → Overture Maps listings
--   modules/01_core_infra.sql            → DB, compute pools, services
--   modules/02_routing_functions.sql     → ORS SQL functions
--   modules/03_region_management.sql     → Multi-region provisioner
--   modules/04_service_lifecycle.sql     → Service lifecycle procedures
--   modules/05_matrix_pipeline.sql       → Matrix builder
--   modules/06_matrix_ops.sql            → Matrix operations
--   datasets/load-seed-data.sql          → CREATE TABLES + COPY INTO (parquet)
--   >>> modules/07_deploy_demo_views.sql <<< (THIS FILE)
--
-- The datasets/load-seed-data.sql file is CRITICAL — it defines the canonical
-- table schemas that these views depend on:
--   SYNTHETIC_DATASETS.UNIFIED.FACT_TRIPS:
--     TRIP_ID, VEHICLE_ID, DRIVER_ID, TRIP_START, TRIP_END, DURATION_MINUTES,
--     DISTANCE_KM, ORIGIN_LAT, ORIGIN_LON, ORIGIN (GEOGRAPHY), DESTINATION_LAT,
--     DESTINATION_LON, DESTINATION (GEOGRAPHY), ROUTE_GEOG, ORIGIN_POI_ID, STATUS...
--   SYNTHETIC_DATASETS.UNIFIED.FACT_VEHICLE_TELEMETRY:
--     TELEMETRY_ID, TS, LATITUDE, LONGITUDE, POINT_GEOM, SPEED_KMH, STATUS,
--     LOCATION_ID, LOCATION_TYPE, BATTERY_PCT, POINT_INDEX...
--   SYNTHETIC_DATASETS.UNIFIED.DIM_POIS:
--     LOCATION_ID, NAME, LOCATION_TYPE, CATEGORY, LAT, LNG, POINT_GEOM...
--   SYNTHETIC_DATASETS.UNIFIED.DIM_FLEET:
--     VEHICLE_ID, VEHICLE_TYPE, REGION, SHIFT_TYPE, DRIVER_PROFILE, ORS_PROFILE...
--
-- DO NOT create tables or views manually — always run the scripts in order.
-- DO NOT rename columns — the React app uses hardcoded SQL with these exact names.
--
-- Deploys:
--   1. Fleet Intelligence Taxis (TRIP_SUMMARY, DRIVER_LOCATIONS_V, etc.)
--   2. Fleet Intelligence Food Delivery (DELIVERIES, RESTAURANTS_ENRICHED)
--   3. Route Deviation (DETOUR_TRIPS, VW_VEHICLE_TELEMETRY)
--   4. Dwell Analysis (8 Dynamic Tables + force refresh)
-- =============================================================================

ALTER SESSION SET query_tag = '{"origin":"sf_sit-is-fleet","name":"oss-build-routing-solution","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';

-- ============================================================
-- 1. FLEET INTELLIGENCE TAXIS
-- Source: .cortex/skills/fleet-intelligence-taxis/references/seed-data.sql
-- ============================================================

CREATE SCHEMA IF NOT EXISTS FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-fleet-intelligence-taxis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';

CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS.CONFIG (
    VEHICLE_TYPE VARCHAR NOT NULL,
    REGION       VARCHAR NOT NULL
)
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-fleet-intelligence-taxis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';
MERGE INTO FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS.CONFIG tgt
USING (SELECT 'ebike' AS VEHICLE_TYPE, 'SanFrancisco' AS REGION) src
ON TRUE
WHEN NOT MATCHED THEN INSERT (VEHICLE_TYPE, REGION) VALUES (src.VEHICLE_TYPE, src.REGION);

CREATE OR REPLACE VIEW FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS.VW_DRIVER_LOCATIONS
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-fleet-intelligence-taxis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT
    t.VEHICLE_ID AS DRIVER_ID,
    t.TRIP_ID,
    t.TS AS CURR_TIME,
    t.TS AS POINT_TIME,
    t.LONGITUDE AS LON,
    t.LATITUDE AS LAT,
    t.SPEED_KMH AS KMH,
    CASE t.STATUS
        WHEN 'MOVING' THEN 'driving'
        WHEN 'DWELL_ORIGIN' THEN 'pickup'
        WHEN 'DWELL_DESTINATION' THEN 'dropoff'
        WHEN 'IDLE' THEN 'idle'
        ELSE LOWER(t.STATUS)
    END AS DRIVER_STATE,
    t.POINT_INDEX,
    t.REGION,
    t.ODOMETER_KM
FROM SYNTHETIC_DATASETS.UNIFIED.FACT_VEHICLE_TELEMETRY t
WHERE t.VEHICLE_TYPE = (SELECT VEHICLE_TYPE FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS.CONFIG LIMIT 1)
  AND t.REGION = (SELECT REGION FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS.CONFIG LIMIT 1)
QUALIFY ROW_NUMBER() OVER (PARTITION BY t.TELEMETRY_ID ORDER BY t.TS) = 1;

CREATE OR REPLACE VIEW FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS.VW_TRIP_SUMMARY
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-fleet-intelligence-taxis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
WITH cfg AS (SELECT VEHICLE_TYPE, REGION FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS.CONFIG LIMIT 1),
trip_speeds AS (
    SELECT TRIP_ID, MAX(SPEED_KMH) AS MAX_KMH
    FROM SYNTHETIC_DATASETS.UNIFIED.FACT_VEHICLE_TELEMETRY
    WHERE VEHICLE_TYPE = (SELECT VEHICLE_TYPE FROM cfg)
    GROUP BY TRIP_ID
),
dedup_pois AS (
    SELECT LOCATION_ID, NAME, CATEGORY, LAT, LNG,
           ROW_NUMBER() OVER (PARTITION BY LOCATION_ID ORDER BY NAME) AS RN
    FROM SYNTHETIC_DATASETS.UNIFIED.DIM_POIS
),
dedup_fleet AS (
    SELECT VEHICLE_ID, SHIFT_TYPE,
           ROW_NUMBER() OVER (PARTITION BY VEHICLE_ID ORDER BY SHIFT_TYPE) AS RN
    FROM SYNTHETIC_DATASETS.UNIFIED.DIM_FLEET
    WHERE VEHICLE_TYPE = (SELECT VEHICLE_TYPE FROM cfg)
)
SELECT
    t.VEHICLE_ID AS DRIVER_ID,
    t.TRIP_ID,
    t.TRIP_START AS TRIP_START_TIME,
    t.TRIP_END AS TRIP_END_TIME,
    COALESCE(po.NAME, 'Unknown') AS ORIGIN_ADDRESS,
    COALESCE(pd.NAME, 'Unknown') AS DESTINATION_ADDRESS,
    t.DURATION_MINUTES * 60 AS ROUTE_DURATION_SECS,
    t.DISTANCE_KM * 1000 AS ROUTE_DISTANCE_METERS,
    t.ROUTE_GEOG AS GEOMETRY,
    t.ORIGIN,
    t.DESTINATION,
    CASE f.SHIFT_TYPE
        WHEN '6-14' THEN 'Morning'
        WHEN '14-22' THEN 'Afternoon'
        WHEN '22-6' THEN 'Night'
        ELSE f.SHIFT_TYPE
    END AS SHIFT_TYPE,
    t.REGION,
    CASE WHEN t.DURATION_MINUTES > 0
         THEN t.DISTANCE_KM / (t.DURATION_MINUTES / 60)
         ELSE 0 END AS AVERAGE_KMH,
    ts.MAX_KMH
FROM SYNTHETIC_DATASETS.UNIFIED.FACT_TRIPS t
LEFT JOIN dedup_pois po ON t.ORIGIN_POI_ID = po.LOCATION_ID AND po.RN = 1
LEFT JOIN dedup_pois pd ON t.DESTINATION_POI_ID = pd.LOCATION_ID AND pd.RN = 1
LEFT JOIN dedup_fleet f ON t.VEHICLE_ID = f.VEHICLE_ID AND f.RN = 1
LEFT JOIN trip_speeds ts ON t.TRIP_ID = ts.TRIP_ID
WHERE t.VEHICLE_TYPE = (SELECT VEHICLE_TYPE FROM cfg)
  AND t.REGION = (SELECT REGION FROM cfg);

-- React wrapper views
CREATE OR REPLACE VIEW FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS.TRIP_SUMMARY
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-fleet-intelligence-taxis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS SELECT * FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS.VW_TRIP_SUMMARY;

CREATE OR REPLACE VIEW FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS.DRIVER_LOCATIONS_V
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-fleet-intelligence-taxis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT
    DRIVER_ID, TRIP_ID,
    NULL::TIMESTAMP_NTZ AS PICKUP_TIME,
    NULL::TIMESTAMP_NTZ AS DROPOFF_TIME,
    NULL::VARIANT AS PICKUP_LOCATION,
    NULL::VARIANT AS DROPOFF_LOCATION,
    NULL::VARIANT AS ROUTE,
    ST_MAKEPOINT(LON, LAT) AS POINT_GEOM,
    LON, LAT, CURR_TIME, CURR_TIME AS POINT_TIME,
    POINT_INDEX, DRIVER_STATE, KMH, REGION
FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS.VW_DRIVER_LOCATIONS;

CREATE OR REPLACE VIEW FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS.ROUTE_NAMES
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-fleet-intelligence-taxis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT TRIP_ID, ORIGIN_ADDRESS || ' -> ' || DESTINATION_ADDRESS AS TRIP_NAME
FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS.VW_TRIP_SUMMARY;

CREATE OR REPLACE VIEW FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS.TRIPS_ASSIGNED_TO_DRIVERS
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-fleet-intelligence-taxis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT DRIVER_ID, TRIP_ID, GEOMETRY, ORIGIN, DESTINATION,
       ORIGIN_ADDRESS, DESTINATION_ADDRESS,
       TRIP_START_TIME AS PICKUP_TIME, TRIP_END_TIME AS DROPOFF_TIME
FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS.VW_TRIP_SUMMARY;

CREATE OR REPLACE VIEW FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS.TRIP_ROUTE_PLAN
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-fleet-intelligence-taxis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT TRIP_ID, DRIVER_ID, ORIGIN_ADDRESS, ORIGIN_ADDRESS AS ORIGIN_STREET,
       DESTINATION_ADDRESS, DESTINATION_ADDRESS AS DESTINATION_STREET,
       TRIP_START_TIME AS PICKUP_TIME, TRIP_END_TIME AS DROPOFF_TIME,
       ORIGIN, DESTINATION, GEOMETRY, ROUTE_DISTANCE_METERS AS DISTANCE_METERS,
       SHIFT_TYPE,
       OBJECT_CONSTRUCT('features', ARRAY_CONSTRUCT(OBJECT_CONSTRUCT('properties',
           OBJECT_CONSTRUCT('summary', OBJECT_CONSTRUCT(
               'distance', ROUTE_DISTANCE_METERS, 'duration', ROUTE_DURATION_SECS
           ))))) AS ROUTE
FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS.VW_TRIP_SUMMARY;

-- ============================================================
-- 2. FLEET INTELLIGENCE FOOD DELIVERY
-- Source: .cortex/skills/fleet-intelligence-food-delivery/references/sql-projection-views.sql
-- ============================================================

CREATE SCHEMA IF NOT EXISTS FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-fleet-intelligence-food-delivery","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';

CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.CONFIG (
    VEHICLE_TYPE VARCHAR NOT NULL,
    REGION       VARCHAR NOT NULL
)
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-fleet-intelligence-food-delivery","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';
MERGE INTO FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.CONFIG tgt
USING (SELECT 'ebike' AS VEHICLE_TYPE, 'SanFrancisco' AS REGION) src
ON TRUE
WHEN NOT MATCHED THEN INSERT (VEHICLE_TYPE, REGION) VALUES (src.VEHICLE_TYPE, src.REGION);

CREATE OR REPLACE VIEW FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.DELIVERIES
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-fleet-intelligence-food-delivery","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT
    t.TRIP_ID        AS DELIVERY_ID,
    t.VEHICLE_ID     AS COURIER_ID,
    t.ORIGIN_POI_ID  AS RESTAURANT_ID,
    t.DESTINATION_POI_ID AS CUSTOMER_ADDRESS_ID,
    t.ORIGIN           AS PICKUP_LOCATION,
    t.DESTINATION      AS DROPOFF_LOCATION,
    t.DESTINATION      AS CUSTOMER_LOCATION,
    t.DURATION_MINUTES AS DELIVERY_TIME_MIN,
    t.DISTANCE_KM,
    t.ROUTE_GEOG     AS GEOMETRY,
    t.TRIP_START      AS ORDER_TIME,
    t.TRIP_END        AS DELIVERY_TIME,
    t.STATUS          AS ORDER_STATUS,
    t.REGION
FROM SYNTHETIC_DATASETS.UNIFIED.FACT_TRIPS t
WHERE t.VEHICLE_TYPE = (SELECT VEHICLE_TYPE FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.CONFIG LIMIT 1)
  AND t.REGION       = (SELECT REGION FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.CONFIG LIMIT 1);

CREATE OR REPLACE VIEW FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.RESTAURANTS_ENRICHED
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-fleet-intelligence-food-delivery","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT
    p.LOCATION_ID         AS RESTAURANT_ID,
    REPLACE(p.NAME, '"', '') AS RESTAURANT_NAME,
    ANY_VALUE(p.POINT_GEOM) AS LOCATION,
    COUNT(t.TRIP_ID)      AS TOTAL_ORDERS,
    ROUND(AVG(t.DURATION_MINUTES), 1) AS AVG_DELIVERY_TIME_MIN,
    p.REGION
FROM SYNTHETIC_DATASETS.UNIFIED.DIM_POIS p
LEFT JOIN SYNTHETIC_DATASETS.UNIFIED.FACT_TRIPS t
    ON p.LOCATION_ID = t.ORIGIN_POI_ID
   AND t.VEHICLE_TYPE = (SELECT VEHICLE_TYPE FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.CONFIG LIMIT 1)
   AND t.REGION       = (SELECT REGION FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.CONFIG LIMIT 1)
WHERE p.LOCATION_TYPE = 'RESTAURANT'
  AND p.REGION = (SELECT REGION FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.CONFIG LIMIT 1)
GROUP BY p.LOCATION_ID, p.NAME, p.REGION;

-- ============================================================
-- 3. ROUTE DEVIATION
-- Source: .cortex/skills/route-deviation/references/seed-data.sql
-- ============================================================

CREATE SCHEMA IF NOT EXISTS FLEET_INTELLIGENCE.ROUTE_DEVIATION
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-route-deviation","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';

CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.ROUTE_DEVIATION.CONFIG (
    VEHICLE_TYPE VARCHAR NOT NULL,
    REGION       VARCHAR NOT NULL
)
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-route-deviation","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';
MERGE INTO FLEET_INTELLIGENCE.ROUTE_DEVIATION.CONFIG tgt
USING (SELECT 'ebike' AS VEHICLE_TYPE, 'SanFrancisco' AS REGION) src
ON TRUE
WHEN NOT MATCHED THEN INSERT (VEHICLE_TYPE, REGION) VALUES (src.VEHICLE_TYPE, src.REGION);

CREATE OR REPLACE VIEW FLEET_INTELLIGENCE.ROUTE_DEVIATION.VW_VEHICLE_TELEMETRY
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-route-deviation","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT
    TELEMETRY_ID, VEHICLE_ID, TRIP_ID, TS, STATUS, SPEED_KMH, HEADING_DEG,
    LATITUDE, LONGITUDE, POINT_GEOM, LOCATION_ID, LOCATION_TYPE,
    BATTERY_PCT, ODOMETER_KM, IS_SPEEDING, IS_DETOUR, GPS_ACCURACY_M, REGION
FROM SYNTHETIC_DATASETS.UNIFIED.FACT_VEHICLE_TELEMETRY
WHERE VEHICLE_TYPE = (SELECT VEHICLE_TYPE FROM FLEET_INTELLIGENCE.ROUTE_DEVIATION.CONFIG LIMIT 1)
  AND REGION = (SELECT REGION FROM FLEET_INTELLIGENCE.ROUTE_DEVIATION.CONFIG LIMIT 1);

CREATE OR REPLACE VIEW FLEET_INTELLIGENCE.ROUTE_DEVIATION.DETOUR_TRIPS
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-route-deviation","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT
    t.TRIP_ID, t.VEHICLE_ID, t.TRIP_START, t.TRIP_END, t.DURATION_MINUTES,
    t.DISTANCE_KM, t.PLANNED_DISTANCE_KM, t.DETOUR_DISTANCE_KM, t.IS_DETOUR,
    t.ORIGIN, t.DESTINATION, t.ROUTE_GEOG, t.PLANNED_ROUTE_GEOG,
    t.ORIGIN_POI_ID, t.DESTINATION_POI_ID, t.STATUS
FROM SYNTHETIC_DATASETS.UNIFIED.FACT_TRIPS t
WHERE t.VEHICLE_TYPE = (SELECT VEHICLE_TYPE FROM FLEET_INTELLIGENCE.ROUTE_DEVIATION.CONFIG LIMIT 1)
  AND t.REGION = (SELECT REGION FROM FLEET_INTELLIGENCE.ROUTE_DEVIATION.CONFIG LIMIT 1)
  AND t.IS_DETOUR = TRUE;

-- ============================================================
-- 4. DWELL ANALYSIS (Dynamic Table Pipeline)
-- Source: .cortex/skills/dwell-analysis/references/sql-pipeline.sql
-- ============================================================

CREATE SCHEMA IF NOT EXISTS FLEET_INTELLIGENCE.DWELL_ANALYSIS
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';

CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.DWELL_ANALYSIS.CONFIG (
    VEHICLE_TYPE VARCHAR NOT NULL,
    REGION       VARCHAR NOT NULL
)
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';
MERGE INTO FLEET_INTELLIGENCE.DWELL_ANALYSIS.CONFIG tgt
USING (SELECT 'ebike' AS VEHICLE_TYPE, 'SanFrancisco' AS REGION) src
ON TRUE
WHEN NOT MATCHED THEN INSERT (VEHICLE_TYPE, REGION) VALUES (src.VEHICLE_TYPE, src.REGION)
WHEN MATCHED THEN UPDATE SET VEHICLE_TYPE = src.VEHICLE_TYPE, REGION = src.REGION;

CREATE OR REPLACE VIEW FLEET_INTELLIGENCE.DWELL_ANALYSIS.VW_VEHICLE_TELEMETRY
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT
    TELEMETRY_ID, VEHICLE_ID, TRIP_ID, TS, STATUS, SPEED_KMH, HEADING_DEG,
    LATITUDE, LONGITUDE, POINT_GEOM, LOCATION_ID, LOCATION_TYPE,
    BATTERY_PCT, ODOMETER_KM, IS_SPEEDING, IS_DETOUR, GPS_ACCURACY_M, REGION
FROM SYNTHETIC_DATASETS.UNIFIED.FACT_VEHICLE_TELEMETRY
WHERE VEHICLE_TYPE = (SELECT VEHICLE_TYPE FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.CONFIG LIMIT 1)
  AND REGION = (SELECT REGION FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.CONFIG LIMIT 1);

CREATE OR REPLACE TABLE FLEET_INTELLIGENCE.DWELL_ANALYSIS.SLA_THRESHOLDS (
    LOCATION_TYPE    VARCHAR,
    MAX_DWELL_MINUTES INT,
    WARNING_MINUTES  INT,
    PRIORITY VARCHAR DEFAULT 'MEDIUM'
)
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';
INSERT INTO FLEET_INTELLIGENCE.DWELL_ANALYSIS.SLA_THRESHOLDS VALUES
('RESTAURANT', 5, 3, 'HIGH'),
('DWELL_ORIGIN', 5, 3, 'HIGH'),
('DWELL_DESTINATION', 5, 3, 'MEDIUM'),
('TRAFFIC_LIGHT', 2, 1, 'LOW'),
('INTERSECTION', 2, 1, 'LOW'),
('IDLE', 10, 5, 'LOW');

CREATE OR REPLACE DYNAMIC TABLE FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_STATE_CHANGES
    WAREHOUSE = ROUTING_ANALYTICS
    TARGET_LAG = '10 minutes'
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT
    TELEMETRY_ID, VEHICLE_ID, TRIP_ID, TS, STATUS, SPEED_KMH,
    LATITUDE, LONGITUDE, POINT_GEOM, REGION,
    CASE WHEN STATUS != LAG(STATUS) OVER (PARTITION BY VEHICLE_ID ORDER BY TS) THEN TRUE ELSE FALSE END AS IS_STATE_CHANGE
FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.VW_VEHICLE_TELEMETRY
WHERE POINT_GEOM IS NOT NULL;

CREATE OR REPLACE DYNAMIC TABLE FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_DWELL_EVENTS
    WAREHOUSE = ROUTING_ANALYTICS
    TARGET_LAG = '10 minutes'
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT
    VEHICLE_ID || '-' || TRIP_ID || '-' || LOCATION_ID AS SESSION_ID,
    VEHICLE_ID, TRIP_ID, LOCATION_ID, LOCATION_TYPE,
    ANY_VALUE(STATUS) AS STATUS,
    MIN(TS) AS DWELL_START, MAX(TS) AS DWELL_END,
    DATEDIFF('MINUTE', MIN(TS), MAX(TS)) AS DWELL_MINUTES,
    COUNT(*) AS POINT_COUNT,
    ST_CENTROID(ST_COLLECT(POINT_GEOM)) AS DWELL_CENTER,
    AVG(LATITUDE) AS CENTER_LAT, AVG(LONGITUDE) AS CENTER_LNG, REGION
FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.VW_VEHICLE_TELEMETRY
WHERE STATUS IN ('DWELL_ORIGIN', 'DWELL_DESTINATION', 'IDLE')
  AND LOCATION_ID IS NOT NULL
GROUP BY VEHICLE_ID, TRIP_ID, LOCATION_ID, LOCATION_TYPE, REGION;

CREATE OR REPLACE DYNAMIC TABLE FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_DWELL_ENRICHED
    WAREHOUSE = ROUTING_ANALYTICS
    TARGET_LAG = '10 minutes'
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT
    d.SESSION_ID, d.VEHICLE_ID, d.TRIP_ID, d.LOCATION_ID, d.LOCATION_TYPE,
    COALESCE(TRIM(p.NAME, '"'), 'Unknown') AS LOCATION_NAME,
    COALESCE(p.CATEGORY, d.LOCATION_TYPE) AS CATEGORY,
    d.DWELL_START AS SESSION_START, d.DWELL_END AS SESSION_END,
    d.DWELL_MINUTES, d.POINT_COUNT, d.DWELL_CENTER,
    d.DWELL_CENTER AS AVG_POINT,
    d.CENTER_LAT, d.CENTER_LNG, d.REGION, d.STATUS
FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_DWELL_EVENTS d
LEFT JOIN SYNTHETIC_DATASETS.UNIFIED.DIM_POIS p ON d.LOCATION_ID = p.LOCATION_ID;

CREATE OR REPLACE DYNAMIC TABLE FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_H3_CONGESTION
    WAREHOUSE = ROUTING_ANALYTICS
    TARGET_LAG = '10 minutes'
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT
    H3_POINT_TO_CELL_STRING(DWELL_CENTER, 7) AS H3_CELL_R7,
    DATE_TRUNC('HOUR', SESSION_START) AS HOUR_BUCKET,
    COUNT(DISTINCT SESSION_ID) AS SESSION_COUNT,
    ROUND(AVG(DWELL_MINUTES), 1) AS AVG_DWELL_MIN,
    COUNT(DISTINCT VEHICLE_ID) AS UNIQUE_VEHICLES, REGION
FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_DWELL_ENRICHED
WHERE DWELL_CENTER IS NOT NULL
GROUP BY H3_POINT_TO_CELL_STRING(DWELL_CENTER, 7), DATE_TRUNC('HOUR', SESSION_START), REGION;

CREATE OR REPLACE DYNAMIC TABLE FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_SLA_ALERTS
    WAREHOUSE = ROUTING_ANALYTICS
    TARGET_LAG = '10 minutes'
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT
    d.SESSION_ID, d.VEHICLE_ID, d.TRIP_ID, d.LOCATION_NAME, d.LOCATION_TYPE,
    d.SESSION_START, d.SESSION_END, d.DWELL_MINUTES,
    s.MAX_DWELL_MINUTES AS SLA_LIMIT, s.WARNING_MINUTES,
    CASE
        WHEN d.DWELL_MINUTES > s.MAX_DWELL_MINUTES * 2 THEN 'CRITICAL'
        WHEN d.DWELL_MINUTES > s.MAX_DWELL_MINUTES THEN 'WARNING'
        WHEN d.DWELL_MINUTES > s.WARNING_MINUTES THEN 'INFO'
    END AS SLA_STATUS,
    d.CENTER_LAT, d.CENTER_LNG, d.REGION
FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_DWELL_ENRICHED d
JOIN FLEET_INTELLIGENCE.DWELL_ANALYSIS.SLA_THRESHOLDS s ON d.LOCATION_TYPE = s.LOCATION_TYPE
WHERE d.DWELL_MINUTES > s.WARNING_MINUTES;

CREATE OR REPLACE DYNAMIC TABLE FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_FACILITY_UTILIZATION
    WAREHOUSE = ROUTING_ANALYTICS
    TARGET_LAG = '10 minutes'
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT
    LOCATION_ID, LOCATION_NAME, CATEGORY AS FACILITY_TYPE,
    COUNT(DISTINCT SESSION_ID) AS TOTAL_SESSIONS,
    COUNT(DISTINCT VEHICLE_ID) AS UNIQUE_VEHICLES,
    ROUND(AVG(DWELL_MINUTES), 1) AS AVG_DWELL_MIN,
    ROUND(MAX(DWELL_MINUTES), 1) AS MAX_DWELL_MIN,
    MIN(SESSION_START) AS FIRST_VISIT, MAX(SESSION_END) AS LAST_VISIT,
    CENTER_LAT, CENTER_LNG, REGION
FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_DWELL_ENRICHED
GROUP BY LOCATION_ID, LOCATION_NAME, CATEGORY, CENTER_LAT, CENTER_LNG, REGION;

CREATE OR REPLACE DYNAMIC TABLE FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_DRIVER_DWELL_SUMMARY
    WAREHOUSE = ROUTING_ANALYTICS
    TARGET_LAG = '10 minutes'
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT
    d.VEHICLE_ID,
    COUNT(DISTINCT d.LOCATION_ID) AS UNIQUE_LOCATIONS,
    COUNT(DISTINCT d.SESSION_ID) AS TOTAL_DWELL_SESSIONS,
    ROUND(AVG(d.DWELL_MINUTES), 1) AS AVG_SESSION_MIN,
    ROUND(SUM(d.DWELL_MINUTES), 0) AS TOTAL_DWELL_MIN,
    COALESCE(SUM(CASE WHEN a.SLA_STATUS IN ('CRITICAL', 'WARNING') THEN 1 ELSE 0 END), 0) AS SLA_BREACH_COUNT,
    d.REGION
FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_DWELL_ENRICHED d
LEFT JOIN FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_SLA_ALERTS a ON d.SESSION_ID = a.SESSION_ID
GROUP BY d.VEHICLE_ID, d.REGION;

CREATE OR REPLACE DYNAMIC TABLE FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_DAILY_TRENDS
    WAREHOUSE = ROUTING_ANALYTICS
    TARGET_LAG = '10 minutes'
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT
    DATE_TRUNC('DAY', SESSION_START) AS TREND_DATE,
    COUNT(DISTINCT SESSION_ID) AS TOTAL_SESSIONS,
    COUNT(DISTINCT VEHICLE_ID) AS ACTIVE_VEHICLES,
    ROUND(AVG(DWELL_MINUTES), 1) AS AVG_DWELL_MINUTES,
    ROUND(MAX(DWELL_MINUTES), 1) AS MAX_DWELL_MINUTES,
    SUM(CASE WHEN DWELL_MINUTES <= 5 THEN 1 ELSE 0 END) AS SLA_COMPLIANT,
    COUNT(*) AS TOTAL_DWELLS
FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_DWELL_ENRICHED
GROUP BY DATE_TRUNC('DAY', SESSION_START);

-- Force refresh all DTs (they do NOT auto-populate on creation)
ALTER DYNAMIC TABLE FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_STATE_CHANGES REFRESH;
ALTER DYNAMIC TABLE FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_DWELL_EVENTS REFRESH;
ALTER DYNAMIC TABLE FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_DWELL_ENRICHED REFRESH;
ALTER DYNAMIC TABLE FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_H3_CONGESTION REFRESH;
ALTER DYNAMIC TABLE FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_SLA_ALERTS REFRESH;
ALTER DYNAMIC TABLE FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_FACILITY_UTILIZATION REFRESH;
ALTER DYNAMIC TABLE FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_DRIVER_DWELL_SUMMARY REFRESH;
ALTER DYNAMIC TABLE FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_DAILY_TRENDS REFRESH;

-- ============================================================
-- VALIDATION
-- Expected row counts (SF seed data):
--   TAXI TRIP_SUMMARY:    6008
--   TAXI DRIVER_LOCATIONS_V: 472869
--   FOOD DELIVERIES:     6008
--   FOOD RESTAURANTS:    ~5000
--   ROUTE DETOUR_TRIPS:  ~164
--   DWELL DT_STATE_CHANGES: ~470K
--   DWELL DT_DWELL_EVENTS: ~12K
--   DWELL DT_H3_CONGESTION: ~1.5K
--   DWELL DT_SLA_ALERTS: ~3K
--   DWELL DT_DAILY_TRENDS: 7
-- ============================================================
