-- =============================================================================
-- 13_retail_and_pharma_intelligence.sql
-- Deploys retail catchment data from Overture Maps + pharma intelligence tables.
-- Run AFTER: 12_agent_and_streamlit.sql
-- Requires: OVERTURE_MAPS__PLACES (from 00_marketplace_datasets.sql)
-- Requires: SF_TOP_PHARMACIES + SF_DRUG_FORMULARY + SF_HEALTH_DEMOGRAPHICS
--           (from setup-agent-playground/references/deploy-demo-data.sql)
--
-- FIXES APPLIED (2026-05-28):
--   1. Correlated subquery in SF_DEMAND_FORECAST INSERT replaced with CTE + ROW_NUMBER
--   2. Stored procedures: SELECT...INTO replaced with LET := (SELECT...) for Snowflake SQL
--   3. VALUES clause with ARRAY_CONSTRUCT moved to module 08 (UNION ALL SELECT pattern)
-- =============================================================================

ALTER SESSION SET query_tag = '{"origin":"sf_sit-is-fleet","name":"oss-retail-catchment","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';

-- ============================================================
-- RETAIL CATCHMENT (Step 5)
-- ============================================================

CREATE SCHEMA IF NOT EXISTS FLEET_INTELLIGENCE.RETAIL_CATCHMENT
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-retail-catchment","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';

CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.RETAIL_CATCHMENT.CONFIG (
    VEHICLE_TYPE VARCHAR NOT NULL, REGION VARCHAR NOT NULL
) COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-retail-catchment","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';
MERGE INTO FLEET_INTELLIGENCE.RETAIL_CATCHMENT.CONFIG tgt
USING (SELECT 'ebike' AS VEHICLE_TYPE, 'SanFrancisco' AS REGION) src
ON TRUE
WHEN NOT MATCHED THEN INSERT (VEHICLE_TYPE, REGION) VALUES (src.VEHICLE_TYPE, src.REGION);

CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.RETAIL_CATCHMENT.REGION_CONFIG (
    REGION VARCHAR NOT NULL, REGION_NAME VARCHAR, BBOX_MIN_LON FLOAT, BBOX_MIN_LAT FLOAT,
    BBOX_MAX_LON FLOAT, BBOX_MAX_LAT FLOAT, CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-retail-catchment","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';
MERGE INTO FLEET_INTELLIGENCE.RETAIL_CATCHMENT.REGION_CONFIG tgt
USING (SELECT 'SanFrancisco' AS REGION, 'San Francisco Bay Area' AS REGION_NAME,
       -123.0 AS BBOX_MIN_LON, 36.8 AS BBOX_MIN_LAT, -121.5 AS BBOX_MAX_LON, 38.5 AS BBOX_MAX_LAT) src
ON tgt.REGION = src.REGION
WHEN NOT MATCHED THEN INSERT VALUES (src.REGION, src.REGION_NAME, src.BBOX_MIN_LON, src.BBOX_MIN_LAT, src.BBOX_MAX_LON, src.BBOX_MAX_LAT, CURRENT_TIMESTAMP());

CREATE OR REPLACE TABLE FLEET_INTELLIGENCE.RETAIL_CATCHMENT.RETAIL_POIS (
    REGION VARCHAR NOT NULL, POI_ID VARCHAR, POI_NAME VARCHAR, BASIC_CATEGORY VARCHAR,
    LONGITUDE FLOAT, LATITUDE FLOAT, GEOMETRY GEOGRAPHY, ADDRESS VARCHAR, CITY VARCHAR, STATE VARCHAR, POSTCODE VARCHAR
) COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-retail-catchment","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';

INSERT INTO FLEET_INTELLIGENCE.RETAIL_CATCHMENT.RETAIL_POIS
SELECT 'SanFrancisco' AS REGION, ID AS POI_ID, NAMES:primary::VARCHAR AS POI_NAME, BASIC_CATEGORY,
    ST_X(GEOMETRY) AS LONGITUDE, ST_Y(GEOMETRY) AS LATITUDE, GEOMETRY,
    COALESCE(ADDRESSES[0]:freeform::VARCHAR, '') AS ADDRESS,
    ADDRESSES[0]:locality::VARCHAR AS CITY, ADDRESSES[0]:region::VARCHAR AS STATE, ADDRESSES[0]:postcode::VARCHAR AS POSTCODE
FROM OVERTURE_MAPS__PLACES.CARTO.PLACE
WHERE BASIC_CATEGORY IN ('coffee_shop','fast_food_restaurant','restaurant','casual_eatery','grocery_store','convenience_store','gas_station','pharmacy','clothing_store','electronics_store','specialty_store','gym','beauty_salon','hair_salon','bakery','bar','supermarket')
AND GEOMETRY IS NOT NULL AND ADDRESSES[0]:region IS NOT NULL
AND ST_X(GEOMETRY) BETWEEN -123.0 AND -121.5
AND ST_Y(GEOMETRY) BETWEEN 36.8 AND 38.5;

CREATE OR REPLACE TABLE FLEET_INTELLIGENCE.RETAIL_CATCHMENT.CITIES_BY_STATE (
    REGION VARCHAR NOT NULL, STATE VARCHAR, CITY VARCHAR, POI_COUNT INT
) COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-retail-catchment","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';
INSERT INTO FLEET_INTELLIGENCE.RETAIL_CATCHMENT.CITIES_BY_STATE
SELECT 'SanFrancisco', STATE, CITY, COUNT(*) FROM FLEET_INTELLIGENCE.RETAIL_CATCHMENT.RETAIL_POIS
WHERE REGION = 'SanFrancisco' GROUP BY STATE, CITY;

-- ============================================================
-- PHARMA INTELLIGENCE (Step 13) — downstream pharmacy tools
-- Source: .cortex/skills/add-pharma-intelligence/references/deploy-pharma-data.sql
-- ============================================================

CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.SF_INVENTORY (
    INVENTORY_ID NUMBER AUTOINCREMENT, PHARMACY_ID NUMBER, DRUG_ID NUMBER,
    PHARMACY_NAME VARCHAR, DRUG_NAME VARCHAR, DRUG_CATEGORY VARCHAR,
    CURRENT_STOCK NUMBER, REORDER_POINT NUMBER, MAX_STOCK NUMBER,
    DAYS_TO_EXPIRY NUMBER, UNITS_WASTED_MTD NUMBER, WASTAGE_VALUE_USD FLOAT,
    LAST_ORDER_DATE DATE, FILL_RATE_PCT FLOAT, DELIVERY_SKILL NUMBER
) COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-add-pharma-intelligence","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';

CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.SF_DEMAND_FORECAST (
    FORECAST_ID NUMBER AUTOINCREMENT, PHARMACY_ID NUMBER, DRUG_ID NUMBER,
    PHARMACY_NAME VARCHAR, DRUG_NAME VARCHAR, NEIGHBORHOOD VARCHAR,
    CATCHMENT_POPULATION NUMBER, MORBIDITY_RATE FLOAT, UNITS_PER_1000 NUMBER,
    FORECAST_UNITS NUMBER, CURRENT_STOCK NUMBER, STOCK_GAP NUMBER,
    FORECAST_MONTH DATE
) COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-add-pharma-intelligence","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';

CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.SF_REPLENISHMENT_ORDERS (
    ORDER_ID NUMBER AUTOINCREMENT, PHARMACY_ID NUMBER, DRUG_ID NUMBER,
    PHARMACY_NAME VARCHAR, DRUG_NAME VARCHAR, DRUG_CATEGORY VARCHAR,
    UNITS_REQUIRED NUMBER, PRIORITY VARCHAR, DELIVERY_TYPE VARCHAR,
    ESTIMATED_VALUE_USD FLOAT, ORDER_DATE DATE DEFAULT CURRENT_DATE()
) COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-add-pharma-intelligence","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';

-- Populate SF_INVENTORY from cross-join of pharmacies x drugs with synthetic stock levels
INSERT INTO FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.SF_INVENTORY (PHARMACY_ID, DRUG_ID, PHARMACY_NAME, DRUG_NAME, DRUG_CATEGORY, CURRENT_STOCK, REORDER_POINT, MAX_STOCK, DAYS_TO_EXPIRY, UNITS_WASTED_MTD, WASTAGE_VALUE_USD, LAST_ORDER_DATE, FILL_RATE_PCT, DELIVERY_SKILL)
SELECT p.PHARMACY_ID, d.DRUG_ID, p.NAME, d.DRUG_NAME, d.DRUG_CATEGORY,
    GREATEST(5, ROUND(d.UNITS_PER_1000 * (0.3 + ABS(HASH(p.PHARMACY_ID * 100 + d.DRUG_ID)) % 100 / 100.0))),
    ROUND(d.UNITS_PER_1000 * 0.4),
    ROUND(d.UNITS_PER_1000 * 1.2),
    GREATEST(5, 10 + ABS(HASH(p.PHARMACY_ID * 7 + d.DRUG_ID * 13)) % 80),
    GREATEST(0, ABS(HASH(p.PHARMACY_ID + d.DRUG_ID * 3)) % 15),
    GREATEST(0, ABS(HASH(p.PHARMACY_ID + d.DRUG_ID * 3)) % 15) * (5 + d.PRIORITY * 10),
    DATEADD('day', -(ABS(HASH(p.PHARMACY_ID * 11 + d.DRUG_ID)) % 14), CURRENT_DATE()),
    ROUND(75 + ABS(HASH(p.PHARMACY_ID * 5 + d.DRUG_ID * 7)) % 25, 1),
    d.DELIVERY_SKILL
FROM FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.SF_TOP_PHARMACIES p
CROSS JOIN FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.SF_DRUG_FORMULARY d;

-- Populate SF_DEMAND_FORECAST from demographics model
-- Pre-compute nearest neighborhood per pharmacy, then cross-join with drugs
INSERT INTO FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.SF_DEMAND_FORECAST (PHARMACY_ID, DRUG_ID, PHARMACY_NAME, DRUG_NAME, NEIGHBORHOOD, CATCHMENT_POPULATION, MORBIDITY_RATE, UNITS_PER_1000, FORECAST_UNITS, CURRENT_STOCK, STOCK_GAP, FORECAST_MONTH)
WITH nearest_demo AS (
    SELECT p.PHARMACY_ID, h.NEIGHBORHOOD, h.TOTAL_POPULATION,
        ROW_NUMBER() OVER (PARTITION BY p.PHARMACY_ID ORDER BY ST_DISTANCE(ST_MAKEPOINT(h.LONGITUDE, h.LATITUDE), ST_MAKEPOINT(p.LONGITUDE, p.LATITUDE))) AS rn
    FROM FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.SF_TOP_PHARMACIES p
    CROSS JOIN FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.SF_HEALTH_DEMOGRAPHICS h
)
SELECT p.PHARMACY_ID, d.DRUG_ID, p.NAME, d.DRUG_NAME,
    nd.NEIGHBORHOOD, nd.TOTAL_POPULATION,
    CASE d.CONDITION WHEN 'Diabetes' THEN 20.0 WHEN 'Hypertension' THEN 38.0 WHEN 'Cardiovascular' THEN 15.0 WHEN 'Respiratory' THEN 18.0 ELSE 10.0 END,
    d.UNITS_PER_1000,
    ROUND(d.UNITS_PER_1000 * 28000 / 1000 * CASE d.CONDITION WHEN 'Diabetes' THEN 0.20 WHEN 'Hypertension' THEN 0.38 ELSE 0.15 END),
    i.CURRENT_STOCK,
    GREATEST(0, ROUND(d.UNITS_PER_1000 * 28000 / 1000 * 0.2) - COALESCE(i.CURRENT_STOCK, 0)),
    DATE_TRUNC('month', CURRENT_DATE())
FROM FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.SF_TOP_PHARMACIES p
CROSS JOIN FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.SF_DRUG_FORMULARY d
JOIN nearest_demo nd ON nd.PHARMACY_ID = p.PHARMACY_ID AND nd.rn = 1
LEFT JOIN FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.SF_INVENTORY i ON i.PHARMACY_ID = p.PHARMACY_ID AND i.DRUG_ID = d.DRUG_ID;

-- Populate replenishment orders (urgent items)
INSERT INTO FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.SF_REPLENISHMENT_ORDERS (PHARMACY_ID, DRUG_ID, PHARMACY_NAME, DRUG_NAME, DRUG_CATEGORY, UNITS_REQUIRED, PRIORITY, DELIVERY_TYPE, ESTIMATED_VALUE_USD)
SELECT i.PHARMACY_ID, i.DRUG_ID, i.PHARMACY_NAME, i.DRUG_NAME, i.DRUG_CATEGORY,
    GREATEST(i.REORDER_POINT - i.CURRENT_STOCK, 10),
    CASE WHEN i.DAYS_TO_EXPIRY < 14 AND i.CURRENT_STOCK < i.REORDER_POINT THEN 'URGENT'
         WHEN i.CURRENT_STOCK < i.REORDER_POINT THEN 'HIGH' ELSE 'MEDIUM' END,
    CASE i.DELIVERY_SKILL WHEN 1 THEN 'Cold Chain' WHEN 2 THEN 'Controlled' ELSE 'Standard' END,
    GREATEST(i.REORDER_POINT - i.CURRENT_STOCK, 10) * (5 + i.DELIVERY_SKILL * 8)
FROM FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.SF_INVENTORY i
WHERE i.CURRENT_STOCK < i.REORDER_POINT;

-- ============================================================
-- PHARMA INTELLIGENCE TOOL PROCEDURES
-- Called by the ROUTING_AGENT for pharma supply scenarios
-- ============================================================

CREATE OR REPLACE PROCEDURE FLEET_INTELLIGENCE.ROUTING_AGENT.TOOL_INVENTORY_STATUS(PHARMACY_NAME VARCHAR DEFAULT NULL)
RETURNS VARIANT LANGUAGE SQL
COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-add-pharma-intelligence","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS $$
BEGIN
    LET v_result VARIANT := (SELECT OBJECT_CONSTRUCT(
        'status', 'SUCCESS',
        'summary', OBJECT_CONSTRUCT(
            'total_items', COUNT(*),
            'critical_count', SUM(CASE WHEN CURRENT_STOCK < REORDER_POINT * 0.3 THEN 1 ELSE 0 END),
            'low_count', SUM(CASE WHEN CURRENT_STOCK < REORDER_POINT THEN 1 ELSE 0 END),
            'near_expiry_count', SUM(CASE WHEN DAYS_TO_EXPIRY <= 30 THEN 1 ELSE 0 END),
            'total_wastage_usd', ROUND(SUM(WASTAGE_VALUE_USD), 2)),
        'critical_items', (SELECT ARRAY_AGG(OBJECT_CONSTRUCT('pharmacy',PHARMACY_NAME,'drug',DRUG_NAME,'category',DRUG_CATEGORY,'stock',CURRENT_STOCK,'reorder_point',REORDER_POINT,'days_to_expiry',DAYS_TO_EXPIRY,'wastage_usd',WASTAGE_VALUE_USD)) FROM FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.SF_INVENTORY WHERE CURRENT_STOCK<REORDER_POINT AND (:PHARMACY_NAME IS NULL OR UPPER(PHARMACY_NAME) LIKE '%'||UPPER(:PHARMACY_NAME)||'%') ORDER BY CURRENT_STOCK LIMIT 15),
        'near_expiry', (SELECT ARRAY_AGG(OBJECT_CONSTRUCT('pharmacy',PHARMACY_NAME,'drug',DRUG_NAME,'stock',CURRENT_STOCK,'days_to_expiry',DAYS_TO_EXPIRY,'wastage_usd',WASTAGE_VALUE_USD)) FROM FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.SF_INVENTORY WHERE DAYS_TO_EXPIRY<=30 AND (:PHARMACY_NAME IS NULL OR UPPER(PHARMACY_NAME) LIKE '%'||UPPER(:PHARMACY_NAME)||'%') ORDER BY DAYS_TO_EXPIRY LIMIT 10),
        'top_wastage', (SELECT ARRAY_AGG(OBJECT_CONSTRUCT('pharmacy',PHARMACY_NAME,'drug',DRUG_NAME,'wastage_usd',WASTAGE_VALUE_USD,'units_wasted',UNITS_WASTED_MTD)) FROM FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.SF_INVENTORY WHERE WASTAGE_VALUE_USD>50 AND (:PHARMACY_NAME IS NULL OR UPPER(PHARMACY_NAME) LIKE '%'||UPPER(:PHARMACY_NAME)||'%') ORDER BY WASTAGE_VALUE_USD DESC LIMIT 10)
    ) FROM FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.SF_INVENTORY WHERE (:PHARMACY_NAME IS NULL OR UPPER(PHARMACY_NAME) LIKE '%'||UPPER(:PHARMACY_NAME)||'%'));
    RETURN v_result;
EXCEPTION WHEN OTHER THEN RETURN OBJECT_CONSTRUCT('error','TOOL_INVENTORY_STATUS failed: '||SQLERRM,'status','FAILED');
END; $$;

CREATE OR REPLACE PROCEDURE FLEET_INTELLIGENCE.ROUTING_AGENT.TOOL_DEMAND_FORECAST(PHARMACY_NAME VARCHAR, CONDITION_FILTER VARCHAR DEFAULT NULL)
RETURNS VARIANT LANGUAGE SQL
COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-add-pharma-intelligence","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS $$
BEGIN
    LET v_result VARIANT := (SELECT OBJECT_CONSTRUCT(
        'status','SUCCESS','pharmacy',:PHARMACY_NAME,
        'forecast_items',(SELECT ARRAY_AGG(OBJECT_CONSTRUCT('drug',DRUG_NAME,'neighborhood',NEIGHBORHOOD,'catchment_pop',CATCHMENT_POPULATION,'morbidity_rate',MORBIDITY_RATE,'forecast_units',FORECAST_UNITS,'current_stock',CURRENT_STOCK,'stock_gap',STOCK_GAP)) FROM FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.SF_DEMAND_FORECAST WHERE UPPER(PHARMACY_NAME) LIKE '%'||UPPER(:PHARMACY_NAME)||'%' AND (:CONDITION_FILTER IS NULL OR UPPER(DRUG_NAME) LIKE '%'||UPPER(:CONDITION_FILTER)||'%') ORDER BY STOCK_GAP DESC LIMIT 20),
        'total_gap',(SELECT SUM(STOCK_GAP) FROM FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.SF_DEMAND_FORECAST WHERE UPPER(PHARMACY_NAME) LIKE '%'||UPPER(:PHARMACY_NAME)||'%')
    ));
    RETURN v_result;
EXCEPTION WHEN OTHER THEN RETURN OBJECT_CONSTRUCT('error','TOOL_DEMAND_FORECAST failed: '||SQLERRM,'status','FAILED');
END; $$;

CREATE OR REPLACE PROCEDURE FLEET_INTELLIGENCE.ROUTING_AGENT.TOOL_REPLENISHMENT_PLAN(PRIORITY_FILTER VARCHAR DEFAULT NULL)
RETURNS VARIANT LANGUAGE SQL
COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-add-pharma-intelligence","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS $$
BEGIN
    LET v_result VARIANT := (SELECT OBJECT_CONSTRUCT(
        'status','SUCCESS',
        'orders',(SELECT ARRAY_AGG(OBJECT_CONSTRUCT('pharmacy',PHARMACY_NAME,'drug',DRUG_NAME,'category',DRUG_CATEGORY,'units_required',UNITS_REQUIRED,'priority',PRIORITY,'delivery_type',DELIVERY_TYPE,'estimated_value_usd',ESTIMATED_VALUE_USD)) FROM FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.SF_REPLENISHMENT_ORDERS WHERE (:PRIORITY_FILTER IS NULL OR UPPER(PRIORITY)=UPPER(:PRIORITY_FILTER)) ORDER BY CASE PRIORITY WHEN 'URGENT' THEN 1 WHEN 'HIGH' THEN 2 ELSE 3 END, ESTIMATED_VALUE_USD DESC LIMIT 30),
        'summary',OBJECT_CONSTRUCT(
            'total_orders',(SELECT COUNT(*) FROM FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.SF_REPLENISHMENT_ORDERS WHERE :PRIORITY_FILTER IS NULL OR UPPER(PRIORITY)=UPPER(:PRIORITY_FILTER)),
            'urgent_count',(SELECT COUNT(*) FROM FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.SF_REPLENISHMENT_ORDERS WHERE PRIORITY='URGENT'),
            'total_value_usd',(SELECT ROUND(SUM(ESTIMATED_VALUE_USD),2) FROM FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.SF_REPLENISHMENT_ORDERS WHERE :PRIORITY_FILTER IS NULL OR UPPER(PRIORITY)=UPPER(:PRIORITY_FILTER)))
    ));
    RETURN v_result;
EXCEPTION WHEN OTHER THEN RETURN OBJECT_CONSTRUCT('error','TOOL_REPLENISHMENT_PLAN failed: '||SQLERRM,'status','FAILED');
END; $$;
