#!/usr/bin/env python3
"""
Deterministic data-contract generator (Solution-Accelerator Phase-6 style).

Reads a logical data-model.yaml + an entity-mapping.yaml (a SOURCE binding) and
emits CREATE SCHEMA + CREATE VIEW + GRANT DDL for the neutral app schema. Consumers
(dashboards, semantic views) bind to these views; swapping the --mapping file and
re-running repoints the solution at a different source with no consumer changes.

Usage:
  python3 generate.py [--model data-model.yaml] [--mapping entity-mapping.yaml]
                      [--out setup.sql]

Mapped/context entities  -> view selects mapped columns (with transforms) from source_table.
Derived entities         -> view computes expr/group_by from the derived_from entity's view.
"""
import argparse, os, sys
try:
    import yaml
except ImportError:
    sys.exit("PyYAML required: pip install pyyaml")

HERE = os.path.dirname(os.path.abspath(__file__))
ROLES = ["FLEET_APP_USER", "FLEET_APP_OPS", "FLEET_APP_ADMIN"]


def view_name(entity: str) -> str:
    return f"VW_{entity}"


def col_expr(m: dict) -> str:
    """Resolve a mapped column to a SQL expression aliased to the app column."""
    app = m["app_column"]
    src = m.get("source_column")
    xf = m.get("transform")
    if xf:
        expr = xf.replace("{src}", src) if src else xf
    elif src:
        expr = src
    else:
        expr = "NULL"
    return f"{expr} AS {app}"


def gen_mapped(schema: str, entity: dict, binding: dict) -> str:
    vn = view_name(entity["name"])
    cols = ",\n  ".join(col_expr(m) for m in binding["mapping"])
    return (
        f"CREATE OR REPLACE VIEW {schema}.{vn} AS\nSELECT\n  {cols}\n"
        f"FROM {binding['source_table']};\n"
    )


def gen_derived(schema: str, entity: dict) -> str:
    vn = view_name(entity["name"])
    src_view = f"{schema}.{view_name(entity['derived_from'])}"
    gb = entity.get("group_by", [])
    sel = []
    for c in entity["columns"]:
        if c["name"] in gb:
            sel.append(c["name"])
        elif "expr" in c:
            sel.append(f"{c['expr']} AS {c['name']}")
        else:
            sel.append(f"NULL AS {c['name']}")
    sel_sql = ",\n  ".join(sel)
    gb_sql = ("\nGROUP BY " + ", ".join(gb)) if gb else ""
    return f"CREATE OR REPLACE VIEW {schema}.{vn} AS\nSELECT\n  {sel_sql}\nFROM {src_view}{gb_sql};\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default=os.path.join(HERE, "data-model.yaml"))
    ap.add_argument("--mapping", default=os.path.join(HERE, "entity-mapping.yaml"))
    ap.add_argument("--out", default=os.path.join(HERE, "setup.sql"))
    args = ap.parse_args()

    model = yaml.safe_load(open(args.model))
    mapping = yaml.safe_load(open(args.mapping))
    schema = model["app_schema"]                 # e.g. FLEET_APP.ROUTE_DEVIATION
    db = schema.split(".")[0]
    bindings = {b["entity"]: b for b in mapping["entities"]}

    out = []
    out.append("-- GENERATED by generate.py - DO NOT EDIT BY HAND.")
    out.append(f"-- model={os.path.basename(args.model)} mapping={os.path.basename(args.mapping)} "
               f"source_id={mapping.get('source_id','?')}")
    out.append("-- Neutral app schema the dashboards + SV_ROUTE_DEVIATION bind to. Regenerate to repoint sources.\n")
    out.append(f"CREATE DATABASE IF NOT EXISTS {db} "
               f"COMMENT='{{\"origin\":\"sf_sit-is-fleet\",\"name\":\"install-fleet-apps\",\"attributes\":{{\"component\":\"data-contract-app-layer\"}}}}';")
    out.append(f"CREATE SCHEMA IF NOT EXISTS {schema} COMMENT='Stable logical layer for the route_deviation pack (generated from data-model + entity-mapping).';\n")

    # mapped + context first (derived views depend on them)
    order = {"mapped": 0, "context": 0, "derived": 1}
    for ent in sorted(model["entities"], key=lambda e: order.get(e["access_pattern"], 2)):
        ap_ = ent["access_pattern"]
        if ap_ in ("mapped", "context"):
            b = bindings.get(ent["name"])
            if not b or b.get("materialization") == "derived" or not b.get("mapping"):
                continue
            out.append(gen_mapped(schema, ent, b))
        elif ap_ == "derived":
            out.append(gen_derived(schema, ent))

    out.append("-- Grants (additive; roles from fleet_sa_app/app/role_binding.sql)")
    out.append(f"GRANT USAGE ON DATABASE {db} TO ROLE FLEET_APP_USER;")
    for r in ROLES:
        out.append(f"GRANT USAGE ON SCHEMA {schema} TO ROLE {r};")
    for r in ROLES:
        out.append(f"GRANT SELECT ON ALL VIEWS IN SCHEMA {schema} TO ROLE {r};")
        out.append(f"GRANT SELECT ON FUTURE VIEWS IN SCHEMA {schema} TO ROLE {r};")

    sql = "\n".join(out) + "\n"
    open(args.out, "w").write(sql)
    print(f"Wrote {args.out} ({sql.count('CREATE OR REPLACE VIEW')} views) from source_id={mapping.get('source_id')}")


if __name__ == "__main__":
    main()
