-- =============================================================================
-- build-plant-footprints.sql
-- Creates the PLANT_ALERT_STATUS view (always) and pre-computes
-- Overture building footprints for each manufacturing plant.
-- Run this BEFORE deploying the Plant Intelligence React module.
-- =============================================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE ROUTING_ANALYTICS;
USE DATABASE FLEET_INTELLIGENCE;
USE SCHEMA PHARMA_SUPPLY_CHAIN;

-- =============================================================================
-- 1. PLANT ALERT STATUS VIEW (no external dependencies)
--    Aggregates supply chain alerts per plant for color-coding the map
-- =============================================================================

CREATE OR REPLACE VIEW FLEET_INTELLIGENCE.PHARMA_SUPPLY_CHAIN.PLANT_ALERT_STATUS
COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-add-plant-map","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT
    pl.PLANT_ID,
    pl.PLANT_NAME,
    pl.PLANT_CODE,
    pl.CITY,
    pl.COUNTRY,
    pl.REGION,
    pl.SPECIALISATION,
    pl.CAPACITY_BATCHES_MONTH,
    pl.LATITUDE,
    pl.LONGITUDE,

    MAX(CASE
        WHEN b.STATUS = 'ON_HOLD'   AND b.DEVIATION_SEVERITY = 'CRITICAL' THEN 4
        WHEN b.STATUS = 'REJECTED'                                         THEN 4
        WHEN b.STATUS = 'ON_HOLD'   AND b.DEVIATION_SEVERITY = 'MAJOR'    THEN 3
        WHEN b.STATUS = 'QC_REVIEW' AND b.QC_RESULT = 'FAIL'              THEN 3
        WHEN b.DEVIATION_COUNT > 0                                         THEN 1
        ELSE 0
    END) AS BATCH_SEVERITY,

    MAX(CASE
        WHEN mi.TEMP_EXCURSION_FLAG = TRUE  THEN 3
        ELSE 0
    END) AS TEMP_SEVERITY,

    MAX(CASE
        WHEN mi.STOCK_STATUS = 'CRITICAL' THEN 2
        WHEN mi.STOCK_STATUS = 'LOW'      THEN 1
        ELSE 0
    END) AS STOCK_SEVERITY,

    MAX(CASE
        WHEN sh.STATUS IN ('DELAYED', 'CUSTOMS') AND sh.DELAY_DAYS >= 7 THEN 2
        WHEN sh.STATUS IN ('DELAYED', 'CUSTOMS')                         THEN 1
        ELSE 0
    END) AS SHIPMENT_SEVERITY,

    GREATEST(
        MAX(CASE
            WHEN b.STATUS = 'ON_HOLD'   AND b.DEVIATION_SEVERITY = 'CRITICAL' THEN 4
            WHEN b.STATUS = 'REJECTED'                                         THEN 4
            WHEN b.STATUS = 'ON_HOLD'   AND b.DEVIATION_SEVERITY = 'MAJOR'    THEN 3
            WHEN b.STATUS = 'QC_REVIEW' AND b.QC_RESULT = 'FAIL'              THEN 3
            WHEN b.DEVIATION_COUNT > 0                                         THEN 1
            ELSE 0
        END),
        MAX(CASE WHEN mi.TEMP_EXCURSION_FLAG = TRUE THEN 3 ELSE 0 END),
        MAX(CASE WHEN mi.STOCK_STATUS = 'CRITICAL' THEN 2 WHEN mi.STOCK_STATUS = 'LOW' THEN 1 ELSE 0 END),
        MAX(CASE WHEN sh.STATUS IN ('DELAYED', 'CUSTOMS') AND sh.DELAY_DAYS >= 7 THEN 2
                 WHEN sh.STATUS IN ('DELAYED', 'CUSTOMS') THEN 1 ELSE 0 END)
    ) AS MAX_SEVERITY,

    COUNT(DISTINCT CASE WHEN b.STATUS IN ('ON_HOLD', 'REJECTED') THEN b.BATCH_ID END) AS CRITICAL_BATCHES,
    COUNT(DISTINCT CASE WHEN mi.TEMP_EXCURSION_FLAG = TRUE THEN mi.INVENTORY_ID END)   AS TEMP_EXCURSIONS,
    COUNT(DISTINCT CASE WHEN mi.STOCK_STATUS = 'CRITICAL'   THEN mi.INVENTORY_ID END)  AS CRITICAL_STOCK_ITEMS,
    COUNT(DISTINCT CASE WHEN sh.STATUS IN ('DELAYED', 'CUSTOMS') THEN sh.SHIPMENT_ID END) AS DELAYED_SHIPMENTS,
    COUNT(DISTINCT CASE WHEN b.STATUS = 'IN_PROGRESS' THEN b.BATCH_ID END)             AS BATCHES_IN_PROGRESS

FROM FLEET_INTELLIGENCE.PHARMA_SUPPLY_CHAIN.PLANTS pl
LEFT JOIN FLEET_INTELLIGENCE.PHARMA_SUPPLY_CHAIN.PRODUCTION_BATCHES b
    ON b.PLANT_ID = pl.PLANT_ID
LEFT JOIN FLEET_INTELLIGENCE.PHARMA_SUPPLY_CHAIN.MATERIAL_INVENTORY mi
    ON mi.PLANT_ID = pl.PLANT_ID
LEFT JOIN FLEET_INTELLIGENCE.PHARMA_SUPPLY_CHAIN.SHIPMENTS sh
    ON sh.PLANT_ID = pl.PLANT_ID
GROUP BY
    pl.PLANT_ID, pl.PLANT_NAME, pl.PLANT_CODE, pl.CITY, pl.COUNTRY,
    pl.REGION, pl.SPECIALISATION, pl.CAPACITY_BATCHES_MONTH,
    pl.LATITUDE, pl.LONGITUDE;

-- Verify alert status
SELECT PLANT_NAME, MAX_SEVERITY, CRITICAL_BATCHES, TEMP_EXCURSIONS,
       CRITICAL_STOCK_ITEMS, DELAYED_SHIPMENTS
FROM FLEET_INTELLIGENCE.PHARMA_SUPPLY_CHAIN.PLANT_ALERT_STATUS
ORDER BY MAX_SEVERITY DESC;

-- =============================================================================
-- 2. BUILDING FOOTPRINTS TABLE (requires OVERTURE_MAPS__BUILDINGS)
--    CTAS with per-plant UNION ALL subqueries. Each subquery uses a literal
--    ST_MAKEPOINT so the spatial index on BUILDING.GEOMETRY is utilised.
--    A VIEW with JOIN doesn't push the ST_DWITHIN predicate down and times out.
--    Total: ~12K buildings across 6 plants, executes in ~30s on LARGE WH.
--    Install from Marketplace: search "Overture Maps - Buildings" by CARTO.
--    Database name: OVERTURE_MAPS__BUILDINGS, schema: CARTO
-- =============================================================================

-- Accept terms and install listing (idempotent)
CALL SYSTEM$ACCEPT_LEGAL_TERMS('DATA_EXCHANGE_LISTING', 'GZT0Z4CM1E9KN');
CREATE DATABASE IF NOT EXISTS OVERTURE_MAPS__BUILDINGS FROM LISTING 'GZT0Z4CM1E9KN';

CREATE OR REPLACE TABLE FLEET_INTELLIGENCE.PHARMA_SUPPLY_CHAIN.PLANT_BUILDING_FOOTPRINTS
COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-add-plant-map","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT 1 AS PLANT_ID, 'Northshire Site' AS PLANT_NAME, 'MCF' AS PLANT_CODE, b.ID AS OVERTURE_ID, ST_ASGEOJSON(b.GEOMETRY) AS GEOJSON, TRY_PARSE_JSON(b.NAMES):primary::STRING AS BUILDING_NAME, b.CLASS, b.HEIGHT, 'BUILDING' AS FOOTPRINT_TYPE
FROM OVERTURE_MAPS__BUILDINGS.CARTO.BUILDING b WHERE ST_DWITHIN(b.GEOMETRY, ST_MAKEPOINT(-2.1236, 53.2583), 900) AND b.GEOMETRY IS NOT NULL
UNION ALL
SELECT 2, 'Hudson Valley Site', 'MVI', b.ID, ST_ASGEOJSON(b.GEOMETRY), TRY_PARSE_JSON(b.NAMES):primary::STRING, b.CLASS, b.HEIGHT, 'BUILDING'
FROM OVERTURE_MAPS__BUILDINGS.CARTO.BUILDING b WHERE ST_DWITHIN(b.GEOMETRY, ST_MAKEPOINT(-73.8370, 40.9126), 900) AND b.GEOMETRY IS NOT NULL
UNION ALL
SELECT 3, 'Nordic Biologics Site', 'SOD', b.ID, ST_ASGEOJSON(b.GEOMETRY), TRY_PARSE_JSON(b.NAMES):primary::STRING, b.CLASS, b.HEIGHT, 'BUILDING'
FROM OVERTURE_MAPS__BUILDINGS.CARTO.BUILDING b WHERE ST_DWITHIN(b.GEOMETRY, ST_MAKEPOINT(17.6253, 59.1955), 900) AND b.GEOMETRY IS NOT NULL
UNION ALL
SELECT 4, 'Asia Pacific Hub', 'SIN', b.ID, ST_ASGEOJSON(b.GEOMETRY), TRY_PARSE_JSON(b.NAMES):primary::STRING, b.CLASS, b.HEIGHT, 'BUILDING'
FROM OVERTURE_MAPS__BUILDINGS.CARTO.BUILDING b WHERE ST_DWITHIN(b.GEOMETRY, ST_MAKEPOINT(103.8198, 1.3521), 900) AND b.GEOMETRY IS NOT NULL
UNION ALL
SELECT 5, 'Dublin Biologics Site', 'DUN', b.ID, ST_ASGEOJSON(b.GEOMETRY), TRY_PARSE_JSON(b.NAMES):primary::STRING, b.CLASS, b.HEIGHT, 'BUILDING'
FROM OVERTURE_MAPS__BUILDINGS.CARTO.BUILDING b WHERE ST_DWITHIN(b.GEOMETRY, ST_MAKEPOINT(-6.4756, 53.4192), 900) AND b.GEOMETRY IS NOT NULL
UNION ALL
SELECT 6, 'South Plains Site', 'LUB', b.ID, ST_ASGEOJSON(b.GEOMETRY), TRY_PARSE_JSON(b.NAMES):primary::STRING, b.CLASS, b.HEIGHT, 'BUILDING'
FROM OVERTURE_MAPS__BUILDINGS.CARTO.BUILDING b WHERE ST_DWITHIN(b.GEOMETRY, ST_MAKEPOINT(-101.8552, 33.5779), 900) AND b.GEOMETRY IS NOT NULL;

-- Verify footprints
SELECT COUNT(*) AS building_footprint_rows,
       COUNT(DISTINCT PLANT_ID) AS plants_with_footprints
FROM FLEET_INTELLIGENCE.PHARMA_SUPPLY_CHAIN.PLANT_BUILDING_FOOTPRINTS;

-- ============================================================
-- PRIMARY BUILDING VIEW: largest building per plant
-- Used by the warehouse drill-down feature
-- ============================================================
CREATE OR REPLACE VIEW FLEET_INTELLIGENCE.PHARMA_SUPPLY_CHAIN.PLANT_PRIMARY_BUILDING AS
WITH RANKED AS (
  SELECT *,
    ROUND(ST_AREA(TO_GEOGRAPHY(GEOJSON::VARIANT::STRING)), 0) AS AREA_SQM,
    ROW_NUMBER() OVER (PARTITION BY PLANT_ID ORDER BY ST_AREA(TO_GEOGRAPHY(GEOJSON::VARIANT::STRING)) DESC) AS RNK
  FROM FLEET_INTELLIGENCE.PHARMA_SUPPLY_CHAIN.PLANT_BUILDING_FOOTPRINTS
  WHERE GEOJSON IS NOT NULL
)
SELECT PLANT_ID, PLANT_NAME, PLANT_CODE, OVERTURE_ID, GEOJSON, BUILDING_NAME, CLASS, HEIGHT, FOOTPRINT_TYPE, AREA_SQM
FROM RANKED WHERE RNK = 1;

SELECT COUNT(*) AS primary_building_rows FROM FLEET_INTELLIGENCE.PHARMA_SUPPLY_CHAIN.PLANT_PRIMARY_BUILDING;

-- ============================================================
-- CAMPUS BUILDINGS VIEW: top-6 buildings per plant (>=500 sqm)
-- Assigned pharma roles: API Mfg, Formulation, Cold Chain,
-- QC Lab, Central Utilities, Distribution & Dispatch
-- ============================================================
CREATE OR REPLACE VIEW FLEET_INTELLIGENCE.PHARMA_SUPPLY_CHAIN.PLANT_CAMPUS_BUILDINGS AS
WITH RANKED AS (
  SELECT *,
    ROUND(ST_AREA(TO_GEOGRAPHY(GEOJSON)), 0) AS AREA_SQM,
    ROW_NUMBER() OVER (PARTITION BY PLANT_ID ORDER BY ST_AREA(TO_GEOGRAPHY(GEOJSON)) DESC) AS RNK
  FROM FLEET_INTELLIGENCE.PHARMA_SUPPLY_CHAIN.PLANT_BUILDING_FOOTPRINTS
  WHERE GEOJSON IS NOT NULL
    AND ST_AREA(TO_GEOGRAPHY(GEOJSON)) >= 500
)
SELECT PLANT_ID, PLANT_NAME, PLANT_CODE, OVERTURE_ID, GEOJSON,
       BUILDING_NAME, CLASS, HEIGHT, FOOTPRINT_TYPE, AREA_SQM, RNK AS CAMPUS_RANK
FROM RANKED WHERE RNK <= 6;

SELECT COUNT(*) AS campus_building_rows,
       COUNT(DISTINCT PLANT_ID) AS plants_with_campus
FROM FLEET_INTELLIGENCE.PHARMA_SUPPLY_CHAIN.PLANT_CAMPUS_BUILDINGS;
