EXECUTE IMMEDIATE $$
DECLARE
  ddl STRING;
BEGIN
  EXECUTE IMMEDIATE 'USE SCHEMA FLEET_INTELLIGENCE.SEMANTIC';
  ddl := (SELECT GET_DDL('SEMANTIC_VIEW', 'FLEET_INTELLIGENCE.SEMANTIC.SV_ASSET_VELOCITY'));
  ddl := REPLACE(ddl, 'FLEET_APP.DWELL.VW_DWELL_SESSIONS', 'FLEET_APP.ROUTE_OPTIMIZATION.VW_DWELL_ENRICHED');
  ddl := REPLACE(ddl, 'SYNTHETIC_DATASETS.UNIFIED.V_DIM_FLEET_CURRENT', 'FLEET_APP.ROUTE_OPTIMIZATION.VW_FLEET_CURRENT');
  ddl := REPLACE(ddl, 'SYNTHETIC_DATASETS.UNIFIED.V_FACT_TRIPS_CURRENT', 'FLEET_APP.ROUTE_OPTIMIZATION.VW_TRIPS_CURRENT');
  ddl := REPLACE(ddl, 'SYNTHETIC_DATASETS.UNIFIED.V_DIM_POIS_CURRENT', 'FLEET_APP.ROUTE_OPTIMIZATION.VW_POIS_CURRENT');
  ddl := REPLACE(ddl, 'FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.CONFIG', 'FLEET_APP.ROUTE_OPTIMIZATION.VW_CONFIG');
  ddl := REPLACE(ddl, 'FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.VW_VEHICLE_COST_OF_IDLENESS', 'FLEET_APP.ROUTE_OPTIMIZATION.VW_VEHICLE_COST_OF_IDLENESS');
  ddl := REPLACE(ddl, 'FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.VW_LANE_DEMAND', 'FLEET_APP.ROUTE_OPTIMIZATION.VW_LANE_DEMAND');
  EXECUTE IMMEDIATE :ddl;
  RETURN 'repointed semantic views';
END;
$$;
