-- Fleet Intelligence — production role binding (Phase 3E).
-- Source of truth for the account-role grants applied on the provider account
-- (wgb26798). Creates the three app roles and grants least-privilege access per
-- bundle. Run as ACCOUNTADMIN (or a role with MANAGE GRANTS + ownership).
--
-- Role model:
--   FLEET_APP_USER  -> consumer: dashboards + FLEET_AGENT + Cortex Analyst (9 SVs) + FLEET_USER_MCP verbs
--   FLEET_APP_OPS   -> operator: FLEET_OPS_AGENT + FLEET_OPS_MCP (service lifecycle / region / health)
--   FLEET_APP_ADMIN -> installer: FLEET_ADMIN_MCP (substrate checks / region)
-- Hierarchy: ADMIN inherits OPS inherits USER.

CREATE ROLE IF NOT EXISTS FLEET_APP_USER;
CREATE ROLE IF NOT EXISTS FLEET_APP_OPS;
CREATE ROLE IF NOT EXISTS FLEET_APP_ADMIN;
GRANT ROLE FLEET_APP_USER TO ROLE FLEET_APP_OPS;
GRANT ROLE FLEET_APP_OPS  TO ROLE FLEET_APP_ADMIN;
GRANT ROLE FLEET_APP_USER TO ROLE SYSADMIN;
GRANT ROLE FLEET_APP_OPS  TO ROLE SYSADMIN;
GRANT ROLE FLEET_APP_ADMIN TO ROLE SYSADMIN;

-- Agent/Analyst calling requires CORTEX_USER.
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE FLEET_APP_USER;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE FLEET_APP_OPS;

-- Compute + database/schema usage (consumer).
GRANT USAGE ON WAREHOUSE MY_WH TO ROLE FLEET_APP_USER;
GRANT USAGE ON DATABASE FLEET_INTELLIGENCE TO ROLE FLEET_APP_USER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE FLEET_INTELLIGENCE TO ROLE FLEET_APP_USER;
GRANT USAGE ON DATABASE SYNTHETIC_DATASETS TO ROLE FLEET_APP_USER;
GRANT USAGE ON SCHEMA SYNTHETIC_DATASETS.UNIFIED TO ROLE FLEET_APP_USER;

-- Read access for Cortex Analyst (SV + underlying tables/views, incl. cross-DB fleet ops).
GRANT SELECT ON ALL SEMANTIC VIEWS IN SCHEMA FLEET_INTELLIGENCE.SEMANTIC TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA FLEET_INTELLIGENCE.DWELL_ANALYSIS TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL VIEWS  IN SCHEMA FLEET_INTELLIGENCE.DWELL_ANALYSIS TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA FLEET_INTELLIGENCE.ROUTE_DEVIATION TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL VIEWS  IN SCHEMA FLEET_INTELLIGENCE.ROUTE_DEVIATION TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL VIEWS  IN SCHEMA FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL VIEWS  IN SCHEMA FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL VIEWS  IN SCHEMA FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA FLEET_INTELLIGENCE.RETAIL_CATCHMENT TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL VIEWS  IN SCHEMA FLEET_INTELLIGENCE.RETAIL_CATCHMENT TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA FLEET_INTELLIGENCE.MARKETPLACE TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL VIEWS  IN SCHEMA FLEET_INTELLIGENCE.MARKETPLACE TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA FLEET_INTELLIGENCE.BACKLOAD_MATCHING TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL VIEWS  IN SCHEMA FLEET_INTELLIGENCE.BACKLOAD_MATCHING TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA FLEET_INTELLIGENCE.DHL_NTBO TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL VIEWS  IN SCHEMA FLEET_INTELLIGENCE.DHL_NTBO TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL VIEWS  IN SCHEMA SYNTHETIC_DATASETS.UNIFIED TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA SYNTHETIC_DATASETS.UNIFIED TO ROLE FLEET_APP_USER;

-- Consumer agent + User MCP + User verbs.
GRANT USAGE ON AGENT FLEET_INTELLIGENCE.SYNAPSE_USER.FLEET_AGENT TO ROLE FLEET_APP_USER;
GRANT USAGE ON MCP SERVER FLEET_INTELLIGENCE.SYNAPSE_USER.FLEET_USER_MCP TO ROLE FLEET_APP_USER;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA FLEET_INTELLIGENCE.SYNAPSE_USER TO ROLE FLEET_APP_USER;

-- Ops bundle (role-gated; NOT on the consumer agent).
GRANT USAGE ON SCHEMA FLEET_INTELLIGENCE.SYNAPSE_OPS TO ROLE FLEET_APP_OPS;
GRANT USAGE ON AGENT FLEET_INTELLIGENCE.SYNAPSE_OPS.FLEET_OPS_AGENT TO ROLE FLEET_APP_OPS;
GRANT USAGE ON MCP SERVER FLEET_INTELLIGENCE.SYNAPSE_OPS.FLEET_OPS_MCP TO ROLE FLEET_APP_OPS;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA FLEET_INTELLIGENCE.SYNAPSE_OPS TO ROLE FLEET_APP_OPS;

-- Admin bundle.
GRANT USAGE ON SCHEMA FLEET_INTELLIGENCE.SYNAPSE_ADMIN TO ROLE FLEET_APP_ADMIN;
GRANT USAGE ON MCP SERVER FLEET_INTELLIGENCE.SYNAPSE_ADMIN.FLEET_ADMIN_MCP TO ROLE FLEET_APP_ADMIN;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA FLEET_INTELLIGENCE.SYNAPSE_ADMIN TO ROLE FLEET_APP_ADMIN;

-- SPCS endpoint access: only these roles can open the app URL.
GRANT SERVICE ROLE FLEET_INTELLIGENCE.SYNAPSE_USER.FLEET_SA_APP!ALL_ENDPOINTS_USAGE TO ROLE FLEET_APP_USER;

-- Optional: bind to real users, e.g.
--   GRANT ROLE FLEET_APP_USER TO USER <consumer_user>;
--   GRANT ROLE FLEET_APP_OPS  TO USER <operator_user>;
