-- Fleet Intelligence — production role binding (Phase 3E).
-- Source of truth for the account-role grants applied on the provider account
-- (wgb26798). Creates the three app roles and grants least-privilege access per
-- bundle. Run as ACCOUNTADMIN (or a role with MANAGE GRANTS + ownership).
--
-- Role model:
--   FLEET_APP_USER  -> consumer: dashboards + FLEET_AGENT + Cortex Analyst (10 SVs) + ROUTING_MCP verbs (OPENROUTESERVICE_APP.ROUTING)
--   FLEET_APP_OPS   -> operator: FLEET_OPS_AGENT + FLEET_OPS_MCP (service lifecycle / region / health)
--   FLEET_APP_ADMIN -> installer: FLEET_ADMIN_MCP (substrate checks / region)
-- Hierarchy: ADMIN inherits OPS inherits USER.

CREATE ROLE IF NOT EXISTS FLEET_APP_USER;
CREATE ROLE IF NOT EXISTS FLEET_APP_OPS;
CREATE ROLE IF NOT EXISTS FLEET_APP_ADMIN;
GRANT ROLE FLEET_APP_USER TO ROLE FLEET_APP_OPS;
GRANT ROLE FLEET_APP_OPS  TO ROLE FLEET_APP_ADMIN;
GRANT ROLE FLEET_APP_USER TO ROLE SYSADMIN;
GRANT ROLE FLEET_APP_OPS  TO ROLE SYSADMIN;
GRANT ROLE FLEET_APP_ADMIN TO ROLE SYSADMIN;

-- Agent/Analyst calling requires CORTEX_USER.
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE FLEET_APP_USER;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE FLEET_APP_OPS;

-- Compute + database/schema usage (consumer).
GRANT USAGE ON WAREHOUSE MY_WH TO ROLE FLEET_APP_USER;
GRANT USAGE ON DATABASE FLEET_INTELLIGENCE TO ROLE FLEET_APP_USER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE FLEET_INTELLIGENCE TO ROLE FLEET_APP_USER;
GRANT USAGE ON DATABASE SYNTHETIC_DATASETS TO ROLE FLEET_APP_USER;
GRANT USAGE ON SCHEMA SYNTHETIC_DATASETS.UNIFIED TO ROLE FLEET_APP_USER;

-- Read access for Cortex Analyst (SV + underlying tables/views, incl. cross-DB fleet ops).
GRANT SELECT ON ALL SEMANTIC VIEWS IN SCHEMA FLEET_INTELLIGENCE.SEMANTIC TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA FLEET_INTELLIGENCE.DWELL_ANALYSIS TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL VIEWS  IN SCHEMA FLEET_INTELLIGENCE.DWELL_ANALYSIS TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA FLEET_INTELLIGENCE.ROUTE_DEVIATION TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL VIEWS  IN SCHEMA FLEET_INTELLIGENCE.ROUTE_DEVIATION TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL VIEWS  IN SCHEMA FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL VIEWS  IN SCHEMA FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_TAXIS TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL VIEWS  IN SCHEMA FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA FLEET_INTELLIGENCE.CATCHMENT TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL VIEWS  IN SCHEMA FLEET_INTELLIGENCE.CATCHMENT TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA FLEET_INTELLIGENCE.MARKETPLACE TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL VIEWS  IN SCHEMA FLEET_INTELLIGENCE.MARKETPLACE TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA FLEET_INTELLIGENCE.BACKLOAD_MATCHING TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL VIEWS  IN SCHEMA FLEET_INTELLIGENCE.BACKLOAD_MATCHING TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA FLEET_INTELLIGENCE.DHL_NTBO TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL VIEWS  IN SCHEMA FLEET_INTELLIGENCE.DHL_NTBO TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL VIEWS  IN SCHEMA SYNTHETIC_DATASETS.UNIFIED TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA SYNTHETIC_DATASETS.UNIFIED TO ROLE FLEET_APP_USER;

-- Consumer agent + routing MCP + routing verbs (Step 4B: relocated to the
-- Routing Platform schema OPENROUTESERVICE_APP.ROUTING; ROUTING_MCP replaces the
-- retired FLEET_USER_MCP).
GRANT USAGE ON AGENT FLEET_INTELLIGENCE.SYNAPSE_USER.FLEET_AGENT TO ROLE FLEET_APP_USER;
GRANT USAGE ON DATABASE OPENROUTESERVICE_APP TO ROLE FLEET_APP_USER;
GRANT USAGE ON SCHEMA OPENROUTESERVICE_APP.ROUTING TO ROLE FLEET_APP_USER;
GRANT USAGE ON MCP SERVER OPENROUTESERVICE_APP.ROUTING.ROUTING_MCP TO ROLE FLEET_APP_USER;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA OPENROUTESERVICE_APP.ROUTING TO ROLE FLEET_APP_USER;

-- Engine-agnostic Routing Platform (Step 4B.2). Consumers depend on
-- ROUTING_PLATFORM.CONTRACT.*; OPENROUTESERVICE_APP is the ORS provider impl.
-- The TOOL_* procs (EXECUTE AS OWNER) route through CONTRACT, so the consumer
-- role does not strictly need CONTRACT execute, but we grant it for direct/
-- least-privilege use and expose the neutral region inventory view.
-- Full DDL source of truth: .cortex/skills/build-routing-solution/routing_platform/setup.sql
GRANT USAGE ON DATABASE ROUTING_PLATFORM TO ROLE FLEET_APP_USER;
GRANT USAGE ON SCHEMA ROUTING_PLATFORM.CONTRACT TO ROLE FLEET_APP_USER;
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA ROUTING_PLATFORM.CONTRACT TO ROLE FLEET_APP_USER;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA ROUTING_PLATFORM.CONTRACT TO ROLE FLEET_APP_USER;
GRANT USAGE ON SCHEMA ROUTING_PLATFORM.ADMIN TO ROLE FLEET_APP_USER;
GRANT SELECT ON VIEW ROUTING_PLATFORM.ADMIN.V_REGIONS TO ROLE FLEET_APP_USER;
-- Ops/Admin: provider registry visibility + region->provider steering.
GRANT USAGE ON SCHEMA ROUTING_PLATFORM.PROVIDERS TO ROLE FLEET_APP_OPS;
GRANT SELECT ON ALL TABLES IN SCHEMA ROUTING_PLATFORM.PROVIDERS TO ROLE FLEET_APP_OPS;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ROUTING_PLATFORM.ADMIN TO ROLE FLEET_APP_ADMIN;
GRANT USAGE ON PROCEDURE ROUTING_PLATFORM.ADMIN.SET_REGION_PROVIDER(VARCHAR, VARCHAR) TO ROLE FLEET_APP_OPS;

-- Data-contract app layer (FLEET_APP): neutral logical views that all dashboards
-- and semantic views bind to (per-domain packs under fleet_sa_app/app/packs/fleet/*).
-- Database-level + FUTURE grants so new packs are covered without re-granting.
-- DDL source of truth: each pack's generated setup.sql (packs/_lib/generate.py).
GRANT USAGE ON DATABASE FLEET_APP TO ROLE FLEET_APP_USER;
GRANT USAGE ON DATABASE FLEET_APP TO ROLE FLEET_APP_OPS;
GRANT USAGE ON DATABASE FLEET_APP TO ROLE FLEET_APP_ADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE FLEET_APP TO ROLE FLEET_APP_USER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE FLEET_APP TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL VIEWS IN DATABASE FLEET_APP TO ROLE FLEET_APP_USER;
GRANT SELECT ON FUTURE VIEWS IN DATABASE FLEET_APP TO ROLE FLEET_APP_USER;
GRANT SELECT ON ALL DYNAMIC TABLES IN DATABASE FLEET_APP TO ROLE FLEET_APP_USER;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN DATABASE FLEET_APP TO ROLE FLEET_APP_USER;

-- Ops bundle (role-gated; NOT on the consumer agent).
GRANT USAGE ON SCHEMA FLEET_INTELLIGENCE.SYNAPSE_OPS TO ROLE FLEET_APP_OPS;
GRANT USAGE ON AGENT FLEET_INTELLIGENCE.SYNAPSE_OPS.FLEET_OPS_AGENT TO ROLE FLEET_APP_OPS;
GRANT USAGE ON MCP SERVER FLEET_INTELLIGENCE.SYNAPSE_OPS.FLEET_OPS_MCP TO ROLE FLEET_APP_OPS;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA FLEET_INTELLIGENCE.SYNAPSE_OPS TO ROLE FLEET_APP_OPS;

-- Admin bundle.
GRANT USAGE ON SCHEMA FLEET_INTELLIGENCE.SYNAPSE_ADMIN TO ROLE FLEET_APP_ADMIN;
GRANT USAGE ON MCP SERVER FLEET_INTELLIGENCE.SYNAPSE_ADMIN.FLEET_ADMIN_MCP TO ROLE FLEET_APP_ADMIN;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA FLEET_INTELLIGENCE.SYNAPSE_ADMIN TO ROLE FLEET_APP_ADMIN;

-- SPCS endpoint access: only these roles can open the app URL.
GRANT SERVICE ROLE FLEET_INTELLIGENCE.SYNAPSE_USER.FLEET_SA_APP!ALL_ENDPOINTS_USAGE TO ROLE FLEET_APP_USER;

-- Optional: bind to real users, e.g.
--   GRANT ROLE FLEET_APP_USER TO USER <consumer_user>;
--   GRANT ROLE FLEET_APP_OPS  TO USER <operator_user>;
