-- ============================================================================
-- Per-session scope-arg data contract (R2.1 of APP_RESTRUCTURE_PLAN)
-- ============================================================================
-- Multi-tenant-safe READ layer. Today the consumer app reads
-- SYNTHETIC_DATASETS.UNIFIED.V_*_CURRENT, which resolve the active dataset via a
-- GLOBAL flag (FLEET_INTELLIGENCE.CORE.DIM_DATASETS.IS_ACTIVE = TRUE). In a shared
-- consumer app that means one user's "switch" changes everyone's view.
--
-- These table functions resolve an EXPLICIT (region, dataset_id) instead, so each
-- session passes its own scope and sees isolated data. They are ADDITIVE: the
-- V_*_CURRENT views remain unchanged for the global default + surfacing-gate probes.
--
-- Contract:
--   F_<TABLE>_SCOPED(P_REGION, P_DATASET_ID)
--     - P_DATASET_ID given  -> rows for exactly that immutable dataset (per-session).
--     - P_DATASET_ID NULL   -> falls back to the region's ACTIVE dataset (back-compat
--                              with current V_*_CURRENT behavior), region-filtered.
--     - P_REGION NULL        -> no region guard (dataset_id alone pins region+vehicle).
--
-- Call site (consumer /api/query, SELECT-only, :param):
--   SELECT * FROM TABLE(SYNTHETIC_DATASETS.UNIFIED.F_FACT_TRIPS_SCOPED(:region, :dataset_id))
--
-- Source of truth: this file. Also mirrored into the control-app boot path
-- (server/lib/init.ts ensureScopedDatasetContract()) so a fresh install creates them.
--
-- Tracking: query_tag set by caller; each function carries the COMMENT tag.
-- ============================================================================

ALTER SESSION SET query_tag = '{"origin":"sf_sit-is-fleet","name":"oss-app-restructure","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';

-- ---------------------------------------------------------------------------
-- FACT_TRIPS (region + vehicle scoped)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION SYNTHETIC_DATASETS.UNIFIED.F_FACT_TRIPS_SCOPED(P_REGION VARCHAR, P_DATASET_ID VARCHAR)
RETURNS TABLE (
  TRIP_ID VARCHAR, VEHICLE_ID VARCHAR, DRIVER_ID VARCHAR, VEHICLE_TYPE VARCHAR, REGION VARCHAR,
  ORIGIN_POI_ID VARCHAR, DESTINATION_POI_ID VARCHAR, ORIGIN_LAT FLOAT, ORIGIN_LON FLOAT, ORIGIN GEOGRAPHY,
  DESTINATION_LAT FLOAT, DESTINATION_LON FLOAT, DESTINATION GEOGRAPHY, ROUTE_GEOG GEOGRAPHY,
  DISTANCE_KM FLOAT, DURATION_MINUTES FLOAT, PLANNED_ROUTE_GEOG GEOGRAPHY, PLANNED_DISTANCE_KM FLOAT,
  IS_DETOUR BOOLEAN, DETOUR_DISTANCE_KM FLOAT, TRIP_START TIMESTAMP_NTZ, TRIP_END TIMESTAMP_NTZ,
  STATUS VARCHAR, ORS_PROFILE VARCHAR, JOB_ID VARCHAR
)
COMMENT='{"origin":"sf_sit-is-fleet","name":"oss-app-restructure","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
$$
  SELECT t.TRIP_ID, t.VEHICLE_ID, t.DRIVER_ID, t.VEHICLE_TYPE, t.REGION,
         t.ORIGIN_POI_ID, t.DESTINATION_POI_ID, t.ORIGIN_LAT, t.ORIGIN_LON, t.ORIGIN,
         t.DESTINATION_LAT, t.DESTINATION_LON, t.DESTINATION, t.ROUTE_GEOG,
         t.DISTANCE_KM, t.DURATION_MINUTES, t.PLANNED_ROUTE_GEOG, t.PLANNED_DISTANCE_KM,
         t.IS_DETOUR, t.DETOUR_DISTANCE_KM, t.TRIP_START, t.TRIP_END,
         t.STATUS, t.ORS_PROFILE, t.JOB_ID
  FROM SYNTHETIC_DATASETS.UNIFIED.FACT_TRIPS t
  JOIN FLEET_INTELLIGENCE.CORE.DIM_DATASETS d
    ON d.DATASET_ID = t.JOB_ID AND d.REGION = t.REGION AND d.VEHICLE_TYPE = t.VEHICLE_TYPE
  WHERE (P_REGION IS NULL OR t.REGION = P_REGION)
    AND ( (P_DATASET_ID IS NOT NULL AND d.DATASET_ID = P_DATASET_ID)
          OR (P_DATASET_ID IS NULL AND d.IS_ACTIVE = TRUE) )
$$;

-- ---------------------------------------------------------------------------
-- FACT_VEHICLE_TELEMETRY (region + vehicle scoped)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION SYNTHETIC_DATASETS.UNIFIED.F_FACT_VEHICLE_TELEMETRY_SCOPED(P_REGION VARCHAR, P_DATASET_ID VARCHAR)
RETURNS TABLE (
  TELEMETRY_ID VARCHAR, REGION VARCHAR, VEHICLE_TYPE VARCHAR, VEHICLE_ID VARCHAR, TRIP_ID VARCHAR,
  TS TIMESTAMP_NTZ, LATITUDE FLOAT, LONGITUDE FLOAT, POINT_GEOM GEOGRAPHY, SPEED_KMH FLOAT,
  HEADING_DEG FLOAT, POSTED_SPEED_KMH FLOAT, STATUS VARCHAR, IS_SPEEDING BOOLEAN, IS_HOS_VIOLATION BOOLEAN,
  IS_DETOUR BOOLEAN, GPS_ACCURACY_M FLOAT, LOCATION_ID VARCHAR, LOCATION_TYPE VARCHAR, ORS_PROFILE VARCHAR,
  BATTERY_PCT FLOAT, ODOMETER_KM FLOAT, POINT_INDEX NUMBER, JOB_ID VARCHAR
)
COMMENT='{"origin":"sf_sit-is-fleet","name":"oss-app-restructure","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
$$
  SELECT t.TELEMETRY_ID, t.REGION, t.VEHICLE_TYPE, t.VEHICLE_ID, t.TRIP_ID,
         t.TS, t.LATITUDE, t.LONGITUDE, t.POINT_GEOM, t.SPEED_KMH,
         t.HEADING_DEG, t.POSTED_SPEED_KMH, t.STATUS, t.IS_SPEEDING, t.IS_HOS_VIOLATION,
         t.IS_DETOUR, t.GPS_ACCURACY_M, t.LOCATION_ID, t.LOCATION_TYPE, t.ORS_PROFILE,
         t.BATTERY_PCT, t.ODOMETER_KM, t.POINT_INDEX, t.JOB_ID
  FROM SYNTHETIC_DATASETS.UNIFIED.FACT_VEHICLE_TELEMETRY t
  JOIN FLEET_INTELLIGENCE.CORE.DIM_DATASETS d
    ON d.DATASET_ID = t.JOB_ID AND d.REGION = t.REGION AND d.VEHICLE_TYPE = t.VEHICLE_TYPE
  WHERE (P_REGION IS NULL OR t.REGION = P_REGION)
    AND ( (P_DATASET_ID IS NOT NULL AND d.DATASET_ID = P_DATASET_ID)
          OR (P_DATASET_ID IS NULL AND d.IS_ACTIVE = TRUE) )
$$;

-- ---------------------------------------------------------------------------
-- DIM_POIS (region scoped only -- no VEHICLE_TYPE column / join)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION SYNTHETIC_DATASETS.UNIFIED.F_DIM_POIS_SCOPED(P_REGION VARCHAR, P_DATASET_ID VARCHAR)
RETURNS TABLE (
  LOCATION_ID VARCHAR, REGION VARCHAR, NAME VARCHAR, LOCATION_TYPE VARCHAR, CATEGORY VARCHAR,
  LAT FLOAT, LNG FLOAT, POINT_GEOM GEOGRAPHY, SOURCE VARCHAR, JOB_ID VARCHAR
)
COMMENT='{"origin":"sf_sit-is-fleet","name":"oss-app-restructure","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
$$
  SELECT p.LOCATION_ID, p.REGION, p.NAME, p.LOCATION_TYPE, p.CATEGORY,
         p.LAT, p.LNG, p.POINT_GEOM, p.SOURCE, p.JOB_ID
  FROM SYNTHETIC_DATASETS.UNIFIED.DIM_POIS p
  JOIN FLEET_INTELLIGENCE.CORE.DIM_DATASETS d
    ON d.DATASET_ID = p.JOB_ID AND d.REGION = p.REGION
  WHERE (P_REGION IS NULL OR p.REGION = P_REGION)
    AND ( (P_DATASET_ID IS NOT NULL AND d.DATASET_ID = P_DATASET_ID)
          OR (P_DATASET_ID IS NULL AND d.IS_ACTIVE = TRUE) )
$$;

-- ---------------------------------------------------------------------------
-- DIM_FLEET (region + vehicle scoped). NOTE: live column order skips dropped
-- ordinals 14-16; HGV columns (17-23) come AFTER JOB_ID (13). Explicit column
-- list below matches the live table order exactly.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION SYNTHETIC_DATASETS.UNIFIED.F_DIM_FLEET_SCOPED(P_REGION VARCHAR, P_DATASET_ID VARCHAR)
RETURNS TABLE (
  VEHICLE_ID VARCHAR, REGION VARCHAR, VEHICLE_TYPE VARCHAR, ORS_PROFILE VARCHAR, SHIFT_TYPE VARCHAR,
  SHIFT_START_HOUR NUMBER, SHIFT_END_HOUR NUMBER, HOME_LOCATION_ID VARCHAR, DRIVER_PROFILE VARCHAR,
  OPERATING_MODE VARCHAR, BASE_SPEED_KMH FLOAT, BATTERY_RANGE_KM FLOAT, JOB_ID VARCHAR,
  WEIGHT_TONS NUMBER, HEIGHT_M NUMBER, LENGTH_M NUMBER, WIDTH_M NUMBER, AXLELOAD_T NUMBER,
  HAZMAT BOOLEAN, VEHICLE_SUBTYPE VARCHAR
)
COMMENT='{"origin":"sf_sit-is-fleet","name":"oss-app-restructure","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
$$
  SELECT f.VEHICLE_ID, f.REGION, f.VEHICLE_TYPE, f.ORS_PROFILE, f.SHIFT_TYPE,
         f.SHIFT_START_HOUR, f.SHIFT_END_HOUR, f.HOME_LOCATION_ID, f.DRIVER_PROFILE,
         f.OPERATING_MODE, f.BASE_SPEED_KMH, f.BATTERY_RANGE_KM, f.JOB_ID,
         f.WEIGHT_TONS, f.HEIGHT_M, f.LENGTH_M, f.WIDTH_M, f.AXLELOAD_T,
         f.HAZMAT, f.VEHICLE_SUBTYPE
  FROM SYNTHETIC_DATASETS.UNIFIED.DIM_FLEET f
  JOIN FLEET_INTELLIGENCE.CORE.DIM_DATASETS d
    ON d.DATASET_ID = f.JOB_ID AND d.REGION = f.REGION AND d.VEHICLE_TYPE = f.VEHICLE_TYPE
  WHERE (P_REGION IS NULL OR f.REGION = P_REGION)
    AND ( (P_DATASET_ID IS NOT NULL AND d.DATASET_ID = P_DATASET_ID)
          OR (P_DATASET_ID IS NULL AND d.IS_ACTIVE = TRUE) )
$$;

-- ============================================================================
-- Contract-layer scope-arg functions (FLEET_APP.* neutral data contract)
-- ============================================================================
-- The consumer app binds to the NEUTRAL FLEET_APP contract, never to the physical
-- SYNTHETIC_DATASETS source (repo tenet: swappable data seam). The contract views
-- VW_FACT_TRIPS / VW_FACT_VEHICLE_TELEMETRY thinly wrap the global-active
-- V_*_CURRENT views. These contract-layer table functions are the per-session
-- equivalents: they wrap the UNIFIED F_*_SCOPED functions above, so dashboards get
-- per-session scoping WITHOUT reaching past the contract into the physical source.
--
-- Consumer call site:
--   SELECT * FROM TABLE(FLEET_APP.UNIFIED_FLEET.F_VW_FACT_TRIPS_SCOPED(:region, :dataset_id))
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION FLEET_APP.UNIFIED_FLEET.F_VW_FACT_TRIPS_SCOPED(P_REGION VARCHAR, P_DATASET_ID VARCHAR)
RETURNS TABLE (
  TRIP_ID VARCHAR, VEHICLE_ID VARCHAR, DRIVER_ID VARCHAR, VEHICLE_TYPE VARCHAR, REGION VARCHAR,
  ORIGIN_POI_ID VARCHAR, DESTINATION_POI_ID VARCHAR, ORIGIN_LAT FLOAT, ORIGIN_LON FLOAT, ORIGIN GEOGRAPHY,
  DESTINATION_LAT FLOAT, DESTINATION_LON FLOAT, DESTINATION GEOGRAPHY, ROUTE_GEOG GEOGRAPHY,
  DISTANCE_KM FLOAT, DURATION_MINUTES FLOAT, PLANNED_ROUTE_GEOG GEOGRAPHY, PLANNED_DISTANCE_KM FLOAT,
  IS_DETOUR BOOLEAN, DETOUR_DISTANCE_KM FLOAT, TRIP_START TIMESTAMP_NTZ, TRIP_END TIMESTAMP_NTZ,
  STATUS VARCHAR, ORS_PROFILE VARCHAR, JOB_ID VARCHAR
)
COMMENT='{"origin":"sf_sit-is-fleet","name":"oss-app-restructure","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
$$
  SELECT * FROM TABLE(SYNTHETIC_DATASETS.UNIFIED.F_FACT_TRIPS_SCOPED(P_REGION, P_DATASET_ID))
$$;

CREATE OR REPLACE FUNCTION FLEET_APP.UNIFIED_FLEET.F_VW_FACT_VEHICLE_TELEMETRY_SCOPED(P_REGION VARCHAR, P_DATASET_ID VARCHAR)
RETURNS TABLE (
  TELEMETRY_ID VARCHAR, REGION VARCHAR, VEHICLE_TYPE VARCHAR, VEHICLE_ID VARCHAR, TRIP_ID VARCHAR,
  TS TIMESTAMP_NTZ, LATITUDE FLOAT, LONGITUDE FLOAT, POINT_GEOM GEOGRAPHY, SPEED_KMH FLOAT,
  HEADING_DEG FLOAT, POSTED_SPEED_KMH FLOAT, STATUS VARCHAR, IS_SPEEDING BOOLEAN, IS_HOS_VIOLATION BOOLEAN,
  IS_DETOUR BOOLEAN, GPS_ACCURACY_M FLOAT, LOCATION_ID VARCHAR, LOCATION_TYPE VARCHAR, ORS_PROFILE VARCHAR,
  BATTERY_PCT FLOAT, ODOMETER_KM FLOAT, POINT_INDEX NUMBER, JOB_ID VARCHAR
)
COMMENT='{"origin":"sf_sit-is-fleet","name":"oss-app-restructure","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
$$
  SELECT * FROM TABLE(SYNTHETIC_DATASETS.UNIFIED.F_FACT_VEHICLE_TELEMETRY_SCOPED(P_REGION, P_DATASET_ID))
$$;

-- ---------------------------------------------------------------------------
-- Grants: the consumer (and OPS/ADMIN) call the contract-layer scope-arg
-- functions through the NEUTRAL FLEET_APP contract. These are owner's-rights
-- SQL UDTFs, so USAGE on the outer function is sufficient -- the inner call into
-- SYNTHETIC_DATASETS.UNIFIED.F_*_SCOPED runs as the function owner. Roles from
-- fleet_sa_app/app/role_binding.sql. Idempotent (re-granting is a no-op).
-- ---------------------------------------------------------------------------
GRANT USAGE ON FUNCTION FLEET_APP.UNIFIED_FLEET.F_VW_FACT_TRIPS_SCOPED(VARCHAR, VARCHAR) TO ROLE FLEET_APP_USER;
GRANT USAGE ON FUNCTION FLEET_APP.UNIFIED_FLEET.F_VW_FACT_TRIPS_SCOPED(VARCHAR, VARCHAR) TO ROLE FLEET_APP_OPS;
GRANT USAGE ON FUNCTION FLEET_APP.UNIFIED_FLEET.F_VW_FACT_TRIPS_SCOPED(VARCHAR, VARCHAR) TO ROLE FLEET_APP_ADMIN;
GRANT USAGE ON FUNCTION FLEET_APP.UNIFIED_FLEET.F_VW_FACT_VEHICLE_TELEMETRY_SCOPED(VARCHAR, VARCHAR) TO ROLE FLEET_APP_USER;
GRANT USAGE ON FUNCTION FLEET_APP.UNIFIED_FLEET.F_VW_FACT_VEHICLE_TELEMETRY_SCOPED(VARCHAR, VARCHAR) TO ROLE FLEET_APP_OPS;
GRANT USAGE ON FUNCTION FLEET_APP.UNIFIED_FLEET.F_VW_FACT_VEHICLE_TELEMETRY_SCOPED(VARCHAR, VARCHAR) TO ROLE FLEET_APP_ADMIN;

-- ---------------------------------------------------------------------------
-- Neutral contract wrappers for POIS + FLEET (consumed by FLEET_OPS intents).
-- Same pattern as the TRIPS/TELEMETRY wrappers above: the FLEET_OPS layer binds
-- to these FLEET_APP.* contract functions, never to SYNTHETIC_DATASETS directly.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION FLEET_APP.UNIFIED_FLEET.F_VW_DIM_POIS_SCOPED(P_REGION VARCHAR, P_DATASET_ID VARCHAR)
RETURNS TABLE (
  LOCATION_ID VARCHAR, REGION VARCHAR, NAME VARCHAR, LOCATION_TYPE VARCHAR, CATEGORY VARCHAR,
  LAT FLOAT, LNG FLOAT, POINT_GEOM GEOGRAPHY, SOURCE VARCHAR, JOB_ID VARCHAR
)
COMMENT='{"origin":"sf_sit-is-fleet","name":"oss-app-restructure","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
$$
  SELECT * FROM TABLE(SYNTHETIC_DATASETS.UNIFIED.F_DIM_POIS_SCOPED(P_REGION, P_DATASET_ID))
$$;

CREATE OR REPLACE FUNCTION FLEET_APP.UNIFIED_FLEET.F_VW_DIM_FLEET_SCOPED(P_REGION VARCHAR, P_DATASET_ID VARCHAR)
RETURNS TABLE (
  VEHICLE_ID VARCHAR, REGION VARCHAR, VEHICLE_TYPE VARCHAR, ORS_PROFILE VARCHAR, SHIFT_TYPE VARCHAR,
  SHIFT_START_HOUR NUMBER, SHIFT_END_HOUR NUMBER, HOME_LOCATION_ID VARCHAR, DRIVER_PROFILE VARCHAR,
  OPERATING_MODE VARCHAR, BASE_SPEED_KMH FLOAT, BATTERY_RANGE_KM FLOAT, JOB_ID VARCHAR,
  WEIGHT_TONS NUMBER, HEIGHT_M NUMBER, LENGTH_M NUMBER, WIDTH_M NUMBER, AXLELOAD_T NUMBER,
  HAZMAT BOOLEAN, VEHICLE_SUBTYPE VARCHAR
)
COMMENT='{"origin":"sf_sit-is-fleet","name":"oss-app-restructure","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
$$
  SELECT * FROM TABLE(SYNTHETIC_DATASETS.UNIFIED.F_DIM_FLEET_SCOPED(P_REGION, P_DATASET_ID))
$$;

GRANT USAGE ON FUNCTION FLEET_APP.UNIFIED_FLEET.F_VW_DIM_POIS_SCOPED(VARCHAR, VARCHAR) TO ROLE FLEET_APP_USER;
GRANT USAGE ON FUNCTION FLEET_APP.UNIFIED_FLEET.F_VW_DIM_POIS_SCOPED(VARCHAR, VARCHAR) TO ROLE FLEET_APP_OPS;
GRANT USAGE ON FUNCTION FLEET_APP.UNIFIED_FLEET.F_VW_DIM_POIS_SCOPED(VARCHAR, VARCHAR) TO ROLE FLEET_APP_ADMIN;
GRANT USAGE ON FUNCTION FLEET_APP.UNIFIED_FLEET.F_VW_DIM_FLEET_SCOPED(VARCHAR, VARCHAR) TO ROLE FLEET_APP_USER;
GRANT USAGE ON FUNCTION FLEET_APP.UNIFIED_FLEET.F_VW_DIM_FLEET_SCOPED(VARCHAR, VARCHAR) TO ROLE FLEET_APP_OPS;
GRANT USAGE ON FUNCTION FLEET_APP.UNIFIED_FLEET.F_VW_DIM_FLEET_SCOPED(VARCHAR, VARCHAR) TO ROLE FLEET_APP_ADMIN;

-- ============================================================================
-- FLEET_OPS — the ONE universal, mode-agnostic analytics layer (R6)
-- ============================================================================
-- A single schema of dataset-scoped UDTFs powering every fleet analytics INTENT
-- (Fleet/Asset Status, Asset Map, Demand Density, Trip Inspection, Operator
-- Performance, Top Origins, Asset Utilization). VEHICLE_TYPE is a DATA DIMENSION
-- carried by the selected dataset (DATASET_ID keys DIM_DATASETS by region+vehicle),
-- so dataset-scoping IS mode-parameterization. These functions:
--   * bind ONLY to the neutral FLEET_APP.UNIFIED_FLEET.F_VW_*_SCOPED contract,
--   * use mode-neutral vocab (OPERATOR_ID, ORIGIN_POI, ASSET attributes),
--   * NEVER branch on VEHICLE_TYPE (no CASE WHEN vehicle_type=...).
-- Adding a new mode (vessel/aircraft) = a new dataset + config; NO new schema/view.
-- Authored here; mirrored into the control-app boot (init.ts ensureScopedDatasetContract).
-- See app/packs/BUSINESS_PROBLEM_TAXONOMY.md.
-- ============================================================================
CREATE SCHEMA IF NOT EXISTS FLEET_APP.FLEET_OPS
  COMMENT='{"origin":"sf_sit-is-fleet","name":"oss-app-restructure","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql","component":"fleet-ops-universal-analytics"}}';

-- Base trips (mode-neutral: DRIVER_ID -> OPERATOR_ID). Powers Status / Map / Density.
CREATE OR REPLACE FUNCTION FLEET_APP.FLEET_OPS.F_VW_TRIPS_SCOPED(P_REGION VARCHAR, P_DATASET_ID VARCHAR)
RETURNS TABLE (
  TRIP_ID VARCHAR, VEHICLE_ID VARCHAR, OPERATOR_ID VARCHAR, VEHICLE_TYPE VARCHAR, REGION VARCHAR,
  ORIGIN_POI_ID VARCHAR, DESTINATION_POI_ID VARCHAR, ORIGIN_LAT FLOAT, ORIGIN_LON FLOAT, ORIGIN GEOGRAPHY,
  DESTINATION_LAT FLOAT, DESTINATION_LON FLOAT, DESTINATION GEOGRAPHY, ROUTE_GEOG GEOGRAPHY,
  DISTANCE_KM FLOAT, DURATION_MINUTES FLOAT, IS_DETOUR BOOLEAN, TRIP_START TIMESTAMP_NTZ,
  TRIP_END TIMESTAMP_NTZ, STATUS VARCHAR, JOB_ID VARCHAR
)
COMMENT='{"origin":"sf_sit-is-fleet","name":"oss-app-restructure","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
$$
  SELECT TRIP_ID, VEHICLE_ID, DRIVER_ID AS OPERATOR_ID, VEHICLE_TYPE, REGION,
         ORIGIN_POI_ID, DESTINATION_POI_ID, ORIGIN_LAT, ORIGIN_LON, ORIGIN,
         DESTINATION_LAT, DESTINATION_LON, DESTINATION, ROUTE_GEOG,
         DISTANCE_KM, DURATION_MINUTES, IS_DETOUR, TRIP_START, TRIP_END, STATUS, JOB_ID
  FROM TABLE(FLEET_APP.UNIFIED_FLEET.F_VW_FACT_TRIPS_SCOPED(P_REGION, P_DATASET_ID))
$$;

-- Base telemetry (GPS pings + safety flags). Powers Status (safety) / Map / Density.
CREATE OR REPLACE FUNCTION FLEET_APP.FLEET_OPS.F_VW_TELEMETRY_SCOPED(P_REGION VARCHAR, P_DATASET_ID VARCHAR)
RETURNS TABLE (
  TELEMETRY_ID VARCHAR, REGION VARCHAR, VEHICLE_TYPE VARCHAR, VEHICLE_ID VARCHAR, OPERATOR_ID VARCHAR,
  TRIP_ID VARCHAR, TS TIMESTAMP_NTZ, LATITUDE FLOAT, LONGITUDE FLOAT, POINT_GEOM GEOGRAPHY,
  SPEED_KMH FLOAT, HEADING_DEG FLOAT, POSTED_SPEED_KMH FLOAT, STATUS VARCHAR, IS_SPEEDING BOOLEAN,
  IS_HOS_VIOLATION BOOLEAN, IS_DETOUR BOOLEAN, LOCATION_TYPE VARCHAR, JOB_ID VARCHAR
)
COMMENT='{"origin":"sf_sit-is-fleet","name":"oss-app-restructure","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
$$
  SELECT TELEMETRY_ID, REGION, VEHICLE_TYPE, VEHICLE_ID, VEHICLE_ID AS OPERATOR_ID,
         TRIP_ID, TS, LATITUDE, LONGITUDE, POINT_GEOM,
         SPEED_KMH, HEADING_DEG, POSTED_SPEED_KMH, STATUS, IS_SPEEDING,
         IS_HOS_VIOLATION, IS_DETOUR, LOCATION_TYPE, JOB_ID
  FROM TABLE(FLEET_APP.UNIFIED_FLEET.F_VW_FACT_VEHICLE_TELEMETRY_SCOPED(P_REGION, P_DATASET_ID))
$$;

-- Trip Inspection: one enriched row per trip (origin/dest names, speed, shift label).
-- Generalized from the retired taxi VW_TRIP_SUMMARY; SHIFT_LABEL maps shift codes
-- (NOT vehicle type) -> human label. Mode-neutral OPERATOR_ID.
CREATE OR REPLACE FUNCTION FLEET_APP.FLEET_OPS.F_VW_TRIP_SUMMARY_SCOPED(P_REGION VARCHAR, P_DATASET_ID VARCHAR)
RETURNS TABLE (
  OPERATOR_ID VARCHAR, TRIP_ID VARCHAR, TRIP_START_TIME TIMESTAMP_NTZ, TRIP_END_TIME TIMESTAMP_NTZ,
  ORIGIN_ADDRESS VARCHAR, DESTINATION_ADDRESS VARCHAR, ROUTE_DURATION_SECS FLOAT, ROUTE_DISTANCE_METERS FLOAT,
  GEOMETRY GEOGRAPHY, ORIGIN GEOGRAPHY, DESTINATION GEOGRAPHY, SHIFT_LABEL VARCHAR,
  REGION VARCHAR, VEHICLE_TYPE VARCHAR, AVERAGE_KMH FLOAT, MAX_KMH FLOAT
)
COMMENT='{"origin":"sf_sit-is-fleet","name":"oss-app-restructure","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
$$
  WITH trips AS (
    SELECT * FROM TABLE(FLEET_APP.UNIFIED_FLEET.F_VW_FACT_TRIPS_SCOPED(P_REGION, P_DATASET_ID))
  ),
  tel AS (
    SELECT TRIP_ID, MAX(SPEED_KMH) AS MAX_KMH
    FROM TABLE(FLEET_APP.UNIFIED_FLEET.F_VW_FACT_VEHICLE_TELEMETRY_SCOPED(P_REGION, P_DATASET_ID))
    GROUP BY TRIP_ID
  ),
  pois AS (
    SELECT LOCATION_ID, NAME,
           ROW_NUMBER() OVER (PARTITION BY LOCATION_ID ORDER BY NAME) AS RN
    FROM TABLE(FLEET_APP.UNIFIED_FLEET.F_VW_DIM_POIS_SCOPED(P_REGION, P_DATASET_ID))
  ),
  fleet AS (
    SELECT VEHICLE_ID, SHIFT_TYPE,
           ROW_NUMBER() OVER (PARTITION BY VEHICLE_ID ORDER BY SHIFT_TYPE) AS RN
    FROM TABLE(FLEET_APP.UNIFIED_FLEET.F_VW_DIM_FLEET_SCOPED(P_REGION, P_DATASET_ID))
  )
  SELECT
    t.DRIVER_ID AS OPERATOR_ID,
    t.TRIP_ID,
    t.TRIP_START AS TRIP_START_TIME,
    t.TRIP_END AS TRIP_END_TIME,
    COALESCE(po.NAME, 'Unknown') AS ORIGIN_ADDRESS,
    COALESCE(pd.NAME, 'Unknown') AS DESTINATION_ADDRESS,
    t.DURATION_MINUTES * 60 AS ROUTE_DURATION_SECS,
    t.DISTANCE_KM * 1000 AS ROUTE_DISTANCE_METERS,
    t.ROUTE_GEOG AS GEOMETRY,
    t.ORIGIN,
    t.DESTINATION,
    CASE f.SHIFT_TYPE
      WHEN '6-14' THEN 'Morning'
      WHEN '14-22' THEN 'Afternoon'
      WHEN '22-6' THEN 'Night'
      ELSE f.SHIFT_TYPE
    END AS SHIFT_LABEL,
    t.REGION,
    t.VEHICLE_TYPE,
    CASE WHEN t.DURATION_MINUTES > 0 THEN t.DISTANCE_KM / (t.DURATION_MINUTES / 60) ELSE 0 END AS AVERAGE_KMH,
    ts.MAX_KMH
  FROM trips t
  LEFT JOIN pois po ON t.ORIGIN_POI_ID = po.LOCATION_ID AND po.RN = 1
  LEFT JOIN pois pd ON t.DESTINATION_POI_ID = pd.LOCATION_ID AND pd.RN = 1
  LEFT JOIN fleet f ON t.VEHICLE_ID = f.VEHICLE_ID AND f.RN = 1
  LEFT JOIN tel ts ON t.TRIP_ID = ts.TRIP_ID
$$;

-- Demand Density: H3-r7 hexbin of GPS pings, optional hour filter (P_HOUR NULL = all hours).
CREATE OR REPLACE FUNCTION FLEET_APP.FLEET_OPS.F_VW_H3_DENSITY_SCOPED(P_REGION VARCHAR, P_DATASET_ID VARCHAR, P_HOUR NUMBER)
RETURNS TABLE (
  H3_INDEX VARCHAR, HOUR_OF_DAY NUMBER, PING_COUNT NUMBER, AVG_SPEED_KMH FLOAT
)
COMMENT='{"origin":"sf_sit-is-fleet","name":"oss-app-restructure","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
$$
  SELECT H3_POINT_TO_CELL_STRING(POINT_GEOM, 7) AS H3_INDEX,
         EXTRACT(HOUR FROM TS) AS HOUR_OF_DAY,
         COUNT(*) AS PING_COUNT,
         ROUND(AVG(SPEED_KMH), 1) AS AVG_SPEED_KMH
  FROM TABLE(FLEET_APP.UNIFIED_FLEET.F_VW_FACT_VEHICLE_TELEMETRY_SCOPED(P_REGION, P_DATASET_ID))
  WHERE POINT_GEOM IS NOT NULL
    AND (P_HOUR IS NULL OR EXTRACT(HOUR FROM TS) = P_HOUR)
  GROUP BY 1, 2
$$;

-- Operator Performance: per-operator (DRIVER_ID) KPIs, enriched with shift + profile.
CREATE OR REPLACE FUNCTION FLEET_APP.FLEET_OPS.F_VW_OPERATOR_PERF_SCOPED(P_REGION VARCHAR, P_DATASET_ID VARCHAR)
RETURNS TABLE (
  OPERATOR_ID VARCHAR, SHIFT_TYPE VARCHAR, DRIVER_PROFILE VARCHAR, TRIPS NUMBER,
  TOTAL_DISTANCE_KM FLOAT, AVG_DISTANCE_KM FLOAT, AVG_DURATION_MIN FLOAT, AVG_SPEED_KMH FLOAT,
  REGION VARCHAR, VEHICLE_TYPE VARCHAR
)
COMMENT='{"origin":"sf_sit-is-fleet","name":"oss-app-restructure","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
$$
  WITH trips AS (
    SELECT * FROM TABLE(FLEET_APP.UNIFIED_FLEET.F_VW_FACT_TRIPS_SCOPED(P_REGION, P_DATASET_ID))
  ),
  fleet AS (
    SELECT VEHICLE_ID, SHIFT_TYPE, DRIVER_PROFILE,
           ROW_NUMBER() OVER (PARTITION BY VEHICLE_ID ORDER BY SHIFT_TYPE) AS RN
    FROM TABLE(FLEET_APP.UNIFIED_FLEET.F_VW_DIM_FLEET_SCOPED(P_REGION, P_DATASET_ID))
  )
  SELECT
    t.DRIVER_ID AS OPERATOR_ID,
    ANY_VALUE(f.SHIFT_TYPE) AS SHIFT_TYPE,
    ANY_VALUE(f.DRIVER_PROFILE) AS DRIVER_PROFILE,
    COUNT(*) AS TRIPS,
    ROUND(SUM(t.DISTANCE_KM), 1) AS TOTAL_DISTANCE_KM,
    ROUND(AVG(t.DISTANCE_KM), 2) AS AVG_DISTANCE_KM,
    ROUND(AVG(t.DURATION_MINUTES), 1) AS AVG_DURATION_MIN,
    ROUND(AVG(CASE WHEN t.DURATION_MINUTES > 0 THEN t.DISTANCE_KM / (t.DURATION_MINUTES / 60) END), 1) AS AVG_SPEED_KMH,
    ANY_VALUE(t.REGION) AS REGION,
    ANY_VALUE(t.VEHICLE_TYPE) AS VEHICLE_TYPE
  FROM trips t
  LEFT JOIN fleet f ON t.VEHICLE_ID = f.VEHICLE_ID AND f.RN = 1
  GROUP BY t.DRIVER_ID
$$;

-- Top Origins: busiest origin POIs by trip volume. Optional LOCATION_TYPE filter
-- (P_LOCATION_TYPE NULL = all types) generalizes the retired food_delivery
-- "restaurants" view into any origin category (depot, warehouse, restaurant, ...).
CREATE OR REPLACE FUNCTION FLEET_APP.FLEET_OPS.F_VW_TOP_ORIGINS_SCOPED(P_REGION VARCHAR, P_DATASET_ID VARCHAR, P_LOCATION_TYPE VARCHAR)
RETURNS TABLE (
  ORIGIN_POI_ID VARCHAR, ORIGIN_NAME VARCHAR, LOCATION_TYPE VARCHAR, LAT FLOAT, LNG FLOAT,
  LOCATION GEOGRAPHY, TOTAL_TRIPS NUMBER, AVG_DURATION_MIN FLOAT, REGION VARCHAR
)
COMMENT='{"origin":"sf_sit-is-fleet","name":"oss-app-restructure","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
$$
  WITH pois AS (
    SELECT * FROM TABLE(FLEET_APP.UNIFIED_FLEET.F_VW_DIM_POIS_SCOPED(P_REGION, P_DATASET_ID))
  ),
  trips AS (
    SELECT ORIGIN_POI_ID, TRIP_ID, DURATION_MINUTES
    FROM TABLE(FLEET_APP.UNIFIED_FLEET.F_VW_FACT_TRIPS_SCOPED(P_REGION, P_DATASET_ID))
  )
  SELECT
    p.LOCATION_ID AS ORIGIN_POI_ID,
    p.NAME AS ORIGIN_NAME,
    p.LOCATION_TYPE,
    ANY_VALUE(p.LAT) AS LAT,
    ANY_VALUE(p.LNG) AS LNG,
    ANY_VALUE(p.POINT_GEOM) AS LOCATION,
    COUNT(t.TRIP_ID) AS TOTAL_TRIPS,
    ROUND(AVG(t.DURATION_MINUTES), 1) AS AVG_DURATION_MIN,
    p.REGION
  FROM pois p
  LEFT JOIN trips t ON p.LOCATION_ID = t.ORIGIN_POI_ID
  WHERE (P_LOCATION_TYPE IS NULL OR p.LOCATION_TYPE = P_LOCATION_TYPE)
  GROUP BY p.LOCATION_ID, p.NAME, p.LOCATION_TYPE, p.REGION
$$;

-- Asset Utilization (sparse mode attributes): the optional/sparse attribute set.
-- Columns are the UNION of all mode attributes; modes that lack a given attribute
-- return NULL (HGV dims populated today; vessel draft / aircraft FL added later as
-- new columns, never a new schema). NO branching on VEHICLE_TYPE.
CREATE OR REPLACE FUNCTION FLEET_APP.FLEET_OPS.F_VW_ASSET_ATTRIBUTES_SCOPED(P_REGION VARCHAR, P_DATASET_ID VARCHAR)
RETURNS TABLE (
  VEHICLE_ID VARCHAR, VEHICLE_TYPE VARCHAR, REGION VARCHAR, OPERATING_MODE VARCHAR, VEHICLE_SUBTYPE VARCHAR,
  BASE_SPEED_KMH FLOAT, BATTERY_RANGE_KM FLOAT, WEIGHT_TONS NUMBER, HEIGHT_M NUMBER, LENGTH_M NUMBER,
  WIDTH_M NUMBER, AXLELOAD_T NUMBER, HAZMAT BOOLEAN, SHIFT_TYPE VARCHAR, DRIVER_PROFILE VARCHAR,
  HOME_LOCATION_ID VARCHAR
)
COMMENT='{"origin":"sf_sit-is-fleet","name":"oss-app-restructure","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
$$
  SELECT VEHICLE_ID, VEHICLE_TYPE, REGION, OPERATING_MODE, VEHICLE_SUBTYPE,
         BASE_SPEED_KMH, BATTERY_RANGE_KM, WEIGHT_TONS, HEIGHT_M, LENGTH_M,
         WIDTH_M, AXLELOAD_T, HAZMAT, SHIFT_TYPE, DRIVER_PROFILE, HOME_LOCATION_ID
  FROM TABLE(FLEET_APP.UNIFIED_FLEET.F_VW_DIM_FLEET_SCOPED(P_REGION, P_DATASET_ID))
$$;

-- ---------------------------------------------------------------------------
-- Grants: FLEET_OPS schema + UDTFs to the consumer + ops/admin roles.
-- ---------------------------------------------------------------------------
GRANT USAGE ON SCHEMA FLEET_APP.FLEET_OPS TO ROLE FLEET_APP_USER;
GRANT USAGE ON SCHEMA FLEET_APP.FLEET_OPS TO ROLE FLEET_APP_OPS;
GRANT USAGE ON SCHEMA FLEET_APP.FLEET_OPS TO ROLE FLEET_APP_ADMIN;

GRANT USAGE ON FUNCTION FLEET_APP.FLEET_OPS.F_VW_TRIPS_SCOPED(VARCHAR, VARCHAR) TO ROLE FLEET_APP_USER;
GRANT USAGE ON FUNCTION FLEET_APP.FLEET_OPS.F_VW_TRIPS_SCOPED(VARCHAR, VARCHAR) TO ROLE FLEET_APP_OPS;
GRANT USAGE ON FUNCTION FLEET_APP.FLEET_OPS.F_VW_TRIPS_SCOPED(VARCHAR, VARCHAR) TO ROLE FLEET_APP_ADMIN;
GRANT USAGE ON FUNCTION FLEET_APP.FLEET_OPS.F_VW_TELEMETRY_SCOPED(VARCHAR, VARCHAR) TO ROLE FLEET_APP_USER;
GRANT USAGE ON FUNCTION FLEET_APP.FLEET_OPS.F_VW_TELEMETRY_SCOPED(VARCHAR, VARCHAR) TO ROLE FLEET_APP_OPS;
GRANT USAGE ON FUNCTION FLEET_APP.FLEET_OPS.F_VW_TELEMETRY_SCOPED(VARCHAR, VARCHAR) TO ROLE FLEET_APP_ADMIN;
GRANT USAGE ON FUNCTION FLEET_APP.FLEET_OPS.F_VW_TRIP_SUMMARY_SCOPED(VARCHAR, VARCHAR) TO ROLE FLEET_APP_USER;
GRANT USAGE ON FUNCTION FLEET_APP.FLEET_OPS.F_VW_TRIP_SUMMARY_SCOPED(VARCHAR, VARCHAR) TO ROLE FLEET_APP_OPS;
GRANT USAGE ON FUNCTION FLEET_APP.FLEET_OPS.F_VW_TRIP_SUMMARY_SCOPED(VARCHAR, VARCHAR) TO ROLE FLEET_APP_ADMIN;
GRANT USAGE ON FUNCTION FLEET_APP.FLEET_OPS.F_VW_H3_DENSITY_SCOPED(VARCHAR, VARCHAR, NUMBER) TO ROLE FLEET_APP_USER;
GRANT USAGE ON FUNCTION FLEET_APP.FLEET_OPS.F_VW_H3_DENSITY_SCOPED(VARCHAR, VARCHAR, NUMBER) TO ROLE FLEET_APP_OPS;
GRANT USAGE ON FUNCTION FLEET_APP.FLEET_OPS.F_VW_H3_DENSITY_SCOPED(VARCHAR, VARCHAR, NUMBER) TO ROLE FLEET_APP_ADMIN;
GRANT USAGE ON FUNCTION FLEET_APP.FLEET_OPS.F_VW_OPERATOR_PERF_SCOPED(VARCHAR, VARCHAR) TO ROLE FLEET_APP_USER;
GRANT USAGE ON FUNCTION FLEET_APP.FLEET_OPS.F_VW_OPERATOR_PERF_SCOPED(VARCHAR, VARCHAR) TO ROLE FLEET_APP_OPS;
GRANT USAGE ON FUNCTION FLEET_APP.FLEET_OPS.F_VW_OPERATOR_PERF_SCOPED(VARCHAR, VARCHAR) TO ROLE FLEET_APP_ADMIN;
GRANT USAGE ON FUNCTION FLEET_APP.FLEET_OPS.F_VW_TOP_ORIGINS_SCOPED(VARCHAR, VARCHAR, VARCHAR) TO ROLE FLEET_APP_USER;
GRANT USAGE ON FUNCTION FLEET_APP.FLEET_OPS.F_VW_TOP_ORIGINS_SCOPED(VARCHAR, VARCHAR, VARCHAR) TO ROLE FLEET_APP_OPS;
GRANT USAGE ON FUNCTION FLEET_APP.FLEET_OPS.F_VW_TOP_ORIGINS_SCOPED(VARCHAR, VARCHAR, VARCHAR) TO ROLE FLEET_APP_ADMIN;
GRANT USAGE ON FUNCTION FLEET_APP.FLEET_OPS.F_VW_ASSET_ATTRIBUTES_SCOPED(VARCHAR, VARCHAR) TO ROLE FLEET_APP_USER;
GRANT USAGE ON FUNCTION FLEET_APP.FLEET_OPS.F_VW_ASSET_ATTRIBUTES_SCOPED(VARCHAR, VARCHAR) TO ROLE FLEET_APP_OPS;
GRANT USAGE ON FUNCTION FLEET_APP.FLEET_OPS.F_VW_ASSET_ATTRIBUTES_SCOPED(VARCHAR, VARCHAR) TO ROLE FLEET_APP_ADMIN;
