FROM node:20-alpine
ARG APP_VERSION=0.0.0
ENV APP_VERSION=$APP_VERSION
WORKDIR /app
COPY dist ./dist
COPY dist-server ./dist-server
COPY package.json package-lock.json* ./
RUN npm ci --omit=dev --legacy-peer-deps || npm install --omit=dev --legacy-peer-deps
EXPOSE 3001
CMD ["node", "dist-server/index.js"]
