#!/usr/bin/env bash
# deploy_cowork_skills.sh - upload the generated CoWork agent skills to a stage.
#
# WHY A STAGE
# -----------
# A Cortex Agent skill is REFERENCED, never copied: the orchestrator reads
# SKILL.md from its source location on demand. So the folders have to live
# somewhere the agent can read at request time, and the agent spec's `skills`
# array points at exactly this stage path (generated by build_cowork_skills.py,
# which owns SKILL_STAGE - keep the two in step).
#
# Ordering: run AFTER build_cowork_skills.py has written the folders and BEFORE
# create_agents.sh. An agent whose spec references a skill path that does not
# exist fails that reference on every request.
#
# Idempotent: OVERWRITE = TRUE, so a re-run refreshes changed skills. Skills are
# read fresh on each invocation, so an updated SKILL.md takes effect with no
# agent redeploy.
set -euo pipefail

CONNECTION="${1:?usage: deploy_cowork_skills.sh <connection>}"
SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$SKILL_DIR/fleet_sa_app/app/cowork_skills"
STAGE="FLEET_INTELLIGENCE.SEMANTIC.COWORK_SKILLS"

TRACK='{"origin":"sf_sit-is-fleet","name":"oss-install-fleet-apps","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql","component":"cowork-skills"}}'
TAG_SQL="ALTER SESSION SET query_tag = '$TRACK';"

[ -d "$SRC" ] || {
  echo "ERROR: $SRC does not exist - run build_cowork_skills.py first" >&2
  exit 1
}

COUNT=$(find "$SRC" -name SKILL.md | wc -l | tr -d ' ')
[ "$COUNT" -gt 0 ] || { echo "ERROR: no SKILL.md files under $SRC" >&2; exit 1; }
echo "[cowork-skills] uploading $COUNT skill(s) to @$STAGE"

snow sql -c "$CONNECTION" --enable-templating NONE -q \
  "$TAG_SQL CREATE STAGE IF NOT EXISTS $STAGE
     DIRECTORY = (ENABLE = TRUE)
     COMMENT = '$TRACK';" >/dev/null

# One PUT per folder. A single recursive PUT would flatten the tree, and the
# folder name IS the skill identity - SKILL.md must sit at the root of its own
# folder, and Snowflake does not search subdirectories.
UPLOADED=0
for md in "$SRC"/*/SKILL.md; do
  name="$(basename "$(dirname "$md")")"
  snow sql -c "$CONNECTION" --enable-templating NONE -q \
    "$TAG_SQL PUT 'file://$md' '@$STAGE/skills/$name/'
       AUTO_COMPRESS = FALSE OVERWRITE = TRUE;" >/dev/null
  UPLOADED=$((UPLOADED + 1))
done

# Verify by listing what the AGENT will see, not what we just sent: a PUT that
# lands on the wrong path still reports success.
FOUND=$(snow sql -c "$CONNECTION" --enable-templating NONE --format=CSV -q \
  "$TAG_SQL LS '@$STAGE/skills/' PATTERN='.*SKILL[.]md';" 2>/dev/null \
  | grep -c 'SKILL.md' || true)

echo "[cowork-skills] uploaded $UPLOADED, visible on stage: $FOUND"
if [ "$FOUND" -lt "$UPLOADED" ]; then
  echo "ERROR: only $FOUND of $UPLOADED SKILL.md file(s) are readable at @$STAGE/skills/" >&2
  exit 1
fi
echo "[cowork-skills] done."
