#!/usr/bin/env python3
"""Verified queries for the fleet semantic views.

Every SQL statement here was GENERATED by Cortex Analyst from the question, not
hand-written, so it is idiomatic for the view it targets and uses the same
logical-table or physical-view form Analyst itself would emit. Each one is
executed before it is embedded (`--validate`), because a verified query that does
not run is worse than none: it is presented to the user as trusted.

Ordering note for the DDL: AI_VERIFIED_QUERIES goes AFTER the COMMENT and
AI_SQL_GENERATION clauses and BEFORE COPY GRANTS.
"""

# view -> (vqr_name, question, onboarding, sql)
VQRS = {
    "SV_FLEET_OPS": (
        "top_origins_per_region",
        "Which origins generate most of our work?",
        True,
        """WITH ranked_origins AS (
  SELECT origin_region, origin_name, total_origin_trips,
         RANK() OVER (PARTITION BY origin_region ORDER BY total_origin_trips DESC NULLS LAST) AS rnk
  FROM SEMANTIC_VIEW(
    FLEET_INTELLIGENCE.SEMANTIC.SV_FLEET_OPS
    METRICS total_origin_trips
    DIMENSIONS origins.origin_region, origins.origin_name
  )
)
SELECT origin_region, origin_name, total_origin_trips, rnk
FROM ranked_origins
WHERE rnk <= 10
ORDER BY origin_region, rnk NULLS LAST""",
    ),
    "SV_ROUTE_DEVIATION": (
        "deviation_by_driver",
        "How closely does execution match the plan, by driver?",
        True,
        """SELECT *
FROM SEMANTIC_VIEW(
  FLEET_INTELLIGENCE.SEMANTIC.SV_ROUTE_DEVIATION
  METRICS deviation_rate_pct, avg_distance_deviation_pct
  DIMENSIONS driver_id
  WHERE is_route_deviation = TRUE
)
ORDER BY deviation_rate_pct DESC NULLS LAST""",
    ),
    "SV_CATCHMENT": (
        "poi_by_category_and_city",
        "How many points of interest are there per category in each city?",
        True,
        """SELECT *
FROM SEMANTIC_VIEW(
  FLEET_INTELLIGENCE.SEMANTIC.SV_CATCHMENT
  METRICS total_pois
  DIMENSIONS basic_category, city
)
ORDER BY total_pois DESC NULLS LAST
LIMIT 15""",
    ),
    "SV_DWELL_ANALYTICS": (
        "worst_facilities_by_dwell",
        "Which facilities cost us the most turnaround time?",
        True,
        """SELECT *
FROM SEMANTIC_VIEW(
  FLEET_INTELLIGENCE.SEMANTIC.SV_DWELL_ANALYTICS
  METRICS total_dwell_minutes
  DIMENSIONS sessions.location_name, sessions.facility_type, sessions.region
)
ORDER BY total_dwell_minutes DESC NULLS LAST
LIMIT 10""",
    ),
    "SV_ASSET_VELOCITY": (
        "costliest_idle_vehicles",
        "Which vehicles are sitting still, and what is that costing us?",
        True,
        """SELECT vehicle_id, last_location_name, idle_severity, idle_days, idle_hours,
       cost_of_idleness_usd
FROM FLEET_APP.ROUTE_OPTIMIZATION.VW_VEHICLE_COST_OF_IDLENESS
ORDER BY cost_of_idleness_usd DESC NULLS LAST
LIMIT 10""",
    ),
    "SV_LOCATION": (
        "candidate_sites_by_household_base",
        "Which candidate sites have the largest household base?",
        True,
        """SELECT poi_name AS store_name, store_id, reference_hh, annual_revenue
FROM FLEET_APP.LOCATION.VW_STORE_FACTS
WHERE store_role = 'CANDIDATE'
ORDER BY reference_hh DESC NULLS LAST""",
    ),
    "SV_SOURCING": (
        "costliest_customers_by_freight",
        "Which customers cost us the most in annual freight, and which plant serves them?",
        True,
        """SELECT customer_id, customer_name, current_plant, product, region,
       SUM(current_annual_freight) AS total_current_annual_freight,
       SUM(annual_truckloads)      AS total_annual_truckloads,
       AVG(current_distance_km)    AS avg_current_distance_km
FROM FLEET_APP.SOURCING.VW_SOURCING_FACTS
GROUP BY customer_id, customer_name, current_plant, product, region
ORDER BY total_current_annual_freight DESC NULLS LAST
LIMIT 10""",
    ),
    "SV_DELIVERY_SYNC": (
        "recent_site_visits",
        "Has the delivery arrived and left, and how long was it on site?",
        True,
        """SELECT visit_id, site_name, site_id, vehicle_id, arrival_ts, departure_ts,
       dwell_minutes, source_status_hint
FROM FLEET_APP.DELIVERY_SYNC.VW_SITE_VISITS
ORDER BY arrival_ts DESC NULLS LAST
LIMIT 20""",
    ),
    "SV_BACKLOAD_MATCHING": (
        "richest_external_offers",
        "Which external freight offers are worth the most, and where do they run?",
        True,
        """SELECT offer_id, pickup_city, dropoff_city, price_usd,
       pickup_lat, pickup_lon, dropoff_lat, dropoff_lon
FROM FLEET_APP.BACKLOAD_MATCHING.VW_EXTERNAL_OFFERS
ORDER BY price_usd DESC NULLS LAST
LIMIT 10""",
    ),
    "SV_LABOR": (
        "projected_over_60_hours",
        "Which drivers are projected to exceed 60 hours this week?",
        True,
        """SELECT operator_id, region, projected_week_hours, binding_constraint
FROM FLEET_APP.LABOR.VW_LABOR_WEEK
WHERE is_current_week = TRUE
  AND projected_week_hours > 60
ORDER BY projected_week_hours DESC NULLS LAST""",
    ),
    "SV_EMERGENCY_RESPONSE": (
        "participants_per_care_centre",
        "How many participants are nearest to each care centre?",
        True,
        """SELECT *
FROM SEMANTIC_VIEW(
  FLEET_INTELLIGENCE.SEMANTIC.SV_EMERGENCY_RESPONSE
  METRICS participant_count
  DIMENSIONS participants.nearest_center_id
)""",
    ),
}

VERIFIED_BY = "(STEWARD = sf_sit_is_fleet)"
# Fixed timestamp: the date these were generated and executed. A moving
# SYSDATE() would make the DDL non-deterministic and every install would look
# like a change.
VERIFIED_AT = 1789000000


def clause(view: str) -> str:
    name, question, onboarding, sql = VQRS[view]
    # Single-quoted SQL literal, so any apostrophe must be doubled.
    q = question.replace("'", "''")
    s = sql.replace("'", "''")
    return (
        "  AI_VERIFIED_QUERIES (\n"
        f"    {name} AS (\n"
        f"      QUESTION '{q}'\n"
        f"      VERIFIED_AT {VERIFIED_AT}\n"
        f"      ONBOARDING_QUESTION {'TRUE' if onboarding else 'FALSE'}\n"
        f"      VERIFIED_BY '{VERIFIED_BY}'\n"
        f"      SQL '{s}'\n"
        "    )\n"
        "  )\n"
    )
