/*
 * seed-data.sql — Route Deviation
 * Load San Francisco baseline data from S3.
 * Includes source telemetry tables + ETL output tables.
 * Idempotent: only loads if tables are empty for the target region.
 */

CREATE DATABASE IF NOT EXISTS FLEET_INTELLIGENCE;
CREATE SCHEMA IF NOT EXISTS FLEET_INTELLIGENCE.ROUTE_DEVIATION;
CREATE SCHEMA IF NOT EXISTS FLEET_INTELLIGENCE.ROUTE_CACHE;

CREATE STAGE IF NOT EXISTS FLEET_INTELLIGENCE.ROUTE_DEVIATION.SEED_STAGE
    URL = 's3://fleet-intelligence/SanFrancisco/route-deviation/'
    FILE_FORMAT = (TYPE = PARQUET);

--------------------------------------------------------------------
-- ROUTE_CACHE (shared schema)
--------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.ROUTE_CACHE.ROUTE_CACHE (
    REGION           VARCHAR NOT NULL DEFAULT 'SanFrancisco',
    ORIGIN_ID        VARCHAR,
    DEST_ID          VARCHAR,
    ROAD_DISTANCE_M  FLOAT,
    DURATION_SECONDS FLOAT,
    ROUTE_LINE       GEOGRAPHY,
    CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COPY INTO FLEET_INTELLIGENCE.ROUTE_CACHE.ROUTE_CACHE
FROM @FLEET_INTELLIGENCE.ROUTE_DEVIATION.SEED_STAGE/ROUTE_CACHE/
FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE ON_ERROR = CONTINUE;

--------------------------------------------------------------------
-- TRIP_ACTUAL_METRICS
--------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.ROUTE_DEVIATION.TRIP_ACTUAL_METRICS (
    REGION               VARCHAR NOT NULL DEFAULT 'SanFrancisco',
    TRIP_ID              VARCHAR,
    TRUCK_ID             VARCHAR,
    DRIVER_ID            VARCHAR,
    TRUCK_ID_NORMALIZED  VARCHAR,
    TRIP_DATE            DATE,
    TRIP_SEQ             INT,
    ACTUAL_START_TS      TIMESTAMP_NTZ,
    ACTUAL_END_TS        TIMESTAMP_NTZ,
    TOTAL_DURATION_SEC   FLOAT,
    TOTAL_DURATION_MIN   FLOAT,
    ACTUAL_DURATION_SEC  FLOAT,
    ACTUAL_DURATION_MIN  FLOAT,
    POINT_COUNT          INT,
    ACTUAL_PATH          GEOGRAPHY
);

COPY INTO FLEET_INTELLIGENCE.ROUTE_DEVIATION.TRIP_ACTUAL_METRICS
FROM @FLEET_INTELLIGENCE.ROUTE_DEVIATION.SEED_STAGE/TRIP_ACTUAL_METRICS/
FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE ON_ERROR = CONTINUE;

--------------------------------------------------------------------
-- OD_EXPECTED_ROUTES
--------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.ROUTE_DEVIATION.OD_EXPECTED_ROUTES (
    REGION                     VARCHAR NOT NULL DEFAULT 'SanFrancisco',
    ORIGIN_ID                  VARCHAR,
    DEST_ID                    VARCHAR,
    ORIGIN_LNG                 FLOAT,
    ORIGIN_LAT                 FLOAT,
    ORIGIN_NAME                VARCHAR,
    ORIGIN_CITY                VARCHAR,
    DEST_LNG                   FLOAT,
    DEST_LAT                   FLOAT,
    DEST_NAME                  VARCHAR,
    DEST_CITY                  VARCHAR,
    STRAIGHT_LINE_DISTANCE_KM  FLOAT,
    EXPECTED_DISTANCE_KM       FLOAT,
    EXPECTED_DURATION_SEC      FLOAT,
    EXPECTED_DURATION_MIN      FLOAT,
    EXPECTED_PATH              GEOGRAPHY
);

COPY INTO FLEET_INTELLIGENCE.ROUTE_DEVIATION.OD_EXPECTED_ROUTES
FROM @FLEET_INTELLIGENCE.ROUTE_DEVIATION.SEED_STAGE/OD_EXPECTED_ROUTES/
FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE ON_ERROR = CONTINUE;

--------------------------------------------------------------------
-- TRIP_DEVIATION_ANALYSIS
--------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.ROUTE_DEVIATION.TRIP_DEVIATION_ANALYSIS (
    REGION                   VARCHAR NOT NULL DEFAULT 'SanFrancisco',
    TRIP_ID                  VARCHAR,
    TRUCK_ID                 VARCHAR,
    DRIVER_ID                VARCHAR,
    TRIP_DATE                DATE,
    ROUTE_VARIATION          VARCHAR,
    ROUTE_DEVIATION_FACTOR   FLOAT,
    TRIP_TYPE                VARCHAR,
    ACTUAL_DISTANCE_KM       FLOAT,
    ACTUAL_DURATION_MIN      FLOAT,
    TOTAL_DURATION_MIN       FLOAT,
    ACTUAL_START_TS          TIMESTAMP_NTZ,
    ACTUAL_END_TS            TIMESTAMP_NTZ,
    POINT_COUNT              INT,
    EXPECTED_DISTANCE_KM     FLOAT,
    EXPECTED_DURATION_MIN    FLOAT,
    STRAIGHT_LINE_DISTANCE_KM FLOAT,
    ORIGIN_NAME              VARCHAR,
    ORIGIN_CITY              VARCHAR,
    DEST_NAME                VARCHAR,
    DEST_CITY                VARCHAR,
    DISTANCE_DEVIATION_KM    FLOAT,
    DISTANCE_DEVIATION_PCT   FLOAT,
    DURATION_DEVIATION_MIN   FLOAT,
    DURATION_DEVIATION_PCT   FLOAT,
    IS_DISTANCE_DEVIATION    BOOLEAN,
    IS_DURATION_DEVIATION    BOOLEAN,
    IS_ROUTE_DEVIATION       BOOLEAN,
    ACTUAL_PATH              GEOGRAPHY,
    EXPECTED_PATH            GEOGRAPHY
);

COPY INTO FLEET_INTELLIGENCE.ROUTE_DEVIATION.TRIP_DEVIATION_ANALYSIS
FROM @FLEET_INTELLIGENCE.ROUTE_DEVIATION.SEED_STAGE/TRIP_DEVIATION_ANALYSIS/
FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE ON_ERROR = CONTINUE;

--------------------------------------------------------------------
-- DRIVER_DEVIATION_SUMMARY
--------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.ROUTE_DEVIATION.DRIVER_DEVIATION_SUMMARY (
    REGION                     VARCHAR NOT NULL DEFAULT 'SanFrancisco',
    TRUCK_ID                   VARCHAR,
    DRIVER_ID                  VARCHAR,
    DRIVER_PROFILE             VARCHAR,
    TRUCK_TYPE                 VARCHAR,
    HOME_CITY                  VARCHAR,
    TOTAL_TRIPS                INT,
    DEVIATION_TRIPS            INT,
    DEVIATION_RATE_PCT         FLOAT,
    TOTAL_EXCESS_KM            FLOAT,
    TOTAL_TIME_LOST_MIN        FLOAT,
    AVG_DISTANCE_DEVIATION_PCT FLOAT,
    AVG_DURATION_DEVIATION_PCT FLOAT,
    MAX_DISTANCE_DEVIATION_PCT FLOAT,
    MAX_DURATION_DEVIATION_PCT FLOAT
);

COPY INTO FLEET_INTELLIGENCE.ROUTE_DEVIATION.DRIVER_DEVIATION_SUMMARY
FROM @FLEET_INTELLIGENCE.ROUTE_DEVIATION.SEED_STAGE/DRIVER_DEVIATION_SUMMARY/
FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE ON_ERROR = CONTINUE;

--------------------------------------------------------------------
-- DAILY_DEVIATION_TRENDS
--------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.ROUTE_DEVIATION.DAILY_DEVIATION_TRENDS (
    REGION                    VARCHAR NOT NULL DEFAULT 'SanFrancisco',
    TRIP_DATE                 DATE,
    DAY_OF_WEEK               VARCHAR,
    TOTAL_TRIPS               INT,
    DEVIATION_TRIPS           INT,
    DEVIATION_RATE_PCT        FLOAT,
    TOTAL_EXCESS_DISTANCE_KM  FLOAT,
    TOTAL_EXCESS_DURATION_MIN FLOAT,
    AVG_DISTANCE_DEVIATION_PCT FLOAT,
    AVG_DURATION_DEVIATION_PCT FLOAT
);

COPY INTO FLEET_INTELLIGENCE.ROUTE_DEVIATION.DAILY_DEVIATION_TRENDS
FROM @FLEET_INTELLIGENCE.ROUTE_DEVIATION.SEED_STAGE/DAILY_DEVIATION_TRENDS/
FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE ON_ERROR = CONTINUE;

--------------------------------------------------------------------
-- VALIDATION
--------------------------------------------------------------------
SELECT 'ROUTE_CACHE' AS TBL, COUNT(*) AS ROWS FROM FLEET_INTELLIGENCE.ROUTE_CACHE.ROUTE_CACHE
UNION ALL SELECT 'TRIP_ACTUAL_METRICS', COUNT(*) FROM FLEET_INTELLIGENCE.ROUTE_DEVIATION.TRIP_ACTUAL_METRICS
UNION ALL SELECT 'OD_EXPECTED_ROUTES', COUNT(*) FROM FLEET_INTELLIGENCE.ROUTE_DEVIATION.OD_EXPECTED_ROUTES
UNION ALL SELECT 'TRIP_DEVIATION_ANALYSIS', COUNT(*) FROM FLEET_INTELLIGENCE.ROUTE_DEVIATION.TRIP_DEVIATION_ANALYSIS
UNION ALL SELECT 'DRIVER_DEVIATION_SUMMARY', COUNT(*) FROM FLEET_INTELLIGENCE.ROUTE_DEVIATION.DRIVER_DEVIATION_SUMMARY
UNION ALL SELECT 'DAILY_DEVIATION_TRENDS', COUNT(*) FROM FLEET_INTELLIGENCE.ROUTE_DEVIATION.DAILY_DEVIATION_TRENDS;
