/*
 * seed-data.sql — Route Deviation
 * Load San Francisco baseline ETL output data from S3.
 * Only loads pre-computed ETL tables + CONFIG.
 * Source data comes from SYNTHETIC_DATASETS.UNIFIED via projection views.
 * Idempotent: only loads if tables are empty.
 */

CREATE DATABASE IF NOT EXISTS FLEET_INTELLIGENCE;
CREATE SCHEMA IF NOT EXISTS FLEET_INTELLIGENCE.ROUTE_DEVIATION;

CREATE STAGE IF NOT EXISTS FLEET_INTELLIGENCE.ROUTE_DEVIATION.SEED_STAGE
    URL = 's3://fleet-intelligence/SanFrancisco/route-deviation/'
    FILE_FORMAT = (TYPE = PARQUET);

--------------------------------------------------------------------
-- CONFIG
--------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.ROUTE_DEVIATION.CONFIG (
    VEHICLE_TYPE VARCHAR NOT NULL,
    REGION       VARCHAR NOT NULL
);
MERGE INTO FLEET_INTELLIGENCE.ROUTE_DEVIATION.CONFIG tgt
USING (SELECT 'ebike' AS VEHICLE_TYPE, 'SanFrancisco' AS REGION) src
ON TRUE
WHEN NOT MATCHED THEN INSERT (VEHICLE_TYPE, REGION) VALUES (src.VEHICLE_TYPE, src.REGION);

--------------------------------------------------------------------
-- TRIP_DEVIATION_ANALYSIS
--------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.ROUTE_DEVIATION.TRIP_DEVIATION_ANALYSIS (
    REGION                   VARCHAR NOT NULL DEFAULT 'SanFrancisco',
    TRIP_ID                  VARCHAR,
    VEHICLE_ID                 VARCHAR,
    DRIVER_ID                VARCHAR,
    TRIP_DATE                DATE,
    ROUTE_VARIATION          VARCHAR,
    ROUTE_DEVIATION_FACTOR   FLOAT,
    TRIP_TYPE                VARCHAR,
    ACTUAL_DISTANCE_KM       FLOAT,
    ACTUAL_DURATION_MIN      FLOAT,
    TOTAL_DURATION_MIN       FLOAT,
    ACTUAL_START_TS          TIMESTAMP_NTZ,
    ACTUAL_END_TS            TIMESTAMP_NTZ,
    POINT_COUNT              INT,
    EXPECTED_DISTANCE_KM     FLOAT,
    EXPECTED_DURATION_MIN    FLOAT,
    STRAIGHT_LINE_DISTANCE_KM FLOAT,
    ORIGIN_NAME              VARCHAR,
    ORIGIN_CITY              VARCHAR,
    DEST_NAME                VARCHAR,
    DEST_CITY                VARCHAR,
    DISTANCE_DEVIATION_KM    FLOAT,
    DISTANCE_DEVIATION_PCT   FLOAT,
    DURATION_DEVIATION_MIN   FLOAT,
    DURATION_DEVIATION_PCT   FLOAT,
    IS_DISTANCE_DEVIATION    BOOLEAN,
    IS_DURATION_DEVIATION    BOOLEAN,
    IS_ROUTE_DEVIATION       BOOLEAN,
    ACTUAL_PATH              GEOGRAPHY,
    EXPECTED_PATH            GEOGRAPHY
);

COPY INTO FLEET_INTELLIGENCE.ROUTE_DEVIATION.TRIP_DEVIATION_ANALYSIS
FROM @FLEET_INTELLIGENCE.ROUTE_DEVIATION.SEED_STAGE/TRIP_DEVIATION_ANALYSIS/
FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE ON_ERROR = CONTINUE;

--------------------------------------------------------------------
-- DRIVER_DEVIATION_SUMMARY
--------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.ROUTE_DEVIATION.DRIVER_DEVIATION_SUMMARY (
    REGION                     VARCHAR NOT NULL DEFAULT 'SanFrancisco',
    VEHICLE_ID                   VARCHAR,
    DRIVER_ID                  VARCHAR,
    DRIVER_PROFILE             VARCHAR,
    OPERATING_MODE             VARCHAR,
    HOME_CITY                  VARCHAR,
    TOTAL_TRIPS                INT,
    DEVIATION_TRIPS            INT,
    DEVIATION_RATE_PCT         FLOAT,
    TOTAL_EXCESS_KM            FLOAT,
    TOTAL_TIME_LOST_MIN        FLOAT,
    AVG_DISTANCE_DEVIATION_PCT FLOAT,
    AVG_DURATION_DEVIATION_PCT FLOAT,
    MAX_DISTANCE_DEVIATION_PCT FLOAT,
    MAX_DURATION_DEVIATION_PCT FLOAT
);

COPY INTO FLEET_INTELLIGENCE.ROUTE_DEVIATION.DRIVER_DEVIATION_SUMMARY
FROM @FLEET_INTELLIGENCE.ROUTE_DEVIATION.SEED_STAGE/DRIVER_DEVIATION_SUMMARY/
FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE ON_ERROR = CONTINUE;

--------------------------------------------------------------------
-- DAILY_DEVIATION_TRENDS
--------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.ROUTE_DEVIATION.DAILY_DEVIATION_TRENDS (
    REGION                    VARCHAR NOT NULL DEFAULT 'SanFrancisco',
    TRIP_DATE                 DATE,
    DAY_OF_WEEK               VARCHAR,
    TOTAL_TRIPS               INT,
    DEVIATION_TRIPS           INT,
    DEVIATION_RATE_PCT        FLOAT,
    TOTAL_EXCESS_DISTANCE_KM  FLOAT,
    TOTAL_EXCESS_DURATION_MIN FLOAT,
    AVG_DISTANCE_DEVIATION_PCT FLOAT,
    AVG_DURATION_DEVIATION_PCT FLOAT
);

COPY INTO FLEET_INTELLIGENCE.ROUTE_DEVIATION.DAILY_DEVIATION_TRENDS
FROM @FLEET_INTELLIGENCE.ROUTE_DEVIATION.SEED_STAGE/DAILY_DEVIATION_TRENDS/
FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE ON_ERROR = CONTINUE;

--------------------------------------------------------------------
-- VALIDATION
--------------------------------------------------------------------
SELECT 'TRIP_DEVIATION_ANALYSIS' AS TBL, COUNT(*) AS ROW_CNT FROM FLEET_INTELLIGENCE.ROUTE_DEVIATION.TRIP_DEVIATION_ANALYSIS
UNION ALL SELECT 'DRIVER_DEVIATION_SUMMARY', COUNT(*) FROM FLEET_INTELLIGENCE.ROUTE_DEVIATION.DRIVER_DEVIATION_SUMMARY
UNION ALL SELECT 'DAILY_DEVIATION_TRENDS', COUNT(*) FROM FLEET_INTELLIGENCE.ROUTE_DEVIATION.DAILY_DEVIATION_TRENDS;
