EXECUTE IMMEDIATE $$
DECLARE
  ddl STRING;
BEGIN
  EXECUTE IMMEDIATE 'USE SCHEMA FLEET_INTELLIGENCE.SEMANTIC';
  ddl := (SELECT GET_DDL('SEMANTIC_VIEW', 'FLEET_INTELLIGENCE.SEMANTIC.SV_BACKLOAD_MATCHING'));
  ddl := REPLACE(ddl, 'SYNTHETIC_DATASETS.UNIFIED.V_FACT_TRIPS_CURRENT', 'FLEET_APP.BACKLOAD_MATCHING.VW_TRIPS_CURRENT');
  ddl := REPLACE(ddl, 'SYNTHETIC_DATASETS.UNIFIED.V_DIM_POIS_CURRENT', 'FLEET_APP.BACKLOAD_MATCHING.VW_POIS_CURRENT');
  ddl := REPLACE(ddl, 'SYNTHETIC_DATASETS.UNIFIED.V_DIM_FLEET_CURRENT', 'FLEET_APP.BACKLOAD_MATCHING.VW_FLEET_CURRENT');
  ddl := REPLACE(ddl, 'SYNTHETIC_DATASETS.UNIFIED.V_FACT_FREIGHT_OFFERS_CURRENT', 'FLEET_APP.BACKLOAD_MATCHING.VW_FREIGHT_OFFERS');
  ddl := REPLACE(ddl, 'OPENROUTESERVICE_APP.CORE.VEHICLE_CLASS_PROFILE', 'FLEET_APP.BACKLOAD_MATCHING.VW_VEHICLE_CLASS_PROFILE');
  ddl := REPLACE(ddl, 'FLEET_INTELLIGENCE.BACKLOAD_MATCHING.PROPOSAL_DECISIONS', 'FLEET_APP.BACKLOAD_MATCHING.VW_PROPOSAL_DECISIONS');
  ddl := REPLACE(ddl, 'FLEET_INTELLIGENCE.BACKLOAD_MATCHING.CONFIG', 'FLEET_APP.BACKLOAD_MATCHING.VW_CONFIG');
  ddl := REPLACE(ddl, 'FLEET_INTELLIGENCE.BACKLOAD_MATCHING.VW_TRAILERS', 'FLEET_APP.BACKLOAD_MATCHING.VW_TRAILERS');
  ddl := REPLACE(ddl, 'FLEET_INTELLIGENCE.BACKLOAD_MATCHING.VW_EXTERNAL_OFFERS', 'FLEET_APP.BACKLOAD_MATCHING.VW_EXTERNAL_OFFERS');
  EXECUTE IMMEDIATE :ddl;
  RETURN 'repointed semantic views';
END;
$$;
