EXECUTE IMMEDIATE $$
DECLARE
  ddl STRING;
BEGIN
  EXECUTE IMMEDIATE 'USE SCHEMA FLEET_INTELLIGENCE.SEMANTIC';
  ddl := (SELECT GET_DDL('SEMANTIC_VIEW', 'FLEET_INTELLIGENCE.SEMANTIC.SV_DHL_BACKLOAD'));
  ddl := REPLACE(ddl, 'FLEET_INTELLIGENCE.DHL_NTBO.DHL_TRAILERS', 'FLEET_APP.DHL_NTBO.VW_RAW_TRAILERS');
  ddl := REPLACE(ddl, 'FLEET_INTELLIGENCE.DHL_NTBO.DHL_ORDERS', 'FLEET_APP.DHL_NTBO.VW_RAW_ORDERS');
  ddl := REPLACE(ddl, 'FLEET_INTELLIGENCE.DHL_NTBO.DHL_PROPOSALS', 'FLEET_APP.DHL_NTBO.VW_RAW_PROPOSALS');
  ddl := REPLACE(ddl, 'FLEET_INTELLIGENCE.DHL_NTBO.DHL_SNAPSHOTS', 'FLEET_APP.DHL_NTBO.VW_SNAPSHOTS');
  ddl := REPLACE(ddl, 'FLEET_INTELLIGENCE.DHL_NTBO.V_DHL_TRAILERS_ACTIVE', 'FLEET_APP.DHL_NTBO.VW_DHL_TRAILERS');
  ddl := REPLACE(ddl, 'FLEET_INTELLIGENCE.DHL_NTBO.V_DHL_ORDERS_ACTIVE', 'FLEET_APP.DHL_NTBO.VW_DHL_ORDERS');
  ddl := REPLACE(ddl, 'FLEET_INTELLIGENCE.DHL_NTBO.V_DHL_PROPOSALS_ACTIVE', 'FLEET_APP.DHL_NTBO.VW_DHL_PROPOSALS');
  EXECUTE IMMEDIATE :ddl;
  RETURN 'repointed semantic views';
END;
$$;
