-- Extend DIM_FLEET with HGV-specific attributes for Asset Velocity v2 (smart reposition)
-- These columns feed ORS profile_params (matrix/isochrone/optimization) and VROOM
-- skills/capacity. Synthetic data is regenerated by Data Studio, so a companion
-- view (VW_FLEET_HGV_PROFILE) is provided that COALESCEs against deterministic
-- defaults derived from HASH(VEHICLE_ID) + OPERATING_MODE so the page works even
-- after a fresh regeneration.

ALTER SESSION SET query_tag = '{"origin":"sf_sit-is-fleet","name":"oss-route-optimization","version":{"major":1,"minor":1},"attributes":{"is_quickstart":1,"source":"sql"}}';

-- Friction-log F4 (secondary): drop the dependent view BEFORE adding columns
-- to the underlying table. Without this, the next ors_control_app boot
-- fails with `View definition for V_DIM_FLEET_CURRENT declared 13 column(s),
-- but view query produces 20 column(s)`. init.ts will recreate the view
-- with the correct shape on its next run.
DROP VIEW IF EXISTS SYNTHETIC_DATASETS.UNIFIED.V_DIM_FLEET_CURRENT;

ALTER TABLE SYNTHETIC_DATASETS.UNIFIED.DIM_FLEET ADD COLUMN IF NOT EXISTS WEIGHT_TONS    NUMBER(6,2);
ALTER TABLE SYNTHETIC_DATASETS.UNIFIED.DIM_FLEET ADD COLUMN IF NOT EXISTS HEIGHT_M       NUMBER(4,2);
ALTER TABLE SYNTHETIC_DATASETS.UNIFIED.DIM_FLEET ADD COLUMN IF NOT EXISTS LENGTH_M       NUMBER(4,2);
ALTER TABLE SYNTHETIC_DATASETS.UNIFIED.DIM_FLEET ADD COLUMN IF NOT EXISTS WIDTH_M        NUMBER(4,2);
ALTER TABLE SYNTHETIC_DATASETS.UNIFIED.DIM_FLEET ADD COLUMN IF NOT EXISTS AXLELOAD_T     NUMBER(4,2);
ALTER TABLE SYNTHETIC_DATASETS.UNIFIED.DIM_FLEET ADD COLUMN IF NOT EXISTS HAZMAT         BOOLEAN;
ALTER TABLE SYNTHETIC_DATASETS.UNIFIED.DIM_FLEET ADD COLUMN IF NOT EXISTS VEHICLE_SUBTYPE VARCHAR(16); -- DRY | REEFER | FLAT | TANKER | NULL

-- Deterministic backfill (stable for demos):
-- bucket = MOD(ABS(HASH(VEHICLE_ID)), 100)
-- 0..59  -> DRY,    60..84 -> REEFER, 85..96 -> FLAT, 97..99 -> TANKER  (only for trucking)
-- TANKER subtype: 18% hazmat=true (bucket 97..98 -> false, 99 -> true)
UPDATE SYNTHETIC_DATASETS.UNIFIED.DIM_FLEET
   SET VEHICLE_SUBTYPE = CASE
         WHEN OPERATING_MODE <> 'trucking' THEN NULL
         WHEN MOD(ABS(HASH(VEHICLE_ID)), 100) <  60 THEN 'DRY'
         WHEN MOD(ABS(HASH(VEHICLE_ID)), 100) <  85 THEN 'REEFER'
         WHEN MOD(ABS(HASH(VEHICLE_ID)), 100) <  97 THEN 'FLAT'
         ELSE 'TANKER'
       END,
       HAZMAT = CASE
         WHEN OPERATING_MODE <> 'trucking' THEN FALSE
         WHEN MOD(ABS(HASH(VEHICLE_ID)), 100) = 99 THEN TRUE
         ELSE FALSE
       END,
       WEIGHT_TONS = CASE
         WHEN OPERATING_MODE = 'trucking'
           THEN ROUND(38 + (MOD(ABS(HASH(VEHICLE_ID || '_w')), 600) / 100.0), 2) -- 38.0..44.0
         ELSE 2.0
       END,
       HEIGHT_M = CASE
         WHEN OPERATING_MODE = 'trucking' THEN 4.00
         ELSE 2.00
       END,
       LENGTH_M = CASE
         WHEN OPERATING_MODE = 'trucking' THEN 16.50
         ELSE 4.50
       END,
       WIDTH_M = CASE
         WHEN OPERATING_MODE = 'trucking' THEN 2.55
         ELSE 1.85
       END,
       AXLELOAD_T = CASE
         WHEN OPERATING_MODE = 'trucking' THEN 11.50
         ELSE 1.20
       END
 WHERE TRUE;

-- Recreate dataset-scoped projection view immediately (do not rely on the next
-- ors_control_app boot). extend-dim-fleet-hgv.sql drops this view above.
CREATE OR REPLACE VIEW SYNTHETIC_DATASETS.UNIFIED.V_DIM_FLEET_CURRENT
COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-build-routing-solution","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"app"}}'
AS
SELECT f.*
FROM SYNTHETIC_DATASETS.UNIFIED.DIM_FLEET f
JOIN FLEET_INTELLIGENCE.CORE.DIM_DATASETS d
  ON d.DATASET_ID = f.JOB_ID
 AND d.REGION = f.REGION
 AND d.VEHICLE_TYPE = f.VEHICLE_TYPE
 AND d.IS_ACTIVE = TRUE;

-- Resilient view: works even after Data Studio regenerates DIM_FLEET (which
-- would drop the HGV columns). Uses COALESCE against the same deterministic
-- formulas as the backfill, so callers always get well-defined values.
CREATE OR REPLACE VIEW FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.VW_FLEET_HGV_PROFILE
COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-route-optimization","version":{"major":1,"minor":1},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
WITH base AS (
  SELECT
    VEHICLE_ID,
    REGION,
    VEHICLE_TYPE,
    ORS_PROFILE,
    OPERATING_MODE,
    MOD(ABS(HASH(VEHICLE_ID)), 100)               AS BKT
  FROM SYNTHETIC_DATASETS.UNIFIED.V_DIM_FLEET_CURRENT
)
SELECT
  f.VEHICLE_ID,
  f.REGION,
  f.VEHICLE_TYPE,
  f.ORS_PROFILE,
  f.OPERATING_MODE,
  COALESCE(f.VEHICLE_SUBTYPE,
    CASE
      WHEN f.OPERATING_MODE <> 'trucking' THEN NULL
      WHEN b.BKT <  60 THEN 'DRY'
      WHEN b.BKT <  85 THEN 'REEFER'
      WHEN b.BKT <  97 THEN 'FLAT'
      ELSE 'TANKER'
    END
  )                                               AS VEHICLE_SUBTYPE,
  COALESCE(f.HAZMAT,
    CASE WHEN f.OPERATING_MODE = 'trucking' AND b.BKT = 99 THEN TRUE ELSE FALSE END
  )                                               AS HAZMAT,
  COALESCE(f.WEIGHT_TONS,
    CASE WHEN f.OPERATING_MODE = 'trucking'
         THEN ROUND(38 + (MOD(ABS(HASH(f.VEHICLE_ID || '_w')), 600) / 100.0), 2)
         ELSE 2.0 END
  )                                               AS WEIGHT_TONS,
  COALESCE(f.HEIGHT_M,    CASE WHEN f.OPERATING_MODE = 'trucking' THEN 4.00 ELSE 2.00 END) AS HEIGHT_M,
  COALESCE(f.LENGTH_M,    CASE WHEN f.OPERATING_MODE = 'trucking' THEN 16.50 ELSE 4.50 END) AS LENGTH_M,
  COALESCE(f.WIDTH_M,     CASE WHEN f.OPERATING_MODE = 'trucking' THEN 2.55 ELSE 1.85 END) AS WIDTH_M,
  COALESCE(f.AXLELOAD_T,  CASE WHEN f.OPERATING_MODE = 'trucking' THEN 11.50 ELSE 1.20 END) AS AXLELOAD_T
FROM SYNTHETIC_DATASETS.UNIFIED.V_DIM_FLEET_CURRENT f
JOIN base b ON b.VEHICLE_ID = f.VEHICLE_ID;

-- Verification
SELECT
  COUNT(*)                                                                 AS TOTAL,
  COUNT_IF(VEHICLE_SUBTYPE = 'DRY')                                        AS DRY_CNT,
  COUNT_IF(VEHICLE_SUBTYPE = 'REEFER')                                     AS REEFER_CNT,
  COUNT_IF(VEHICLE_SUBTYPE = 'FLAT')                                       AS FLAT_CNT,
  COUNT_IF(VEHICLE_SUBTYPE = 'TANKER')                                     AS TANKER_CNT,
  COUNT_IF(HAZMAT = TRUE)                                                  AS HAZMAT_CNT,
  ROUND(AVG(WEIGHT_TONS), 2)                                               AS AVG_WEIGHT
FROM FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.VW_FLEET_HGV_PROFILE
WHERE OPERATING_MODE = 'trucking';
