-- Extend DIM_FLEET with HGV-specific attributes for Asset Velocity v2 (smart reposition)
-- These columns feed ORS profile_params (matrix/isochrone/optimization) and VROOM
-- skills/capacity. Synthetic data is regenerated by Data Studio, so a companion
-- view (VW_FLEET_HGV_PROFILE) is provided that COALESCEs against deterministic
-- defaults derived from HASH(VEHICLE_ID) + OPERATING_MODE so the page works even
-- after a fresh regeneration.

ALTER SESSION SET query_tag = '{"origin":"sf_sit-is-fleet","name":"oss-route-optimization","version":{"major":1,"minor":1},"attributes":{"is_quickstart":1,"source":"sql"}}';

-- Friction-log F4 (secondary): drop the dependent view BEFORE adding columns
-- to the underlying table. Without this, the next ors_control_app boot
-- fails with `View definition for V_DIM_FLEET_CURRENT declared 13 column(s),
-- but view query produces 20 column(s)`. init.ts will recreate the view
-- with the correct shape on its next run.
DROP VIEW IF EXISTS SYNTHETIC_DATASETS.UNIFIED.V_DIM_FLEET_CURRENT;

ALTER TABLE SYNTHETIC_DATASETS.UNIFIED.DIM_FLEET ADD COLUMN IF NOT EXISTS WEIGHT_TONS    NUMBER(6,2);
ALTER TABLE SYNTHETIC_DATASETS.UNIFIED.DIM_FLEET ADD COLUMN IF NOT EXISTS HEIGHT_M       NUMBER(4,2);
ALTER TABLE SYNTHETIC_DATASETS.UNIFIED.DIM_FLEET ADD COLUMN IF NOT EXISTS LENGTH_M       NUMBER(4,2);
ALTER TABLE SYNTHETIC_DATASETS.UNIFIED.DIM_FLEET ADD COLUMN IF NOT EXISTS WIDTH_M        NUMBER(4,2);
ALTER TABLE SYNTHETIC_DATASETS.UNIFIED.DIM_FLEET ADD COLUMN IF NOT EXISTS AXLELOAD_T     NUMBER(4,2);
ALTER TABLE SYNTHETIC_DATASETS.UNIFIED.DIM_FLEET ADD COLUMN IF NOT EXISTS HAZMAT         BOOLEAN;
ALTER TABLE SYNTHETIC_DATASETS.UNIFIED.DIM_FLEET ADD COLUMN IF NOT EXISTS VEHICLE_SUBTYPE VARCHAR(16); -- DRY | REEFER | FLAT | TANKER | NULL

-- Legacy backfill (catalog-driven, NULL-only). The Data Studio generator now
-- stamps these columns at write time from FLEET_INTELLIGENCE.CORE.DIM_VEHICLE_PROFILE,
-- so this only fills pre-catalog rows. No CASE-on-vehicle-type: dimensions come
-- from the catalog row for the vehicle's VEHICLE_TYPE; the subtype is assigned
-- by HASH bucket over the catalog's SUBTYPE_DIST (modes without a distribution
-- contribute no rows and keep VEHICLE_SUBTYPE = NULL).
UPDATE SYNTHETIC_DATASETS.UNIFIED.DIM_FLEET f
   SET WEIGHT_TONS = COALESCE(f.WEIGHT_TONS, vp.WEIGHT_TONS),
       HEIGHT_M    = COALESCE(f.HEIGHT_M,    vp.HEIGHT_M),
       LENGTH_M    = COALESCE(f.LENGTH_M,    vp.LENGTH_M),
       WIDTH_M     = COALESCE(f.WIDTH_M,     vp.WIDTH_M),
       AXLELOAD_T  = COALESCE(f.AXLELOAD_T,  vp.AXLELOAD_T)
  FROM FLEET_INTELLIGENCE.CORE.DIM_VEHICLE_PROFILE vp
 WHERE vp.VEHICLE_TYPE = f.VEHICLE_TYPE;

-- Subtype backfill via HASH bucket over the catalog distribution (NULL rows only).
UPDATE SYNTHETIC_DATASETS.UNIFIED.DIM_FLEET f
   SET VEHICLE_SUBTYPE = sr.SUBTYPE
  FROM (
    SELECT vp.VEHICLE_TYPE,
           d.value:subtype::string AS SUBTYPE,
           SUM(d.value:pct::number) OVER (PARTITION BY vp.VEHICLE_TYPE ORDER BY d.index)
             - d.value:pct::number AS CUM_LO,
           SUM(d.value:pct::number) OVER (PARTITION BY vp.VEHICLE_TYPE ORDER BY d.index) AS CUM_HI
    FROM FLEET_INTELLIGENCE.CORE.DIM_VEHICLE_PROFILE vp,
         LATERAL FLATTEN(input => vp.SUBTYPE_DIST) d
  ) sr
 WHERE sr.VEHICLE_TYPE = f.VEHICLE_TYPE
   AND f.VEHICLE_SUBTYPE IS NULL
   AND MOD(ABS(HASH(f.VEHICLE_ID)), 100) >= sr.CUM_LO
   AND MOD(ABS(HASH(f.VEHICLE_ID)), 100) <  sr.CUM_HI;

-- Hazmat defaults to FALSE for any remaining legacy NULLs (the generator sets
-- the real per-vehicle value at write time).
UPDATE SYNTHETIC_DATASETS.UNIFIED.DIM_FLEET
   SET HAZMAT = FALSE
 WHERE HAZMAT IS NULL;

-- Recreate dataset-scoped projection view immediately (do not rely on the next
-- ors_control_app boot). extend-dim-fleet-hgv.sql drops this view above.
CREATE OR REPLACE VIEW SYNTHETIC_DATASETS.UNIFIED.V_DIM_FLEET_CURRENT
COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-build-routing-solution","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"app"}}'
AS
SELECT f.*
FROM SYNTHETIC_DATASETS.UNIFIED.DIM_FLEET f
JOIN FLEET_INTELLIGENCE.CORE.DIM_DATASETS d
  ON d.DATASET_ID = f.JOB_ID
 AND d.REGION = f.REGION
 AND d.VEHICLE_TYPE = f.VEHICLE_TYPE
 AND d.IS_ACTIVE = TRUE;

-- Resilient view: works even after Data Studio regenerates DIM_FLEET. The
-- physical columns are now populated by the generator from the catalog; this
-- view COALESCEs against FLEET_INTELLIGENCE.CORE.DIM_VEHICLE_PROFILE so callers
-- always get well-defined values with NO CASE-on-vehicle-type branching.
CREATE OR REPLACE VIEW FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.VW_FLEET_HGV_PROFILE
COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-route-optimization","version":{"major":1,"minor":1},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
WITH filtered AS (
  SELECT f.*, MOD(ABS(HASH(f.VEHICLE_ID)), 100) AS BKT
  FROM SYNTHETIC_DATASETS.UNIFIED.V_DIM_FLEET_CURRENT f
),
subtype_ranges AS (
  SELECT vp.VEHICLE_TYPE,
         d.value:subtype::string AS SUBTYPE,
         SUM(d.value:pct::number) OVER (PARTITION BY vp.VEHICLE_TYPE ORDER BY d.index)
           - d.value:pct::number AS CUM_LO,
         SUM(d.value:pct::number) OVER (PARTITION BY vp.VEHICLE_TYPE ORDER BY d.index) AS CUM_HI
  FROM FLEET_INTELLIGENCE.CORE.DIM_VEHICLE_PROFILE vp,
       LATERAL FLATTEN(input => vp.SUBTYPE_DIST) d
)
SELECT
  f.VEHICLE_ID,
  f.REGION,
  f.VEHICLE_TYPE,
  f.ORS_PROFILE,
  f.OPERATING_MODE,
  COALESCE(f.VEHICLE_SUBTYPE, sr.SUBTYPE)   AS VEHICLE_SUBTYPE,
  COALESCE(f.HAZMAT, FALSE)                 AS HAZMAT,
  COALESCE(f.WEIGHT_TONS, vp.WEIGHT_TONS)   AS WEIGHT_TONS,
  COALESCE(f.HEIGHT_M,    vp.HEIGHT_M)      AS HEIGHT_M,
  COALESCE(f.LENGTH_M,    vp.LENGTH_M)      AS LENGTH_M,
  COALESCE(f.WIDTH_M,     vp.WIDTH_M)       AS WIDTH_M,
  COALESCE(f.AXLELOAD_T,  vp.AXLELOAD_T)    AS AXLELOAD_T
FROM filtered f
LEFT JOIN FLEET_INTELLIGENCE.CORE.DIM_VEHICLE_PROFILE vp
  ON vp.VEHICLE_TYPE = f.VEHICLE_TYPE
LEFT JOIN subtype_ranges sr
  ON sr.VEHICLE_TYPE = f.VEHICLE_TYPE
 AND f.BKT >= sr.CUM_LO AND f.BKT < sr.CUM_HI;

-- Verification
SELECT
  COUNT(*)                                                                 AS TOTAL,
  COUNT_IF(VEHICLE_SUBTYPE = 'DRY')                                        AS DRY_CNT,
  COUNT_IF(VEHICLE_SUBTYPE = 'REEFER')                                     AS REEFER_CNT,
  COUNT_IF(VEHICLE_SUBTYPE = 'FLAT')                                       AS FLAT_CNT,
  COUNT_IF(VEHICLE_SUBTYPE = 'TANKER')                                     AS TANKER_CNT,
  COUNT_IF(HAZMAT = TRUE)                                                  AS HAZMAT_CNT,
  ROUND(AVG(WEIGHT_TONS), 2)                                               AS AVG_WEIGHT
FROM FLEET_INTELLIGENCE.ROUTE_OPTIMIZATION.VW_FLEET_HGV_PROFILE
WHERE OPERATING_MODE = 'trucking';
