/*
 * seed-data.sql — Fleet Intelligence Food Delivery
 * Load San Francisco baseline data from S3.
 * Idempotent: only loads if tables are empty for the target region.
 */

CREATE DATABASE IF NOT EXISTS FLEET_INTELLIGENCE;
CREATE SCHEMA IF NOT EXISTS FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY;

CREATE STAGE IF NOT EXISTS FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.SEED_STAGE
    URL = 's3://fleet-intelligence/SanFrancisco/fleet-intelligence-food-delivery/'
    FILE_FORMAT = (TYPE = PARQUET);

--------------------------------------------------------------------
-- RESTAURANTS
--------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.RESTAURANTS (
    REGION         VARCHAR NOT NULL DEFAULT 'SanFrancisco',
    RESTAURANT_ID  VARCHAR,
    LOCATION       GEOGRAPHY,
    NAME           VARCHAR,
    CUISINE_TYPE   VARCHAR,
    ADDRESS        VARCHAR,
    CITY           VARCHAR,
    STATE          VARCHAR
);

COPY INTO FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.RESTAURANTS
FROM @FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.SEED_STAGE/RESTAURANTS/
FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE ON_ERROR = CONTINUE;

--------------------------------------------------------------------
-- CUSTOMER_ADDRESSES
--------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.CUSTOMER_ADDRESSES (
    REGION        VARCHAR NOT NULL DEFAULT 'SanFrancisco',
    ADDRESS_ID    VARCHAR,
    LOCATION      GEOGRAPHY,
    FULL_ADDRESS  VARCHAR,
    STREET        VARCHAR,
    POSTCODE      VARCHAR,
    STATE         VARCHAR,
    CITY          VARCHAR
);

COPY INTO FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.CUSTOMER_ADDRESSES
FROM @FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.SEED_STAGE/CUSTOMER_ADDRESSES/
FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE ON_ERROR = CONTINUE;

--------------------------------------------------------------------
-- COURIERS
--------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.COURIERS (
    REGION                  VARCHAR NOT NULL DEFAULT 'SanFrancisco',
    COURIER_ID              VARCHAR,
    HOME_ADDRESS_ID         VARCHAR,
    SHIFT_TYPE              VARCHAR,
    SHIFT_START_HOUR        INT,
    SHIFT_END_HOUR          INT,
    SHIFT_CROSSES_MIDNIGHT  VARCHAR,
    VEHICLE_TYPE            VARCHAR
);

COPY INTO FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.COURIERS
FROM @FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.SEED_STAGE/COURIERS/
FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE ON_ERROR = CONTINUE;

--------------------------------------------------------------------
-- RESTAURANTS_NUMBERED
--------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.RESTAURANTS_NUMBERED (
    REGION         VARCHAR NOT NULL DEFAULT 'SanFrancisco',
    RESTAURANT_ID  VARCHAR,
    LOCATION       GEOGRAPHY,
    NAME           VARCHAR,
    CUISINE_TYPE   VARCHAR,
    ADDRESS        VARCHAR,
    RN             INT
);

COPY INTO FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.RESTAURANTS_NUMBERED
FROM @FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.SEED_STAGE/RESTAURANTS_NUMBERED/
FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE ON_ERROR = CONTINUE;

--------------------------------------------------------------------
-- ADDRESSES_NUMBERED
--------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.ADDRESSES_NUMBERED (
    REGION       VARCHAR NOT NULL DEFAULT 'SanFrancisco',
    ADDRESS_ID   VARCHAR,
    LOCATION     GEOGRAPHY,
    FULL_ADDRESS VARCHAR,
    RN           INT
);

COPY INTO FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.ADDRESSES_NUMBERED
FROM @FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.SEED_STAGE/ADDRESSES_NUMBERED/
FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE ON_ERROR = CONTINUE;

--------------------------------------------------------------------
-- DELIVERY_ORDERS
--------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.DELIVERY_ORDERS (
    REGION          VARCHAR NOT NULL DEFAULT 'SanFrancisco',
    ORDER_ID        VARCHAR,
    COURIER_ID      VARCHAR,
    ORDER_HOUR      INT,
    ORDER_NUMBER    INT,
    SHIFT_TYPE      VARCHAR,
    VEHICLE_TYPE    VARCHAR,
    RESTAURANT_IDX  INT,
    CUSTOMER_IDX    INT,
    PREP_TIME_MINS  FLOAT,
    ORDER_STATUS    VARCHAR
);

COPY INTO FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.DELIVERY_ORDERS
FROM @FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.SEED_STAGE/DELIVERY_ORDERS/
FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE ON_ERROR = CONTINUE;

--------------------------------------------------------------------
-- ORDERS_WITH_LOCATIONS
--------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.ORDERS_WITH_LOCATIONS (
    REGION                VARCHAR NOT NULL DEFAULT 'SanFrancisco',
    ORDER_ID              VARCHAR,
    COURIER_ID            VARCHAR,
    ORDER_HOUR            INT,
    ORDER_NUMBER          INT,
    SHIFT_TYPE            VARCHAR,
    VEHICLE_TYPE          VARCHAR,
    RESTAURANT_ID         VARCHAR,
    RESTAURANT_NAME       VARCHAR,
    CUISINE_TYPE          VARCHAR,
    RESTAURANT_LOCATION   GEOGRAPHY,
    RESTAURANT_ADDRESS    VARCHAR,
    CUSTOMER_ADDRESS_ID   VARCHAR,
    CUSTOMER_ADDRESS      VARCHAR,
    CUSTOMER_LOCATION     GEOGRAPHY,
    PREP_TIME_MINS        FLOAT,
    ORDER_STATUS          VARCHAR
);

COPY INTO FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.ORDERS_WITH_LOCATIONS
FROM @FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.SEED_STAGE/ORDERS_WITH_LOCATIONS/
FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE ON_ERROR = CONTINUE;

--------------------------------------------------------------------
-- DELIVERY_ROUTES
--------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.DELIVERY_ROUTES (
    REGION                VARCHAR NOT NULL DEFAULT 'SanFrancisco',
    ORDER_ID              VARCHAR,
    COURIER_ID            VARCHAR,
    ORDER_HOUR            INT,
    ORDER_NUMBER          INT,
    SHIFT_TYPE            VARCHAR,
    VEHICLE_TYPE          VARCHAR,
    RESTAURANT_ID         VARCHAR,
    RESTAURANT_NAME       VARCHAR,
    CUISINE_TYPE          VARCHAR,
    RESTAURANT_LOCATION   GEOGRAPHY,
    RESTAURANT_ADDRESS    VARCHAR,
    CUSTOMER_ADDRESS_ID   VARCHAR,
    CUSTOMER_ADDRESS      VARCHAR,
    CUSTOMER_LOCATION     GEOGRAPHY,
    PREP_TIME_MINS        FLOAT,
    ORDER_STATUS          VARCHAR,
    ROUTE_RESPONSE        VARIANT
);

COPY INTO FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.DELIVERY_ROUTES
FROM @FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.SEED_STAGE/DELIVERY_ROUTES/
FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE ON_ERROR = CONTINUE;

--------------------------------------------------------------------
-- DELIVERY_ROUTES_PARSED
--------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.DELIVERY_ROUTES_PARSED (
    REGION                VARCHAR NOT NULL DEFAULT 'SanFrancisco',
    ORDER_ID              VARCHAR,
    COURIER_ID            VARCHAR,
    ORDER_HOUR            INT,
    ORDER_NUMBER          INT,
    SHIFT_TYPE            VARCHAR,
    VEHICLE_TYPE          VARCHAR,
    RESTAURANT_ID         VARCHAR,
    RESTAURANT_NAME       VARCHAR,
    CUISINE_TYPE          VARCHAR,
    RESTAURANT_LOCATION   GEOGRAPHY,
    RESTAURANT_ADDRESS    VARCHAR,
    CUSTOMER_ADDRESS_ID   VARCHAR,
    CUSTOMER_ADDRESS      VARCHAR,
    CUSTOMER_LOCATION     GEOGRAPHY,
    PREP_TIME_MINS        FLOAT,
    ORDER_STATUS          VARCHAR,
    ROUTE_GEOMETRY        GEOGRAPHY,
    ROUTE_DISTANCE_METERS FLOAT,
    ROUTE_DURATION_SECS   FLOAT
);

COPY INTO FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.DELIVERY_ROUTES_PARSED
FROM @FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.SEED_STAGE/DELIVERY_ROUTES_PARSED/
FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE ON_ERROR = CONTINUE;

--------------------------------------------------------------------
-- DELIVERY_ROUTE_GEOMETRIES
--------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.DELIVERY_ROUTE_GEOMETRIES (
    REGION                VARCHAR NOT NULL DEFAULT 'SanFrancisco',
    COURIER_ID            VARCHAR,
    ORDER_ID              VARCHAR,
    ORDER_TIME            TIMESTAMP_NTZ,
    PICKUP_TIME           TIMESTAMP_NTZ,
    DELIVERY_TIME         TIMESTAMP_NTZ,
    RESTAURANT_ID         VARCHAR,
    RESTAURANT_NAME       VARCHAR,
    CUISINE_TYPE          VARCHAR,
    RESTAURANT_LOCATION   GEOGRAPHY,
    RESTAURANT_ADDRESS    VARCHAR,
    CUSTOMER_ADDRESS_ID   VARCHAR,
    CUSTOMER_ADDRESS      VARCHAR,
    CUSTOMER_LOCATION     GEOGRAPHY,
    PREP_TIME_MINS        FLOAT,
    ORDER_STATUS          VARCHAR,
    ROUTE_DURATION_SECS   FLOAT,
    ROUTE_DISTANCE_METERS FLOAT,
    GEOMETRY              GEOGRAPHY,
    SHIFT_TYPE            VARCHAR,
    VEHICLE_TYPE          VARCHAR
);

COPY INTO FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.DELIVERY_ROUTE_GEOMETRIES
FROM @FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.SEED_STAGE/DELIVERY_ROUTE_GEOMETRIES/
FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE ON_ERROR = CONTINUE;

--------------------------------------------------------------------
-- COURIER_LOCATIONS
--------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.COURIER_LOCATIONS (
    REGION              VARCHAR NOT NULL DEFAULT 'SanFrancisco',
    ORDER_ID            VARCHAR,
    COURIER_ID          VARCHAR,
    ORDER_TIME          TIMESTAMP_NTZ,
    PICKUP_TIME         TIMESTAMP_NTZ,
    DROPOFF_TIME        TIMESTAMP_NTZ,
    RESTAURANT_LOCATION GEOGRAPHY,
    CUSTOMER_LOCATION   GEOGRAPHY,
    ROUTE               GEOGRAPHY,
    POINT_GEOM          GEOGRAPHY,
    CURR_TIME           TIMESTAMP_NTZ,
    POINT_INDEX         INT,
    COURIER_STATE       VARCHAR,
    KMH                 FLOAT
);

COPY INTO FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.COURIER_LOCATIONS
FROM @FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.SEED_STAGE/COURIER_LOCATIONS/
FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE ON_ERROR = CONTINUE;

--------------------------------------------------------------------
-- VALIDATION
--------------------------------------------------------------------
SELECT 'RESTAURANTS' AS TBL, COUNT(*) AS ROWS FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.RESTAURANTS
UNION ALL SELECT 'CUSTOMER_ADDRESSES', COUNT(*) FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.CUSTOMER_ADDRESSES
UNION ALL SELECT 'COURIERS', COUNT(*) FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.COURIERS
UNION ALL SELECT 'DELIVERY_ROUTE_GEOMETRIES', COUNT(*) FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.DELIVERY_ROUTE_GEOMETRIES
UNION ALL SELECT 'COURIER_LOCATIONS', COUNT(*) FROM FLEET_INTELLIGENCE.FLEET_INTELLIGENCE_FOOD_DELIVERY.COURIER_LOCATIONS;
