-- =============================================================================
-- Dwell & Congestion Analysis - Complete SQL Pipeline
-- Target: FLEET_INTELLIGENCE.DWELL_ANALYSIS
-- Source: SYNTHETIC_DATASETS.UNIFIED (via projection views)
-- =============================================================================

-- Query Tag (set at the start of every session)
ALTER SESSION SET query_tag = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';

-- Step 1: Infrastructure
CREATE DATABASE IF NOT EXISTS FLEET_INTELLIGENCE
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';
CREATE WAREHOUSE IF NOT EXISTS ROUTING_ANALYTICS
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';
CREATE SCHEMA IF NOT EXISTS FLEET_INTELLIGENCE.DWELL_ANALYSIS
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';

-- Step 1b: Skill Configuration Table
-- Single-row config controlling which vehicle type and region this skill processes.
-- Update via: UPDATE FLEET_INTELLIGENCE.DWELL_ANALYSIS.CONFIG SET VEHICLE_TYPE='escooter', REGION='SanFrancisco';
CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.DWELL_ANALYSIS.CONFIG (
    VEHICLE_TYPE VARCHAR NOT NULL,
    REGION       VARCHAR NOT NULL
)
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';
MERGE INTO FLEET_INTELLIGENCE.DWELL_ANALYSIS.CONFIG tgt
USING (SELECT 'ebike' AS VEHICLE_TYPE, 'SanFrancisco' AS REGION) src
ON TRUE
WHEN NOT MATCHED THEN INSERT (VEHICLE_TYPE, REGION) VALUES (src.VEHICLE_TYPE, src.REGION);

-- Step 2: Data Studio Projection Views
-- These views read from SYNTHETIC_DATASETS.UNIFIED, filtered by CONFIG table.

CREATE OR REPLACE VIEW FLEET_INTELLIGENCE.DWELL_ANALYSIS.VW_VEHICLE_TELEMETRY
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT
    t.TELEMETRY_ID,
    t.VEHICLE_ID,
    t.TRIP_ID,
    t.TS,
    t.LATITUDE,
    t.LONGITUDE,
    t.SPEED_KMH,
    t.HEADING_DEG,
    t.GPS_ACCURACY_M,
    CASE
        WHEN t.STATUS = 'DWELL_ORIGIN' AND t.LOCATION_TYPE IN ('WAREHOUSE', 'LOGISTICS') THEN 'DWELL_WAREHOUSE'
        WHEN t.STATUS = 'DWELL_ORIGIN' AND t.LOCATION_TYPE IN ('RESTAURANT', 'STORE', 'ADDRESS') THEN 'DWELL_STORE'
        WHEN t.STATUS = 'DWELL_ORIGIN' THEN 'DWELL_DESTINATION'
        WHEN t.STATUS = 'DWELL_REST' THEN 'DWELL_REST_STOP'
        WHEN t.STATUS = 'DWELL_RECHARGE' THEN 'DWELL_REST_STOP'
        WHEN t.STATUS = 'DWELL_DETOUR' THEN 'DWELL_DETOUR'
        ELSE t.STATUS
    END AS STATUS,
    t.IS_SPEEDING,
    t.IS_HOS_VIOLATION,
    t.IS_DETOUR,
    t.LOCATION_ID,
    t.LOCATION_TYPE,
    t.POINT_INDEX,
    t.ODOMETER_KM,
    t.VEHICLE_TYPE,
    t.REGION
FROM SYNTHETIC_DATASETS.UNIFIED.FACT_VEHICLE_TELEMETRY t
WHERE t.VEHICLE_TYPE = (SELECT VEHICLE_TYPE FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.CONFIG LIMIT 1)
  AND t.REGION = (SELECT REGION FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.CONFIG LIMIT 1)
QUALIFY ROW_NUMBER() OVER (PARTITION BY t.TELEMETRY_ID ORDER BY t.TS) = 1;

CREATE OR REPLACE VIEW FLEET_INTELLIGENCE.DWELL_ANALYSIS.VW_VEHICLE_FLEET
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT
    f.VEHICLE_ID,
    f.HOME_LOCATION_ID AS HOME_BASE_ID,
    f.DRIVER_PROFILE,
    f.OPERATING_MODE,
    f.SHIFT_TYPE,
    f.BASE_SPEED_KMH,
    f.VEHICLE_TYPE,
    f.REGION,
    f.REGION AS HOME_BASE_NAME
FROM SYNTHETIC_DATASETS.UNIFIED.DIM_FLEET f
WHERE f.VEHICLE_TYPE = (SELECT VEHICLE_TYPE FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.CONFIG LIMIT 1)
  AND f.REGION = (SELECT REGION FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.CONFIG LIMIT 1)
QUALIFY ROW_NUMBER() OVER (PARTITION BY f.VEHICLE_ID ORDER BY f.VEHICLE_ID) = 1;

CREATE OR REPLACE VIEW FLEET_INTELLIGENCE.DWELL_ANALYSIS.VW_DESTINATIONS
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT
    p.LOCATION_ID AS ID,
    p.NAME,
    p.LOCATION_TYPE,
    p.CATEGORY AS BASIC_CATEGORY,
    p.REGION AS CITY,
    p.LAT,
    p.LNG,
    p.POINT_GEOM AS GEOMETRY,
    p.REGION
FROM SYNTHETIC_DATASETS.UNIFIED.DIM_POIS p
WHERE p.LOCATION_TYPE NOT IN ('REST_STOP')
  AND p.REGION = (SELECT REGION FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.CONFIG LIMIT 1)
QUALIFY ROW_NUMBER() OVER (PARTITION BY p.LOCATION_ID ORDER BY p.NAME) = 1;

CREATE OR REPLACE VIEW FLEET_INTELLIGENCE.DWELL_ANALYSIS.VW_REST_STOPS
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT
    p.LOCATION_ID AS REST_STOP_ID,
    p.NAME,
    p.CATEGORY AS REST_TYPE,
    p.LAT,
    p.LNG,
    p.POINT_GEOM AS CENTER_POINT,
    p.REGION
FROM SYNTHETIC_DATASETS.UNIFIED.DIM_POIS p
WHERE p.LOCATION_TYPE = 'REST_STOP'
  AND p.REGION = (SELECT REGION FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.CONFIG LIMIT 1)
QUALIFY ROW_NUMBER() OVER (PARTITION BY p.LOCATION_ID ORDER BY p.NAME) = 1;

CREATE OR REPLACE VIEW FLEET_INTELLIGENCE.DWELL_ANALYSIS.VW_TRIP_SCHEDULE
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT
    s.TRIP_ID AS SCHEDULE_ID,
    s.VEHICLE_ID,
    s.TRIP_TYPE,
    s.ORIGIN_ID,
    s.DESTINATION_ID AS DEST_ID,
    s.ROUTE_VARIATION,
    s.ROUTE_DEVIATION_FACTOR,
    s.ROUTE_DISTANCE_M,
    s.ROUTE_DURATION_SEC,
    s.SCHEDULED_START,
    s.ORS_PROFILE,
    s.REGION
FROM SYNTHETIC_DATASETS.UNIFIED.DIM_TRIP_SCHEDULE s
WHERE s.REGION = (SELECT REGION FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.CONFIG LIMIT 1);

-- Step 3: Geofence Reference Table (destinations + rest stops with buffer radii)
CREATE OR REPLACE TABLE FLEET_INTELLIGENCE.DWELL_ANALYSIS.GEOFENCE_POLYGONS AS
SELECT
    ID AS LOCATION_ID, NAME, LOCATION_TYPE, 'DESTINATION' AS SOURCE,
    LAT, LNG, GEOMETRY AS CENTER_POINT,
    IFF(LOCATION_TYPE = 'WAREHOUSE', 200, 100) AS BUFFER_RADIUS_M
FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.VW_DESTINATIONS
UNION ALL
SELECT
    REST_STOP_ID, NAME, REST_TYPE, 'REST_STOP',
    LAT, LNG, CENTER_POINT,
    150 AS BUFFER_RADIUS_M
FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.VW_REST_STOPS;
ALTER TABLE FLEET_INTELLIGENCE.DWELL_ANALYSIS.GEOFENCE_POLYGONS SET COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';

-- Step 4: SLA Thresholds Configuration (idempotent)
CREATE TABLE IF NOT EXISTS FLEET_INTELLIGENCE.DWELL_ANALYSIS.SLA_THRESHOLDS (
    LOCATION_TYPE VARCHAR, WARNING_MINUTES NUMBER, CRITICAL_MINUTES NUMBER
)
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';
INSERT INTO FLEET_INTELLIGENCE.DWELL_ANALYSIS.SLA_THRESHOLDS
    (LOCATION_TYPE, WARNING_MINUTES, CRITICAL_MINUTES)
SELECT column1, column2, column3 FROM VALUES
    ('WAREHOUSE', 60, 120),
    ('DESTINATION', 30, 60),
    ('REST_STOP', 45, 90),
    ('STORE', 20, 45),
    ('DETOUR', 15, 30)
WHERE NOT EXISTS (
    SELECT 1 FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.SLA_THRESHOLDS
);

-- Step 5: Dynamic Table Layer 1 - State Change Detection (LAG)
CREATE OR REPLACE DYNAMIC TABLE FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_STATE_CHANGES
  TARGET_LAG = '5 minutes'
  WAREHOUSE = ROUTING_ANALYTICS
  COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT
    TELEMETRY_ID, VEHICLE_ID, TRIP_ID, TS, LATITUDE, LONGITUDE,
    SPEED_KMH, STATUS, LOCATION_ID, LOCATION_TYPE,
    LAG(STATUS) OVER (PARTITION BY VEHICLE_ID ORDER BY TS) AS PREV_STATUS,
    CASE WHEN STATUS != LAG(STATUS) OVER (PARTITION BY VEHICLE_ID ORDER BY TS)
         THEN 1 ELSE 0 END AS IS_STATE_CHANGE
FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.VW_VEHICLE_TELEMETRY
WHERE STATUS IN ('MOVING','DWELL_WAREHOUSE','DWELL_DESTINATION',
                 'DWELL_REST_STOP','DWELL_STORE','DWELL_DETOUR','IDLE');

-- Step 6: Dynamic Table Layer 2 - Dwell Sessionization (CONDITIONAL_CHANGE_EVENT)
CREATE OR REPLACE DYNAMIC TABLE FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_DWELL_SESSIONS
  TARGET_LAG = '5 minutes'
  WAREHOUSE = ROUTING_ANALYTICS
  COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
WITH sessions AS (
  SELECT *,
    CONDITIONAL_CHANGE_EVENT(STATUS) OVER (PARTITION BY VEHICLE_ID ORDER BY TS) AS SESSION_ID
  FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_STATE_CHANGES
)
SELECT
  VEHICLE_ID, SESSION_ID, TRIP_ID, STATUS, LOCATION_ID,
  MIN(TS) AS SESSION_START, MAX(TS) AS SESSION_END,
  DATEDIFF('second', MIN(TS), MAX(TS)) AS DWELL_SECONDS,
  ROUND(DATEDIFF('second', MIN(TS), MAX(TS)) / 60.0, 1) AS DWELL_MINUTES,
  COUNT(*) AS PING_COUNT,
  ROUND(AVG(LATITUDE), 6) AS AVG_LAT,
  ROUND(AVG(LONGITUDE), 6) AS AVG_LNG,
  H3_LATLNG_TO_CELL(AVG(LATITUDE), AVG(LONGITUDE), 7)::VARCHAR AS H3_CELL_R7
FROM sessions
WHERE STATUS LIKE 'DWELL%' OR STATUS = 'IDLE'
GROUP BY VEHICLE_ID, SESSION_ID, TRIP_ID, STATUS, LOCATION_ID;

-- Step 7: Dynamic Table Layer 3 - Enriched Dwell (location + fleet metadata)
CREATE OR REPLACE DYNAMIC TABLE FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_DWELL_ENRICHED
  TARGET_LAG = '5 minutes'
  WAREHOUSE = ROUTING_ANALYTICS
  COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT
  s.VEHICLE_ID, s.SESSION_ID, s.TRIP_ID, s.STATUS, s.LOCATION_ID,
  s.SESSION_START, s.SESSION_END, s.DWELL_SECONDS, s.DWELL_MINUTES,
  s.PING_COUNT, s.AVG_LAT, s.AVG_LNG, s.H3_CELL_R7,
  COALESCE(d.NAME, rs.NAME, 'Unknown') AS LOCATION_NAME,
  COALESCE(d.CITY, 'N/A') AS CITY,
  COALESCE(d.BASIC_CATEGORY, rs.REST_TYPE, s.STATUS) AS FACILITY_TYPE,
  COALESCE(d.LOCATION_TYPE, 'REST_STOP') AS LOC_TYPE,
  tf.HOME_BASE_NAME, tf.OPERATING_MODE, tf.DRIVER_PROFILE
FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_DWELL_SESSIONS s
LEFT JOIN FLEET_INTELLIGENCE.DWELL_ANALYSIS.VW_DESTINATIONS d ON s.LOCATION_ID = d.ID
LEFT JOIN FLEET_INTELLIGENCE.DWELL_ANALYSIS.VW_REST_STOPS rs ON s.LOCATION_ID = rs.REST_STOP_ID
LEFT JOIN FLEET_INTELLIGENCE.DWELL_ANALYSIS.VW_VEHICLE_FLEET tf ON s.VEHICLE_ID = tf.VEHICLE_ID;

-- Step 8: H3 Congestion Heatmap
CREATE OR REPLACE DYNAMIC TABLE FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_H3_CONGESTION
  TARGET_LAG = '10 minutes'
  WAREHOUSE = ROUTING_ANALYTICS
  COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT
  H3_CELL_R7,
  DATE_TRUNC('hour', SESSION_START) AS HOUR_BUCKET,
  COUNT(DISTINCT VEHICLE_ID) AS VEHICLE_COUNT,
  COUNT(*) AS SESSION_COUNT,
  ROUND(AVG(DWELL_MINUTES), 1) AS AVG_DWELL_MIN,
  ROUND(SUM(DWELL_MINUTES), 0) AS TOTAL_DWELL_MIN
FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_DWELL_ENRICHED
WHERE STATUS LIKE 'DWELL%'
GROUP BY H3_CELL_R7, HOUR_BUCKET;

-- Step 9: SLA Alerts
CREATE OR REPLACE DYNAMIC TABLE FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_SLA_ALERTS
  TARGET_LAG = '5 minutes'
  WAREHOUSE = ROUTING_ANALYTICS
  COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT
  e.VEHICLE_ID, e.SESSION_ID, e.STATUS, e.LOCATION_ID,
  e.SESSION_START, e.SESSION_END, e.DWELL_SECONDS, e.DWELL_MINUTES,
  e.PING_COUNT, e.AVG_LAT, e.AVG_LNG, e.H3_CELL_R7,
  e.LOCATION_NAME, e.CITY, e.FACILITY_TYPE, e.LOC_TYPE,
  e.HOME_BASE_NAME, e.OPERATING_MODE, e.DRIVER_PROFILE,
  t.WARNING_MINUTES, t.CRITICAL_MINUTES,
  CASE
    WHEN e.DWELL_MINUTES >= t.CRITICAL_MINUTES THEN 'CRITICAL'
    WHEN e.DWELL_MINUTES >= t.WARNING_MINUTES THEN 'WARNING'
  END AS SLA_STATUS,
  ROUND(e.DWELL_MINUTES - t.WARNING_MINUTES, 1) AS MINUTES_OVER_WARNING
FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_DWELL_ENRICHED e
JOIN FLEET_INTELLIGENCE.DWELL_ANALYSIS.SLA_THRESHOLDS t
  ON REPLACE(e.STATUS, 'DWELL_', '') = t.LOCATION_TYPE
WHERE e.DWELL_MINUTES >= t.WARNING_MINUTES AND e.STATUS LIKE 'DWELL%';

-- Step 10: Facility Utilization
CREATE OR REPLACE DYNAMIC TABLE FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_FACILITY_UTILIZATION
  TARGET_LAG = '10 minutes'
  WAREHOUSE = ROUTING_ANALYTICS
  COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT
  LOCATION_ID, LOCATION_NAME, CITY, FACILITY_TYPE, LOC_TYPE,
  DATE_TRUNC('day', SESSION_START)::DATE AS VISIT_DATE,
  COUNT(DISTINCT VEHICLE_ID) AS UNIQUE_VEHICLES,
  COUNT(*) AS TOTAL_SESSIONS,
  ROUND(SUM(DWELL_MINUTES), 0) AS TOTAL_DWELL_MIN,
  ROUND(AVG(DWELL_MINUTES), 1) AS AVG_DWELL_MIN,
  ROUND(MAX(DWELL_MINUTES), 1) AS MAX_DWELL_MIN,
  ROUND(SUM(DWELL_MINUTES) / 60.0, 1) AS TOTAL_DWELL_HOURS
FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_DWELL_ENRICHED
WHERE STATUS LIKE 'DWELL%'
GROUP BY LOCATION_ID, LOCATION_NAME, CITY, FACILITY_TYPE, LOC_TYPE, VISIT_DATE;

-- Step 11: Driver Dwell Summary
CREATE OR REPLACE DYNAMIC TABLE FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_DRIVER_DWELL_SUMMARY
  TARGET_LAG = '10 minutes'
  WAREHOUSE = ROUTING_ANALYTICS
  COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT
  e.VEHICLE_ID, e.DRIVER_PROFILE, e.OPERATING_MODE, e.HOME_BASE_NAME,
  COUNT(*) AS TOTAL_DWELL_SESSIONS,
  ROUND(SUM(e.DWELL_MINUTES), 0) AS TOTAL_DWELL_MIN,
  ROUND(SUM(e.DWELL_MINUTES) / 60.0, 1) AS TOTAL_DWELL_HOURS,
  ROUND(AVG(e.DWELL_MINUTES), 1) AS AVG_SESSION_MIN,
  COUNT(DISTINCT e.LOCATION_ID) AS UNIQUE_LOCATIONS,
  SUM(CASE WHEN a.SLA_STATUS IS NOT NULL THEN 1 ELSE 0 END) AS SLA_BREACH_COUNT,
  SUM(CASE WHEN a.SLA_STATUS = 'CRITICAL' THEN 1 ELSE 0 END) AS CRITICAL_BREACH_COUNT
FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_DWELL_ENRICHED e
LEFT JOIN FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_SLA_ALERTS a
  ON e.VEHICLE_ID = a.VEHICLE_ID AND e.SESSION_ID = a.SESSION_ID AND e.STATUS = a.STATUS
WHERE e.STATUS LIKE 'DWELL%'
GROUP BY e.VEHICLE_ID, e.DRIVER_PROFILE, e.OPERATING_MODE, e.HOME_BASE_NAME;

-- Step 12: Daily Trends
CREATE OR REPLACE DYNAMIC TABLE FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_DAILY_TRENDS
  TARGET_LAG = '10 minutes'
  WAREHOUSE = ROUTING_ANALYTICS
  COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
SELECT
  DATE_TRUNC('day', SESSION_START)::DATE AS TREND_DATE,
  COUNT(*) AS TOTAL_SESSIONS,
  COUNT(DISTINCT VEHICLE_ID) AS ACTIVE_VEHICLES,
  ROUND(SUM(DWELL_MINUTES), 0) AS TOTAL_DWELL_MIN,
  ROUND(SUM(DWELL_MINUTES) / 60.0, 0) AS TOTAL_DWELL_HOURS,
  ROUND(AVG(DWELL_MINUTES), 1) AS AVG_SESSION_MIN,
  SUM(CASE WHEN STATUS = 'DWELL_WAREHOUSE' THEN DWELL_MINUTES ELSE 0 END)::INT AS WAREHOUSE_DWELL_MIN,
  SUM(CASE WHEN STATUS = 'DWELL_DESTINATION' THEN DWELL_MINUTES ELSE 0 END)::INT AS DESTINATION_DWELL_MIN,
  SUM(CASE WHEN STATUS = 'DWELL_REST_STOP' THEN DWELL_MINUTES ELSE 0 END)::INT AS REST_STOP_DWELL_MIN,
  SUM(CASE WHEN STATUS = 'DWELL_STORE' THEN DWELL_MINUTES ELSE 0 END)::INT AS STORE_DWELL_MIN,
  COUNT(DISTINCT H3_CELL_R7) AS UNIQUE_H3_CELLS
FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_DWELL_ENRICHED
WHERE STATUS LIKE 'DWELL%'
GROUP BY TREND_DATE;

-- Step 13: SLA Alert Log + Stream + Task
CREATE OR REPLACE TABLE FLEET_INTELLIGENCE.DWELL_ANALYSIS.SLA_ALERT_LOG (
    VEHICLE_ID VARCHAR, SESSION_ID NUMBER, STATUS VARCHAR, LOCATION_ID VARCHAR,
    SESSION_START TIMESTAMP_NTZ, SESSION_END TIMESTAMP_NTZ,
    DWELL_SECONDS NUMBER, DWELL_MINUTES FLOAT, PING_COUNT NUMBER,
    AVG_LAT FLOAT, AVG_LNG FLOAT, H3_CELL_R7 VARCHAR,
    LOCATION_NAME VARCHAR, CITY VARCHAR, FACILITY_TYPE VARCHAR, LOC_TYPE VARCHAR,
    HOME_BASE_NAME VARCHAR, OPERATING_MODE VARCHAR, DRIVER_PROFILE VARCHAR,
    WARNING_MINUTES NUMBER, CRITICAL_MINUTES NUMBER, SLA_STATUS VARCHAR,
    MINUTES_OVER_WARNING FLOAT, ALERT_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
    COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';

-- NOTE: Stream on VW_VEHICLE_TELEMETRY is not supported because the view uses subquery expressions
-- for CONFIG filtering. The LOG_SLA_ALERTS task runs on a schedule instead of stream-triggered.
-- CREATE OR REPLACE STREAM FLEET_INTELLIGENCE.DWELL_ANALYSIS.TELEMETRY_STREAM
--   ON VIEW FLEET_INTELLIGENCE.DWELL_ANALYSIS.VW_VEHICLE_TELEMETRY
--   APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK FLEET_INTELLIGENCE.DWELL_ANALYSIS.LOG_SLA_ALERTS
  WAREHOUSE = ROUTING_ANALYTICS
  SCHEDULE = '5 MINUTE'
  COMMENT = '{"origin":"sf_sit-is-fleet","name":"oss-dwell-analysis","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}'
AS
  MERGE INTO FLEET_INTELLIGENCE.DWELL_ANALYSIS.SLA_ALERT_LOG tgt
  USING (SELECT * FROM FLEET_INTELLIGENCE.DWELL_ANALYSIS.DT_SLA_ALERTS) src
  ON tgt.VEHICLE_ID = src.VEHICLE_ID AND tgt.SESSION_ID = src.SESSION_ID AND tgt.STATUS = src.STATUS
  WHEN NOT MATCHED THEN INSERT (
    VEHICLE_ID, SESSION_ID, STATUS, LOCATION_ID, SESSION_START, SESSION_END,
    DWELL_SECONDS, DWELL_MINUTES, PING_COUNT, AVG_LAT, AVG_LNG, H3_CELL_R7,
    LOCATION_NAME, CITY, FACILITY_TYPE, LOC_TYPE, HOME_BASE_NAME, OPERATING_MODE,
    DRIVER_PROFILE, WARNING_MINUTES, CRITICAL_MINUTES, SLA_STATUS, MINUTES_OVER_WARNING, ALERT_TS
  ) VALUES (
    src.VEHICLE_ID, src.SESSION_ID, src.STATUS, src.LOCATION_ID, src.SESSION_START, src.SESSION_END,
    src.DWELL_SECONDS, src.DWELL_MINUTES, src.PING_COUNT, src.AVG_LAT, src.AVG_LNG, src.H3_CELL_R7,
    src.LOCATION_NAME, src.CITY, src.FACILITY_TYPE, src.LOC_TYPE, src.HOME_BASE_NAME, src.OPERATING_MODE,
    src.DRIVER_PROFILE, src.WARNING_MINUTES, src.CRITICAL_MINUTES, src.SLA_STATUS, src.MINUTES_OVER_WARNING, CURRENT_TIMESTAMP()
  )
  WHEN MATCHED AND tgt.SLA_STATUS != src.SLA_STATUS THEN UPDATE SET
    tgt.DWELL_MINUTES = src.DWELL_MINUTES, tgt.DWELL_SECONDS = src.DWELL_SECONDS,
    tgt.SLA_STATUS = src.SLA_STATUS, tgt.MINUTES_OVER_WARNING = src.MINUTES_OVER_WARNING,
    tgt.SESSION_END = src.SESSION_END, tgt.ALERT_TS = CURRENT_TIMESTAMP();

ALTER TASK FLEET_INTELLIGENCE.DWELL_ANALYSIS.LOG_SLA_ALERTS RESUME;

-- Step 14: Grant Access to Native App
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA FLEET_INTELLIGENCE.DWELL_ANALYSIS TO APPLICATION OPENROUTESERVICE_NATIVE_APP;
GRANT SELECT ON ALL TABLES IN SCHEMA FLEET_INTELLIGENCE.DWELL_ANALYSIS TO APPLICATION OPENROUTESERVICE_NATIVE_APP;
GRANT SELECT ON ALL VIEWS IN SCHEMA FLEET_INTELLIGENCE.DWELL_ANALYSIS TO APPLICATION OPENROUTESERVICE_NATIVE_APP;
